#import "SCILocalize.h"

///
/// Every user-facing string, in both languages.
///
/// The two tables must hold the same keys; tools/check.py fails the build if they
/// drift, if a key is used but never defined, or if a stray quote inside a value
/// leaves Objective-C reading prose as code.
///

static NSDictionary *_enTable = nil;
static NSDictionary *_arTable = nil;

static void SCIBuildTables(void) {
    _enTable = @{
        @"panel_title": @"Albrhi for YouTube",
        @"panel_subtitle": @"Hold two fingers anywhere to open this",

        @"about_title": @"About",
        @"about_author": @"Made by",
        @"about_author_note": @"Ibrahim Ismail AL-Rahn (@ibrahim2100)",
        @"about_version": @"Version",
        @"about_licence": @"Licence",
        @"about_licence_note": @"GPLv3 — free to use, study, change and share",
        @"about_footer": @"Copyright (C) Ibrahim Ismail AL-Rahn. Released under the GNU General Public License v3. The source is at github.com/ibrahim2100/albrhi-repo.\n\nSegment data from SponsorBlock (sponsor.ajay.app), CC BY-NC-SA 4.0. The coloured markers on the progress bar are derived from iSponsorBlock by Galactic Dev, GPLv3. Forced fullscreen direction and the screen dimmer follow YTweaks by fosterbarnes, GPLv3, which in turn credits PoomSmart's YTABConfig.",
        @"section_ads": @"Ads",
        @"section_player": @"Player",
        @"section_general": @"General",

        @"identity_attached": @"Everything attached",
        @"identity_partial": @"Some features could not attach",

        @"hide_ads": @"Hide ads",
        @"hide_ads_note": @"Stops the app asking for ads at all, drops promoted rows out of the feed, and refuses ads before, during and inside the video.",

        @"hide_paid_promotion": @"Hide the paid promotion notice",
        @"hide_paid_promotion_note": @"Removes the banner a creator shows when a video is sponsored. Off by default — it is a disclosure.",

        @"native_pip": @"Picture in picture",
        @"native_pip_note": @"Shrinks the video into a floating window you can move around, drag off screen, or leave running over another app — the system window iOS already gives Safari a video for. Unlocked rather than built: the player already has it, gated by account plan.",
        @"section_motion": @"Motion",
        @"high_refresh_rate": @"Smoother motion (ProMotion)",
        @"high_refresh_rate_note": @"Lets the player redraw at your screen's real top speed instead of a lower rate the app sets on its own. Does nothing on a 60Hz phone — there is no faster to ask for.",
        @"high_refresh_rate_footer": @"Only changes how often a frame already decoded is redrawn — not the quality or the source of the video itself.",
        @"background_playback": @"Keep playing in the background",
        @"background_playback_note": @"Audio carries on when you leave the app or lock the screen.",

        @"block_update_nag": @"Silence the update prompt",
        @"block_update_nag_note": @"Stops YouTube asking you to update, which would replace the app and remove this tweak.",

        @"section_sponsorblock": @"SponsorBlock",
        @"sponsorblock": @"Skip sponsored parts",
        @"sponsorblock_note": @"Uses segments other viewers submitted, so paid plugs and intros are jumped over.",
        @"sponsorblock_notice": @"Say what was skipped",
        @"sponsorblock_notice_note": @"A short line at the top naming what was skipped, with an undo.",
        @"sponsorblock_markers": @"Colour the progress bar",
        @"sponsorblock_markers_note": @"Marks each segment on the bar in its SponsorBlock colour, so you can see what is coming.",

        @"sb_categories": @"What to skip",
        @"sb_sponsor": @"Paid sponsor",
        @"sb_sponsor_note": @"A plug the creator was paid for.",
        @"sb_selfpromo": @"Self-promotion",
        @"sb_selfpromo_note": @"The creator's own merchandise, channel or Patreon.",
        @"sb_interaction": @"Like and subscribe",
        @"sb_interaction_note": @"A reminder to subscribe or hit the bell.",
        @"sb_intro": @"Intro",
        @"sb_intro_note": @"Title animations and intermissions with no content.",
        @"sb_outro": @"Endcards",
        @"sb_outro_note": @"Credits and the end screen.",
        @"sb_preview": @"Recap",
        @"sb_preview_note": @"A summary of what is coming, or of an earlier episode.",
        @"sb_filler": @"Tangents",
        @"sb_filler_note": @"Jokes and asides that are not needed to follow along. Aggressive — off by default.",
        @"sb_music_offtopic": @"Non-music parts",
        @"sb_music_offtopic_note": @"In a music video, the parts that are not the music.",

        @"sb_skipped_format": @"Skipped: %@",
        @"sb_undo": @"Undo",

        @"sb_credit": @"Segment data from SponsorBlock (sponsor.ajay.app), licensed CC BY-NC-SA 4.0. Your video is never sent — only the first four characters of its fingerprint, so the server cannot tell which video you are watching.\n\nThe coloured markers are derived from iSponsorBlock by Galactic Dev (GPLv3).",

        @"dl_audio_only": @"Audio only",
        @"dl_why_no_data": @"YouTube has not handed over any stream information for this video yet. Start playing it, then hold again.",
        @"dl_why_no_formats": @"Stream information arrived but it lists no formats. This build may only stream in pieces, which cannot be saved as a file.",
        @"dl_why_no_urls": @"Found %ld formats iOS can play, but not one of them carries a link to fetch. This build streams in pieces instead of serving files, so there is nothing to download yet.",
        @"dl_why_unknown": @"Nothing could be saved, and the reason is not one this page knows. Settings, Diagnostics has the full report.",

        @"dl_asking": @"Asking YouTube for the formats…",
        @"dl_api_no_links": @"YouTube did not return any downloadable formats for this video. It may be private, age restricted, or blocked where you are.",
        @"dl_why_unplayable_api": @"Found %ld formats, all in a codec iOS will not play. Saving one would give you a file that shows a black screen.",

        @"diag_active_video": @"Actually playing",
        @"diag_stream_attempts": @"Asking YouTube for formats",

        @"dl_hls_none": @"No playlist for this video yet. Start it playing, then hold again.",
        @"dl_hls_no_variants": @"The playlist lists no quality iOS can save. Everything in it is in a codec that would download and then not play.",
        @"dl_hls_no_segments": @"The playlist for that quality is empty.",
        @"dl_hls_unreadable": @"The pieces downloaded, but they do not join into a video this device can read. This build serves them in a form that needs converting.",
        @"dl_ts_empty": @"The download finished with nothing in it. Try again.",
        @"dl_ts_write_failed": @"The video was unwrapped but could not be written out. There may be no room left on the device.",
        @"dl_unknown_quality": @"Unknown quality",
        @"dl_progress_format": @"Saving… %d%%",

        @"verbose_logging": @"Verbose logging",
        @"verbose_logging_note": @"Writes what the tweak is doing to the system log. Leave this off unless you are collecting a report — it is noisy and slows things down.",

        @"diagnostics": @"Diagnostics",
        @"diagnostics_note": @"What the tweak actually finds in your copy of YouTube, and what YouTube said about the video you last played.",

        @"diag_title": @"Diagnostics",
        @"diag_copy": @"Copy report",
        @"diag_copied": @"Report copied",

        @"diag_build": @"Build",
        @"diag_tweak_version": @"Albrhi for YouTube",
        @"diag_app_version": @"YouTube",
        @"diag_bundle": @"Bundle",

        @"diag_attached": @"What attached",
        @"diag_present": @"found",
        @"diag_absent": @"missing",

        @"diag_panel_failed": @"The panel could not be built",

        @"diag_groups": @"Settings groups YouTube built",
        @"diag_groups_none": @"None seen yet. Open YouTube's settings once, then come back.",

        @"diag_sponsor": @"SponsorBlock",
        @"diag_sponsor_none": @"Nothing yet. Play a video with the feature on, then come back.",
        @"diag_sponsor_no_id": @"Could not read a video ID from %@ — no segments were requested.",
        @"diag_sponsor_segments": @"%@: %lu segments matched your categories.",
        @"diag_sponsor_skipped": @"Skipped %@ (%.1fs to %.1fs).",
        @"diag_markers_drawn": @"Markers drawn on %@ (%ld).",
        @"diag_markers_none": @"No progress bar found to draw markers on yet.",

        @"ok": @"OK",

        @"dl_row": @"Save this video",
        @"dl_row_note": @"Downloads the video you are watching to Photos, at the quality you pick.",
        @"dl_shorts_unknown": @"Could not tell which Short this is, so nothing was saved — saving the wrong one is worse. Overlay found: %@. Model: %@. Please send this from Settings, Diagnostics.",
        @"dl_delete_title": @"Delete this?",
        @"dl_delete_body": @"%@\n\nThis removes it from the device. It cannot be undone.",
        @"dl_saved_and_removed": @"Saved to Photos and removed from here.",
        @"dl_already_have": @"You already have this one saved.",
        @"set_tidy_photos": @"Remove from here after saving to Photos",
        @"set_tidy_photos_note": @"Off, a video sent to Photos stays here as well. On, it is removed once Photos has it — which cannot be undone.",
        @"notice_done_title": @"Saved",
        @"notice_done_body": @"%@ finished downloading.",
        @"notice_failed_title": @"Could not save",
        @"notice_failed_body": @"%@ — %@",
        @"set_finish_notice": @"Tell me when a download finishes",
        @"set_finish_notice_note": @"A notification, only when you are not in the app. Downloads carry on when you leave YouTube, so this is how you find out one is done.",
        @"dl_title": @"Save video",
        @"dl_choose_quality": @"Which quality?",
        @"dl_with_audio": @" (fetches audio too)",
        @"dl_saving": @"Saving",
        @"dl_working": @"Downloading, then writing to Photos. This stays open until it is done.",
        @"dl_saved": @"Saved to Photos.",

        // The Download Centre.
        @"dl_rename": @"Rename",
        @"dl_rename_failed": @"That name is already taken, or it is empty.",
        @"welcome_title": @"Albrhi for YouTube",
        @"welcome_body": @"Hold any video to save it. What you save lives in Downloads, beside Home and You — it does not go to Photos unless you send it there. Hold two fingers anywhere to open settings.",
        @"welcome_go": @"Start",
        @"diag_playback": @"Files that would not open",
        @"diag_playback_none": @"None. Everything opened.",
        @"player_unreadable": @"This file will not open",
        @"set_embed_artwork": @"Put the cover inside saved songs",
        @"set_embed_artwork_note": @"Only matters when you send a song somewhere else. It rewrites the file to do it, and a rewrite that goes wrong loses the song — which is why it is off.",
        @"diag_ids": @"Which video each part thinks it is on",
        @"diag_ids_line": @"streams %@ · playing %@ · playlist %@",
        @"diag_shorts_resp": @"What the Shorts model handed over",
        @"diag_shorts_resp_none": @"Nothing. The hook never fired — open a Short, then come back.",
        @"diag_shorts_save": @"Last Shorts save attempt",
        @"diag_shorts_save_none": @"Nothing yet. Tap the save button on a Short, then come back.",
        @"diag_shorts_ads": @"Ads in Shorts",
        @"diag_shorts_ads_none": @"None seen. Either this build shows them another way, or none came up.",
        @"diag_shorts_ads_count": @"%lu refused — %@",

        @"diag_sabr": @"Streaming protocol (SABR)",
        @"diag_sabr_classes": @"reload context: %@   onesie context: %@",
        @"diag_sabr_never": @"Neither gate was consulted. Forcing them would change nothing.",
        @"diag_sabr_gate": @"%@ — asked %lu times, YouTube said %@",
        @"diag_sabr_forced": @"forced by us: %lu",
        @"diag_sabr_video": @"measured while playing %@",


        @"seek_seconds": @"Double-tap jump",
        @"seek_seconds_format": @"%ld seconds",
        @"seek_default": @"YouTube's own (10 seconds)",
        @"seek_seconds_note": @"How far a double tap on the left or right of the video moves.",
        @"extra_speeds": @"Speeds above 2×",
        @"extra_speeds_note": @"Adds 2.25×, 2.5×, 3× and 4× to the speed menu.",

        @"section_hide_player": @"Hide in the player",
        @"hide_ambient_glow": @"Ambient glow",
        @"hide_ambient_glow_note": @"The coloured light that spills from the video onto the page behind it.",
        @"hide_endscreen": @"End screen suggestions",
        @"hide_endscreen_note": @"The grid of other videos that covers the last seconds.",
        @"hide_info_cards": @"Info cards",
        @"hide_info_cards_note": @"The small pop-outs a creator adds partway through a video.",
        @"section_tab_bar": @"Tab bar",
        @"section_tab_bar_note": @"Choose which tabs the bottom bar carries, and in what order. History is one of them.",
        @"set_tabs_arrange": @"Arrange tabs",
        @"set_tabs_arrange_note": @"Drag to reorder, or across to switch one off.",
        @"tabs_active": @"Active",
        @"tabs_preview": @"How the bar will read",
        @"tabs_inactive": @"Off",
        @"tabs_inactive_note": @"Drag one up to switch it on. History is added by Albrhi; the rest are YouTube's own.",
        @"tabs_max_note": @"YouTube draws at most six tabs, and at least one must stay active.",
        @"tabs_empty_note": @"Nothing yet. Open YouTube's own tabs once so the bar can be read, then come back.",
        @"tabs_reset": @"Reset",
        @"tab_home": @"Home",
        @"tab_shorts": @"Shorts",
        @"tab_subscriptions": @"Subscriptions",
        @"tab_you": @"You",
        @"tab_explore": @"Explore",
        @"tab_history": @"History",
        @"tab_uploads": @"Your videos",
        @"section_hide_topbar": @"Hide at the top",
        @"section_hide_topbar_note": @"These are YouTube's own buttons. Everything here is off until you turn it on.",
        @"hide_search_button": @"Search",
        @"hide_notify_button": @"Notifications",
        @"hide_create_button": @"Create",
        @"hide_cast_button": @"Cast",
        @"section_hide_elsewhere": @"Hide elsewhere",
        @"hide_share_promo": @"Promotion in the share sheet",
        @"hide_share_promo_note": @"The extra row YouTube puts above the apps you share to.",

        @"done": @"Done",

        @"page_downloads": @"Downloads",
        @"page_downloads_note": @"Where saved videos go, and the button that saves them",
        @"page_quality": @"Quality",
        @"page_quality_note": @"Resolution limits and the old quality menu",
        @"page_ads": @"Ads",
        @"page_ads_note": @"In the feed, before the video, and inside it",
        @"page_interface": @"Hide things",
        @"page_interface_note": @"Parts of YouTube you can switch off",
        @"page_playback": @"Player",
        @"page_playback_note": @"Background audio, jump distance and speed",
        @"page_display": @"Screen",
        @"page_display_note": @"Fullscreen direction and going darker than iOS allows",
        @"page_sponsor": @"SponsorBlock",
        @"page_sponsor_note": @"Skip the paid parts of a video",
        @"page_general": @"General",
        @"page_general_note": @"Logging and the diagnostics report",
        @"page_about": @"About",
        @"page_about_note": @"Version, licence and credits",

        @"section_fullscreen": @"Fullscreen",
        @"fullscreen_button": @"Fullscreen button",
        @"fullscreen_swipe": @"Swipe up",
        @"fullscreen_note": @"Which way round the video turns.",
        @"fullscreen_footer": @"YouTube decides this from how you are holding the phone, which is wrong every time you are lying down. Set a side and it goes that way whatever the phone thinks. If it comes out the other way round on your device, pick the other one.",
        @"fullscreen_off": @"Leave it to YouTube",
        @"fullscreen_left": @"Turn left",
        @"fullscreen_right": @"Turn right",
        @"fullscreen_portrait": @"Stay upright",

        @"section_brightness": @"Brightness",
        @"dim_enabled": @"Go darker than iOS allows",
        @"dim_enabled_note": @"For a dark room, where the lowest setting is still too bright.",
        @"dim_level": @"How dark",
        @"dim_level_none": @"Off",
        @"dim_level_format": @"%ld%%",
        @"dim_level_note": @"How much light to take away.",
        @"dim_footer": @"This lays a dark layer over the screen rather than turning the backlight down — there is no way to go below the system minimum. On an OLED phone that looks the same; on an LCD the picture dims but the backlight does not. Touch still works through it, and it never goes fully black.",

        @"section_night": @"At night",
        @"night_schedule": @"Only between these hours",
        @"night_schedule_note": @"Outside them the screen is left alone.",
        @"night_from": @"From",
        @"night_to": @"Until",
        @"night_footer": @"An end earlier than the start means across midnight, which is usually what you want — 10:00 PM until 7:00 AM.",

        @"diag_overlay": @"Save button in the player",
        @"diag_overlay_unplaced": @"Never placed in a view.",
        @"diag_overlay_frame": @"Frame %.0f,%.0f %.0f×%.0f — %@",
        @"diag_overlay_frame_inset": @"Top inset %.0f, measured from a control row %.0f tall",
        @"diag_overlay_in_window": @"on screen",
        @"diag_overlay_no_window": @"not in a window",
        @"diag_overlay_none": @"The player's control overlay has not been built yet. Open a video, then come back.",
        @"diag_overlay_counts": @"%lu overlay(s) seen, %lu button(s) made, %@ · %lu tap(s) · %lu show/hide signal(s).\n  %@",
        @"diag_overlay_native": @"built by YouTube's own factory and handed to its layout",
        @"diag_overlay_placed": @"plain button, placed by us — this build has no player-button factory",
        @"diag_overlay_no_host": @"The button was tapped and no view controller was found to present the sheet from.",
        @"diag_overlay_threw": @"Adding the button threw: %@",
        @"diag_native_button": @"YouTube's own download button",
        @"diag_native_button_none": @"Not one of these buttons has been built. This build does not draw the class they live on — nothing here can work, and that is the fault to report.",
        @"diag_native_button_counts": @"%lu button(s) built, %lu of them the download button · %lu tap(s) seen, %lu answered by Albrhi.",
        @"diag_native_button_no_tap": @"No tap answered yet.",
        @"diag_native_button_unknown": @"Tapped, but this build's action view does not answer -hasOfflineButton — left to YouTube rather than guessed at.",
        @"diag_native_button_no_presenter": @"The download button was tapped and there was nothing to present the sheet from. Left to YouTube.",
        @"diag_native_button_ok": @"The download button was tapped and Albrhi answered it.",
        @"set_native_download": @"Answer YouTube's download button",
        @"set_native_download_note": @"Tapping Download saves the video with Albrhi instead of YouTube's offline copy. The button is identified by the app's own flag, not by where it sits.",
        @"set_hold_to_save": @"Hold the video to save",
        @"set_hold_to_save_note": @"Off. YouTube uses a hold on the same picture to speed the video up, and two long presses over one surface is how holding to speed up starts downloading instead.",
        @"diag_shorts": @"Shorts save button",
        @"diag_shorts_none": @"Nothing yet. Open a Short, then come back.",
        @"diag_methods_title": @"THE ACTIONS ROW, AS THIS BUILD DECLARES IT",
        @"diag_methods_list": @"%@ — %lu method(s):\n  %@",
        @"diag_methods_absent": @"%@ is not in this build",
        @"diag_methods_none": @"%@ declares no methods of its own",
        @"diag_scan_title": @"WHAT IS ACTUALLY ON SCREEN",
        @"diag_scan_none": @"  Not run. Open a video, then run the scan from Settings › General.",
        @"diag_scan_found": @"  %lu view(s) under the player, deepest last:\n%@",
        @"diag_scan_nothing": @"  Nothing matched. Either no video is open or this build names its row something else entirely.",
        @"diag_scan_no_window": @"  No window to scan.",
        @"diag_scan_hidden": @"  (hidden)",
        @"licence_row": @"Licence",
        @"licence_row_note": @"Enter a key or a code, see what this device is licensed for, and remove a key.",
        @"scan_watch": @"Scan what is on screen",
        @"scan_watch_note": @"Open a video first, then run this. It writes down the classes YouTube actually built under the player — which is the only way to know where a button can go, and the answer a class dump cannot give.",
        @"scan_done": @"Asked for. Close this now and open a video — the scan is taken ten seconds from now, whatever is on screen then.",
        @"diag_scan_waiting": @"  Asked for — open a video and it is taken from the player itself.",
        @"action_save": @"Save",
        @"set_action_row": @"Save in the actions row",
        @"set_action_row_note": @"Adds a Save button beside Like and Share, built by YouTube itself from one more renderer — so it looks like the buttons next to it and collapses with them when the row runs out of room.",
        @"diag_action_bar_title": @"THE ACTIONS BAR ITSELF",
        @"diag_action_bar": @"%lu bar cell(s) built · %lu button(s) placed\n  %@",
        @"diag_action_bar_none": @"nothing yet — no actions bar has been built this session",
        @"diag_action_bar_absent": @"YTSlimVideoScrollableActionBarCell is not in this build",
        @"diag_action_bar_no_row": @"the cell was built but nothing inside it looks like the row",
        @"diag_action_bar_no_room": @"no gap wide enough between the groups — nothing placed, on purpose",
        @"diag_action_bar_placed": @"placed in the gap between the two groups",
        @"diag_action_row_title": @"SAVE IN THE ACTIONS ROW",
        @"diag_action_row": @"%lu row(s) built by the app · %lu handed to us to fill · %lu renderer(s) added · %lu button(s) found · %lu tap(s)\n  %@",
        @"diag_action_row_none": @"nothing yet — no action row has been built this session",
        @"diag_action_row_nothing": @"nothing recorded yet",
        @"diag_action_row_hooked": @"hooked; waiting for a video to be opened",
        @"diag_action_row_absent": @"YTSlimVideoScrollableDetailsActionsView is not in this build",
        @"diag_action_row_classes": @"the renderer classes are not in this build",
        @"diag_action_row_added": @"renderer added; waiting for YouTube to build the button",
        @"diag_action_row_placed": @"the button was built and marked",
        @"diag_action_row_refused": @"the field %@ was refused: %@",
        @"diag_action_row_threw": @"refused: %@",
        @"diag_action_row_no_host": @"tapped, but there was no controller to present from",
        @"set_pivot_bar": @"Change YouTube's tab bar",
        @"set_pivot_bar_note": @"Adds the Download Centre and History tabs and applies your saved tab order. Applied a moment after the app opens rather than while it is starting — this is what stopped YouTube launching in 1.29.x, and doing it later means a fault here costs a tab rather than the app. Switch it off if the bar misbehaves.",
        @"set_shorts_button": @"Save button in Shorts",
        @"set_shorts_button_note": @"Adds a save button beside like and share. Shorts has no long press to spare, so without this there is no way to save one.",
        @"diag_feed": @"Feed filtering",
        @"diag_feed_none": @"No feed sections seen. Open Home and scroll once, then come back.",
        @"diag_feed_counts": @"%lu sections seen, %lu dropped as promoted.",
        @"diag_tab": @"Downloads tab",
        @"diag_tab_none": @"Nothing yet. It attaches when the tab bar is first built.",
        @"diag_lock_screen": @"Player → lock screen",
        @"diag_lock_screen_none": @"Nothing yet. Recorded the moment a saved video or sound starts playing.",
        @"diag_ad_slots": @"Ad-slot probe",
        @"diag_ad_slots_none": @"Nothing yet. Recorded whenever a video's player response is captured.",
        @"diag_feed_sample": @"Home feed → kept sections",
        @"diag_feed_sample_none": @"Nothing yet. Recorded on every scroll that loads more of Home.",
        @"set_lock_skip": @"Lock screen jumps 15 seconds",
        @"set_lock_skip_note": @"Off, the lock screen gets next and previous. On, it gets 15 seconds back and forward instead. iPhone shows one pair or the other, never both.",
        @"player_speed": @"Playback speed",
        @"player_sleep": @"Stop playing after",
        @"player_sleep_minutes": @"%ld minutes",
        @"player_sleep_end": @"When this one ends",
        @"player_sleep_off": @"Cancel the timer",
        @"section_quality": @"Quality",
        @"set_classic_quality": @"Full quality list",
        @"set_classic_quality_note": @"Show every resolution when you tap quality, instead of the two-line shortcut.",
        @"set_cap_wifi": @"Highest on Wi-Fi",
        @"set_cap_cellular": @"Highest on mobile data",
        @"set_cap_note": @"A ceiling, not a fixed quality. YouTube still drops lower when the connection cannot keep up.",
        @"quality_auto": @"No limit",
        @"quality_cap_format": @"Up to %ldp",
        @"dl_centre_title": @"Downloads",
        @"dl_centre_empty": @"Nothing saved yet",
        @"dl_centre_empty_hint": @"Hold a video to save it. What you save stays here — it does not go to Photos unless you send it.",
        @"dl_started": @"Saving. Watch it in Downloads.",
        @"dl_untitled": @"Video",
        @"dl_in_photos": @"in Photos",
        @"dl_to_photos": @"To Photos",
        @"dl_share": @"Share",
        @"delete": @"Delete",
        @"dl_audio_not_photos": @"Photos holds videos and pictures, not sound. Share it instead.",
        @"dl_no_audio_track": @"There is no sound in this one to keep.",

        // Choosing what to save.
        @"dl_choose_title": @"Save",
        @"dl_kind_video": @"Video",
        @"dl_kind_shorts": @"Shorts",
        @"dl_kind_audio": @"Sound",
        @"dl_kind_thumb": @"Cover",
        @"dl_thumb_header": @"Cover image",
        @"dl_thumb_save": @"Save to Photos",
        @"dl_thumb_where": @"Full size",
        @"dl_thumb_saved": @"Cover saved to Photos.",
        @"dl_thumb_failed": @"That cover could not be saved.",
        @"dl_sound_only": @"Sound only",
        @"dl_sound_small": @"A fraction of the size",
        @"dl_quality_header": @"Quality",
        @"dl_sound_header": @"Sound",
        @"overlay_save": @"Save this video",
        @"overlay_ends_at": @"ends %@",
        @"overlay_header": @"In the player",
        @"overlay_button_title": @"Save button",
        @"overlay_button_note": @"Adds a save button over the video, so a download does not mean leaving the player.",
        @"overlay_endtime_title": @"End time",
        @"overlay_endtime_note": @"Shows the clock time the video finishes at, above the progress bar.",

        // Settings.
        @"set_auto_photos": @"Also save to Photos",
        @"set_auto_photos_note": @"Off: downloads stay in the Download Centre and go to Photos only when you send them.",
        @"set_downloads_title": @"Downloads",
        @"set_open_centre": @"Download Centre",
        @"dl_saved_silent": @"Saved, but without sound — the audio track would not download.",
        @"dl_failed": @"That did not work. The diagnostics page has the detail.",
        @"dl_no_permission": @"Photos refused access. Grant it in iOS Settings → YouTube → Photos, or swipe the row and choose Share.",
        @"dl_no_photos_access": @"YouTube itself declares no way to add to Photos, so nothing here can. Swipe the row and choose Share to keep the file.",
        @"dl_diag_none": @"No saveable format found.",
        @"dl_diag_found": @"%ld video and %ld audio formats with links.",
        @"diag_downloadable": @"Saveable",
        @"cancel": @"Cancel",
        @"diag_truncated": @"— shown up to here. The rest is in the full report, written to %@ and copied whole by the button below.",
        @"diag_page_failed": @"This page could not be opened, and the report was written to %@ instead.",

        @"diag_video": @"Last video played",
        @"diag_no_video": @"Nothing yet. Play a video, then come back to this page.",
        @"diag_video_id": @"Video",
        @"diag_streams": @"Streams offered",
        @"diag_response": @"Full player response",
        @"diag_response_note": @"Everything YouTube told the app about that video. This is the part worth copying — it decides how downloading can work at all.",
        @"set_parallel": @"Simultaneous downloads",
        @"set_parallel_note": @"How many pieces of a video are fetched at once. More is faster; too many and the server may slow you down.",
        @"set_parallel_tested": @" (tested)",
    };

    _arTable = @{
        @"panel_title": @"البرهي ليوتيوب",
        @"panel_subtitle": @"اضغط بإصبعين في أي مكان لفتح هذه اللوحة",

        @"about_title": @"عن الأداة",
        @"about_author": @"من إعداد",
        @"about_author_note": @"إبراهيم إسماعيل الرهن (@ibrahim2100)",
        @"about_version": @"الإصدار",
        @"about_licence": @"الرخصة",
        @"about_licence_note": @"GPLv3 — حرّة في الاستعمال والدراسة والتعديل والمشاركة",
        @"about_footer": @"حقوق النشر (C) إبراهيم إسماعيل الرهن. تصدر برخصة جنو العمومية الإصدار الثالث. المصدر على github.com/ibrahim2100/albrhi-repo.\n\nبيانات المقاطع من سبونسر بلوك (sponsor.ajay.app) برخصة CC BY-NC-SA 4.0. العلامات الملوّنة على شريط التقدّم مشتقّة من iSponsorBlock لـ Galactic Dev برخصة GPLv3. فرض اتجاه ملء الشاشة وإعتام الشاشة يتبعان YTweaks لـ fosterbarnes برخصة GPLv3، وهي بدورها تنسب الفضل إلى YTABConfig لـ PoomSmart.",
        @"section_ads": @"الإعلانات",
        @"section_player": @"المشغّل",
        @"section_general": @"عام",

        @"identity_attached": @"كل شيء مرتبط",
        @"identity_partial": @"بعض المميزات لم ترتبط",

        @"hide_ads": @"حجب الإعلانات",
        @"hide_ads_note": @"يمنع التطبيق من طلبها أصلًا، ويُسقط الصفوف المُموّلة من الخصائص، ويرفض الإعلانات قبل الفيديو وأثناءه والمدموجة فيه.",

        @"hide_paid_promotion": @"إخفاء تنبيه الترويج المدفوع",
        @"hide_paid_promotion_note": @"يُزيل الشريط الذي يظهر عندما يكون الفيديو مموّلًا. مطفأ افتراضيًا — لأنه إفصاح.",

        @"native_pip": @"صورة داخل صورة",
        @"native_pip_note": @"يُصغّر الفيديو إلى نافذة عائمة تحرّكها كما تشاء، أو تتركها فوق تطبيق آخر — نفس النافذة التي يعطيها iOS لفيديو Safari. لم تُبنَ من الصفر، بل فُتحت: المشغّل يملكها أصلاً، وكانت مقفلة بحسب خطة الحساب.",
        @"section_motion": @"الحركة",
        @"high_refresh_rate": @"حركة أنعم (ProMotion)",
        @"high_refresh_rate_note": @"يترك المشغّل يرسم بأعلى سرعة يقدر عليها شاشتك فعلياً، بدل سرعة أقل يفرضها التطبيق بنفسه. لا يفعل شيئاً على شاشة 60 هرتز — لا شيء أسرع يُطلب.",
        @"high_refresh_rate_footer": @"يغيّر فقط عدد مرّات إعادة رسم الإطار الذي فُكّت شفرته أصلاً — لا جودة الفيديو ولا مصدره.",
        @"background_playback": @"الاستمرار في الخلفية",
        @"background_playback_note": @"يكمل الصوت عند خروجك من التطبيق أو قفل الشاشة.",

        @"block_update_nag": @"كتم تنبيه التحديث",
        @"block_update_nag_note": @"يمنع يوتيوب من مطالبتك بالتحديث، فالتحديث يستبدل التطبيق ويُزيل هذه الأداة.",

        @"section_sponsorblock": @"سبونسر بلوك",
        @"sponsorblock": @"تخطّي المقاطع المموّلة",
        @"sponsorblock_note": @"يستخدم مقاطع أرسلها مشاهدون آخرون، فتُتجاوَز الإعلانات المدفوعة والمقدّمات.",
        @"sponsorblock_notice": @"إظهار ما تم تخطّيه",
        @"sponsorblock_notice_note": @"سطر قصير في الأعلى يسمّي ما تُخطّي، ومعه زر تراجع.",
        @"sponsorblock_markers": @"تلوين شريط التقدّم",
        @"sponsorblock_markers_note": @"يعلّم كل مقطع على الشريط بلون سبونسر بلوك الخاص به، فترى ما هو قادم.",

        @"sb_categories": @"ما الذي يُتخطّى",
        @"sb_sponsor": @"إعلان مدفوع",
        @"sb_sponsor_note": @"ترويج تلقّى صاحب القناة مقابلًا عليه.",
        @"sb_selfpromo": @"ترويج ذاتي",
        @"sb_selfpromo_note": @"منتجات صاحب القناة أو قناته أو دعمه.",
        @"sb_interaction": @"طلب الإعجاب والاشتراك",
        @"sb_interaction_note": @"تذكير بالاشتراك أو تفعيل الجرس.",
        @"sb_intro": @"المقدّمة",
        @"sb_intro_note": @"مقدّمات وحركات العنوان بلا محتوى.",
        @"sb_outro": @"الخاتمة",
        @"sb_outro_note": @"الشكر وشاشة النهاية.",
        @"sb_preview": @"التلخيص",
        @"sb_preview_note": @"ملخّص لما سيأتي، أو لحلقة سابقة.",
        @"sb_filler": @"الاستطراد",
        @"sb_filler_note": @"نكات وجُمل جانبية لا يحتاجها الفهم. حادّ — مطفأ افتراضيًا.",
        @"sb_music_offtopic": @"غير الموسيقى",
        @"sb_music_offtopic_note": @"في المقاطع الغنائية، الأجزاء التي ليست موسيقى.",

        @"sb_skipped_format": @"تم تخطّي: %@",
        @"sb_undo": @"تراجع",

        @"sb_credit": @"بيانات المقاطع من سبونسر بلوك (sponsor.ajay.app) برخصة CC BY-NC-SA 4.0. لا يُرسَل الفيديو الذي تشاهده إطلاقًا — تُرسَل أربعة أحرف من بصمته فقط، فلا يعرف الخادم أيّ فيديو تشاهد.\n\nالعلامات الملوّنة مُشتقّة من iSponsorBlock لـ Galactic Dev (رخصة GPLv3).",

        @"dl_audio_only": @"الصوت فقط",
        @"dl_why_no_data": @"يوتيوب لم يُسلّم بعد أي معلومات عن مقاطع هذا الفيديو. شغّله ثم اضغط مطوّلًا مرة أخرى.",
        @"dl_why_no_formats": @"وصلت معلومات المقاطع لكنها بلا صيغ. قد تكون هذه النسخة تبثّ على أجزاء فقط، وهذا لا يُحفَظ كملف.",
        @"dl_why_no_urls": @"وُجدت %ld صيغة يشغّلها iOS، لكن لا واحدة منها تحمل رابطًا للتحميل. هذه النسخة تبثّ على أجزاء بدل أن تقدّم ملفات، فلا شيء يمكن تحميله بعد.",
        @"dl_why_unknown": @"تعذّر حفظ أي شيء، والسبب ليس مما تعرفه هذه الصفحة. التقرير الكامل في الإعدادات ثم التشخيص.",

        @"dl_asking": @"جارٍ سؤال يوتيوب عن الصيغ…",
        @"dl_api_no_links": @"يوتيوب لم يُرجع أي صيغة قابلة للتحميل لهذا الفيديو. قد يكون خاصًّا أو مقيَّدًا بالعمر أو محجوبًا في بلدك.",
        @"dl_why_unplayable_api": @"وُجدت %ld صيغة، كلها بترميز لا يشغّله iOS. حفظ أيّ منها يعطيك ملفًا بشاشة سوداء.",

        @"diag_active_video": @"المُشغَّل فعلًا",
        @"diag_stream_attempts": @"سؤال يوتيوب عن الصيغ",

        @"dl_hls_none": @"لا توجد قائمة تشغيل لهذا الفيديو بعد. شغّله ثم اضغط مطوّلًا مرة أخرى.",
        @"dl_hls_no_variants": @"القائمة لا تعرض جودة يستطيع iOS حفظها. كل ما فيها بترميز يُحمَّل ثم لا يعمل.",
        @"dl_hls_no_segments": @"قائمة تلك الجودة فارغة.",
        @"dl_hls_unreadable": @"نُزّلت الأجزاء، لكنها لا تجتمع في فيديو يقرأه هذا الجهاز. هذا البناء يقدّمها بصيغة تحتاج تحويلًا.",
        @"dl_ts_empty": @"انتهى التنزيل وليس فيه شيء. جرّب مرة أخرى.",
        @"dl_ts_write_failed": @"فُكَّ غلاف الفيديو لكن تعذّرت كتابته. قد لا تكون هناك مساحة كافية على الجهاز.",
        @"dl_unknown_quality": @"جودة غير معروفة",
        @"dl_progress_format": @"جارٍ الحفظ… %d%%",

        @"verbose_logging": @"سجل مفصّل",
        @"verbose_logging_note": @"يكتب ما تفعله الأداة في سجل النظام. اتركه مطفأً إلا إذا كنت تجمع تقريرًا — فهو مزعج ويُبطئ الأداء.",

        @"diagnostics": @"التشخيص",
        @"diagnostics_note": @"ما تجده الأداة فعلًا في نسختك من يوتيوب، وما قاله يوتيوب عن آخر فيديو شغّلته.",

        @"diag_title": @"التشخيص",
        @"diag_copy": @"نسخ التقرير",
        @"diag_copied": @"تم نسخ التقرير",

        @"diag_build": @"النسخة",
        @"diag_tweak_version": @"البرهي ليوتيوب",
        @"diag_app_version": @"يوتيوب",
        @"diag_bundle": @"الحزمة",

        @"diag_attached": @"ما تم ربطه",
        @"diag_present": @"موجود",
        @"diag_absent": @"غير موجود",

        @"diag_panel_failed": @"تعذّر بناء اللوحة",

        @"diag_groups": @"مجموعات الإعدادات التي بناها يوتيوب",
        @"diag_groups_none": @"لم تُرَ بعد. افتح إعدادات يوتيوب مرة ثم ارجع.",

        @"diag_sponsor": @"سبونسر بلوك",
        @"diag_sponsor_none": @"لا شيء بعد. شغّل فيديو والميزة مفعّلة ثم ارجع.",
        @"diag_sponsor_no_id": @"تعذّرت قراءة معرّف الفيديو من %@ — لم تُطلب أي مقاطع.",
        @"diag_sponsor_segments": @"%@: %lu مقطعًا يطابق فئاتك.",
        @"diag_sponsor_skipped": @"تم تخطّي %@ (من %.1f ث إلى %.1f ث).",
        @"diag_markers_drawn": @"رُسمت العلامات على %@ (%ld).",
        @"diag_markers_none": @"لم يُعثر بعد على شريط تقدّم لرسم العلامات عليه.",

        @"ok": @"حسنًا",

        @"dl_row": @"احفظ هذا الفيديو",
        @"dl_row_note": @"ينزّل الفيديو الذي تشاهده إلى الصور، بالجودة التي تختارها.",
        @"dl_shorts_unknown": @"تعذّر تحديد أيّ شورت هذا، فلم يُحفظ شيء — حفظ الخطأ أسوأ. الطبقة: %@. النموذج: %@. أرسل هذا من الإعدادات ثم التشخيص.",
        @"dl_delete_title": @"حذف هذا؟",
        @"dl_delete_body": @"%@\n\nسيُحذف من الجهاز. لا يمكن التراجع.",
        @"dl_saved_and_removed": @"حُفظ في الصور وأُزيل من هنا.",
        @"dl_already_have": @"هذا محفوظ عندك بالفعل.",
        @"set_tidy_photos": @"إزالته من هنا بعد الحفظ في الصور",
        @"set_tidy_photos_note": @"مطفأ: يبقى الفيديو هنا أيضاً بعد إرساله إلى الصور. مشغّل: يُزال بمجرّد وصوله — ولا يمكن التراجع.",
        @"notice_done_title": @"حُفظ",
        @"notice_done_body": @"انتهى تنزيل %@.",
        @"notice_failed_title": @"تعذّر الحفظ",
        @"notice_failed_body": @"%@ — %@",
        @"set_finish_notice": @"أخبرني عند انتهاء التنزيل",
        @"set_finish_notice_note": @"إشعار، ولا يظهر إلا وأنت خارج التطبيق. التنزيل يكمل بعد مغادرتك يوتيوب، وهذه طريقتك لمعرفة أنه انتهى.",
        @"dl_title": @"حفظ الفيديو",
        @"dl_choose_quality": @"أي جودة؟",
        @"dl_with_audio": @" (يجلب الصوت أيضًا)",
        @"dl_saving": @"جارٍ الحفظ",
        @"dl_working": @"يُنزَّل ثم يُكتب في الصور. تبقى هذه النافذة حتى ينتهي.",
        @"dl_saved": @"حُفظ في الصور.",

        // مركز التحميلات.
        @"dl_rename": @"إعادة تسمية",
        @"dl_rename_failed": @"الاسم مستخدم بالفعل، أو فارغ.",
        @"welcome_title": @"البرهي لليوتيوب",
        @"welcome_body": @"اضغط مطوّلًا على أيّ فيديو لحفظه. ما تحفظه يعيش في «التحميلات» بجانب الرئيسية وحسابك — ولا يذهب إلى الصور إلا إذا أرسلته. اضغط بإصبعين في أيّ مكان لفتح الإعدادات.",
        @"welcome_go": @"ابدأ",
        @"diag_playback": @"ملفات لم تُفتح",
        @"diag_playback_none": @"لا شيء. كل شيء فُتح.",
        @"player_unreadable": @"هذا الملف لا يُفتح",
        @"set_embed_artwork": @"وضع الصورة داخل الأغاني المحفوظة",
        @"set_embed_artwork_note": @"لا يهمّ إلا حين ترسل أغنية إلى مكان آخر. يُعيد كتابة الملف ليفعلها، وإعادة كتابة تفشل تُفقد الأغنية — ولهذا هو مطفأ.",
        @"diag_ids": @"أيّ فيديو يظنّ كل جزء أنه عليه",
        @"diag_ids_line": @"التدفّقات %@ · يعمل %@ · قائمة التشغيل %@",
        @"diag_shorts_resp": @"ما سلّمه نموذج الشورتس",
        @"diag_shorts_resp_none": @"لا شيء. الخطّاف لم يعمل إطلاقاً — افتح شورت ثم عد.",
        @"diag_shorts_save": @"آخر محاولة حفظ شورت",
        @"diag_shorts_save_none": @"لا شيء بعد. اضغط زر الحفظ على شورت ثم عد.",
        @"diag_shorts_ads": @"إعلانات الشورتس",
        @"diag_shorts_ads_none": @"لم يُرَ شيء. إمّا أن هذا البناء يعرضها بطريقة أخرى، أو لم يظهر أيّ إعلان.",
        @"diag_shorts_ads_count": @"رُفض %lu — %@",

        @"diag_sabr": @"بروتوكول البثّ (SABR)",
        @"diag_sabr_classes": @"سياق إعادة التحميل: %@   سياق الطلب: %@",
        @"diag_sabr_never": @"لم يُسأل أيّ من البوّابتين. فرضهما لن يُغيّر شيئاً.",
        @"diag_sabr_gate": @"%@ — سُئلت %lu مرّة، وجواب يوتيوب %@",
        @"diag_sabr_forced": @"فرضناها: %lu",
        @"diag_sabr_video": @"قيست أثناء تشغيل %@",


        @"seek_seconds": @"قفزة النقر المزدوج",
        @"seek_seconds_format": @"%ld ثانية",
        @"seek_default": @"ما يفعله يوتيوب (١٠ ثوانٍ)",
        @"seek_seconds_note": @"كم يتقدّم الفيديو أو يرجع عند النقر مرّتين على يمينه أو يساره.",
        @"extra_speeds": @"سرعات فوق ٢×",
        @"extra_speeds_note": @"يُضيف ٢٫٢٥× و٢٫٥× و٣× و٤× إلى قائمة السرعة.",

        @"section_hide_player": @"إخفاء في المشغّل",
        @"hide_ambient_glow": @"الوهج المحيط",
        @"hide_ambient_glow_note": @"الضوء الملوّن الذي يتسرّب من الفيديو إلى الصفحة خلفه.",
        @"hide_endscreen": @"اقتراحات نهاية الفيديو",
        @"hide_endscreen_note": @"شبكة الفيديوهات التي تُغطّي الثواني الأخيرة.",
        @"hide_info_cards": @"بطاقات المعلومات",
        @"hide_info_cards_note": @"النوافذ الصغيرة التي يُضيفها صاحب القناة في منتصف الفيديو.",
        @"section_tab_bar": @"الشريط السفلي",
        @"section_tab_bar_note": @"اختر التبويبات التي يحملها الشريط السفلي وترتيبها، والسجل واحد منها.",
        @"set_tabs_arrange": @"ترتيب التبويبات",
        @"set_tabs_arrange_note": @"اسحب لتغيير الترتيب، أو إلى القائمة الأخرى لإيقاف تبويب.",
        @"tabs_active": @"مفعّلة",
        @"tabs_preview": @"كيف سيقرأ الشريط",
        @"tabs_inactive": @"موقوفة",
        @"tabs_inactive_note": @"اسحب أيّاً منها إلى الأعلى لتفعيله. السجل يضيفه البرهي، والبقية من يوتيوب نفسه.",
        @"tabs_max_note": @"يوتيوب يرسم ستّة تبويبات على الأكثر، ويجب أن يبقى واحد مفعّلاً.",
        @"tabs_empty_note": @"لا شيء بعد. افتح تبويبات يوتيوب مرّة ليُقرأ الشريط، ثم عد إلى هنا.",
        @"tabs_reset": @"إعادة",
        @"tab_home": @"الرئيسية",
        @"tab_shorts": @"شورتس",
        @"tab_subscriptions": @"الاشتراكات",
        @"tab_you": @"أنت",
        @"tab_explore": @"استكشاف",
        @"tab_history": @"السجل",
        @"tab_uploads": @"فيديوهاتك",
        @"section_hide_topbar": @"إخفاء في الشريط العلوي",
        @"section_hide_topbar_note": @"هذه أزرار يوتيوب نفسه. كلّ ما هنا مُطفأ حتّى تُشغّله.",
        @"hide_search_button": @"البحث",
        @"hide_notify_button": @"الإشعارات",
        @"hide_create_button": @"الإنشاء",
        @"hide_cast_button": @"البثّ إلى شاشة",
        @"section_hide_elsewhere": @"إخفاء في أماكن أخرى",
        @"hide_share_promo": @"الترويج في نافذة المشاركة",
        @"hide_share_promo_note": @"الصفّ الإضافي الذي يضعه يوتيوب فوق التطبيقات التي تُشارك إليها.",

        @"done": @"تمّ",

        @"page_downloads": @"التحميلات",
        @"page_downloads_note": @"أين تذهب الفيديوهات المحفوظة، وزرّ الحفظ",
        @"page_quality": @"الجودة",
        @"page_quality_note": @"حدود الدقّة وقائمة الجودة القديمة",
        @"page_ads": @"الإعلانات",
        @"page_ads_note": @"في الصفحة الرئيسيّة، وقبل الفيديو، وداخله",
        @"page_interface": @"إخفاء عناصر",
        @"page_interface_note": @"أجزاء من يوتيوب يمكنك إطفاؤها",
        @"page_playback": @"المشغّل",
        @"page_playback_note": @"الصوت في الخلفيّة، ومسافة القفز، والسرعة",
        @"page_display": @"الشاشة",
        @"page_display_note": @"اتجاه ملء الشاشة، والإعتام تحت حدّ النظام",
        @"page_sponsor": @"سبونسر بلوك",
        @"page_sponsor_note": @"تخطّي الأجزاء المدفوعة من الفيديو",
        @"page_general": @"عامّ",
        @"page_general_note": @"السجلّ وتقرير التشخيص",
        @"page_about": @"حول",
        @"page_about_note": @"الإصدار والرخصة والحقوق",

        @"section_fullscreen": @"ملء الشاشة",
        @"fullscreen_button": @"زرّ ملء الشاشة",
        @"fullscreen_swipe": @"السحب لأعلى",
        @"fullscreen_note": @"إلى أيّ جهة يدور الفيديو.",
        @"fullscreen_footer": @"يوتيوب يُقرّر هذا من طريقة إمساكك بالهاتف، وهو خطأ في كل مرّة تكون فيها مُستلقياً. اختر جهة فيذهب إليها مهما ظنّ الهاتف. وإن جاء بالعكس على جهازك، اختر الجهة الأخرى.",
        @"fullscreen_off": @"اتركه ليوتيوب",
        @"fullscreen_left": @"يساراً",
        @"fullscreen_right": @"يميناً",
        @"fullscreen_portrait": @"عموديّاً",

        @"section_brightness": @"السطوع",
        @"dim_enabled": @"أغمق ممّا يسمح به النظام",
        @"dim_enabled_note": @"لغرفة مظلمة، حيث أقلّ إعداد ما زال ساطعاً.",
        @"dim_level": @"مقدار الإعتام",
        @"dim_level_none": @"مُطفأ",
        @"dim_level_format": @"%ld٪",
        @"dim_level_note": @"كم من الضوء يُؤخذ.",
        @"dim_footer": @"هذا يضع طبقة داكنة فوق الشاشة ولا يُخفّض الإضاءة الخلفيّة — لا سبيل للنزول تحت حدّ النظام. على شاشة OLED تبدو النتيجة واحدة؛ على LCD تُعتم الصورة دون الإضاءة. اللمس يعمل من خلالها، ولا تصل إلى السواد الكامل أبداً.",

        @"section_night": @"في الليل",
        @"night_schedule": @"بين هاتين الساعتين فقط",
        @"night_schedule_note": @"وخارجهما تُترك الشاشة كما هي.",
        @"night_from": @"من",
        @"night_to": @"إلى",
        @"night_footer": @"نهاية أبكر من البداية تعني عبور منتصف الليل، وهو المقصود عادةً — من ١٠ مساءً إلى ٧ صباحاً.",

        @"diag_overlay": @"زر الحفظ داخل المشغّل",
        @"diag_overlay_unplaced": @"لم يوضع في أي عرض.",
        @"diag_overlay_frame": @"الإطار ‎%.0f,%.0f‏ ‎%.0f×%.0f‏ — %@",
        @"diag_overlay_frame_inset": @"إزاحة علوية ‎%.0f‏، مقيسة من صفّ أزرارٍ ارتفاعه ‎%.0f‏",
        @"diag_overlay_in_window": @"ظاهر على الشاشة",
        @"diag_overlay_no_window": @"ليس داخل نافذة",
        @"diag_overlay_none": @"لم تُبنَ طبقة أزرار المشغّل بعد. افتح فيديو ثم عد.",
        @"diag_overlay_counts": @"‏%lu طبقة رُئيت، و%lu زر صُنع، %@ · %lu ضغطة · %lu إشارة ظهور/اختفاء.\n  %@",
        @"diag_overlay_native": @"مصنوع بمصنع يوتيوب نفسه ومُسلَّم إلى تخطيطه",
        @"diag_overlay_placed": @"زر عادي وضعناه نحن — هذه النسخة لا تملك مصنع أزرار المشغّل",
        @"diag_overlay_no_host": @"ضُغط الزر ولم يوجد متحكّم عرضٍ تُعرض منه النافذة.",
        @"diag_overlay_threw": @"إضافة الزر رمت استثناءً: %@",
        @"diag_native_button": @"زر التحميل الأصلي في يوتيوب",
        @"diag_native_button_none": @"لم يُبنَ أيّ زرٍّ من هذا الصف. هذه النسخة لا ترسم الصنف الذي تعيش فيه هذه الأزرار — لا شيء هنا يمكن أن يعمل، وهذا هو العطب الذي يُبلَّغ عنه.",
        @"diag_native_button_counts": @"‏%lu زرًّا بُني، منها %lu زر التحميل · %lu ضغطة رُئيت، و%lu أجابها البرهي.",
        @"diag_native_button_no_tap": @"لم تُجَب أي ضغطة بعد.",
        @"diag_native_button_unknown": @"ضُغط، لكن صفّ الأزرار في هذه النسخة لا يجيب ‎-hasOfflineButton — تُرك ليوتيوب بدل التخمين.",
        @"diag_native_button_no_presenter": @"ضُغط زر التحميل ولم يوجد ما تُعرض منه النافذة. تُرك ليوتيوب.",
        @"diag_native_button_ok": @"ضُغط زر التحميل وأجابه البرهي.",
        @"set_native_download": @"أجب زر التحميل الأصلي",
        @"set_native_download_note": @"ضغط زر التحميل يحفظ الفيديو ببرهان بدل النسخة دون اتصال من يوتيوب. الزر يُعرَف من علامة التطبيق نفسه، لا من موضعه.",
        @"set_hold_to_save": @"الضغط المطوّل على الفيديو للحفظ",
        @"set_hold_to_save_note": @"معطّل. يوتيوب يستخدم الضغط المطوّل على الصورة نفسها لتسريع الفيديو، وضغطتان مطوّلتان على سطح واحد هي سبب تحوّل التسريع إلى تحميل.",
        @"diag_shorts": @"زر الحفظ في الشورتس",
        @"diag_shorts_none": @"لا شيء بعد. افتح شورت ثم عد.",
        @"diag_methods_title": @"صفّ الأزرار كما يعلنه هذا البناء",
        @"diag_methods_list": @"‏%@ — %lu دالّة:\n  %@",
        @"diag_methods_absent": @"‏%@ غير موجود في هذا البناء",
        @"diag_methods_none": @"‏%@ لا يعلن دوالّ خاصة به",
        @"diag_scan_title": @"ما هو معروض فعلاً",
        @"diag_scan_none": @"  لم يُنفَّذ. افتح فيديو، ثم شغّل الفحص من الإعدادات › عام.",
        @"diag_scan_found": @"  ‏%lu عرضاً تحت المشغّل، الأعمق أخيراً:\n%@",
        @"diag_scan_nothing": @"  لا شيء طابق. إمّا لا فيديو مفتوح، أو أن هذا البناء يسمّي صفّه باسم آخر تماماً.",
        @"diag_scan_no_window": @"  لا توجد نافذة تُفحص.",
        @"diag_scan_hidden": @"  (مخفي)",
        @"licence_row": @"الترخيص",
        @"licence_row_note": @"أدخل مفتاحاً أو كوداً، واعرف ما يغطّيه ترخيص هذا الجهاز، وأزل المفتاح.",
        @"scan_watch": @"افحص ما هو معروض",
        @"scan_watch_note": @"افتح فيديو أولاً ثم شغّل هذا. يسجّل الأصناف التي بناها اليوتيوب فعلاً تحت المشغّل — وهي الطريقة الوحيدة لمعرفة أين يمكن وضع زر، والجواب الذي لا يعطيه تفريغ الأصناف.",
        @"scan_done": @"طُلب الفحص. أغلق هذه الشاشة الآن وافتح فيديو — يُلتقط الفحص بعد عشر ثوانٍ مهما كان المعروض حينها.",
        @"diag_scan_waiting": @"  طُلب — افتح فيديو ويُؤخذ من المشغّل نفسه.",
        @"action_save": @"حفظ",
        @"set_action_row": @"زر الحفظ مع الإعجاب والمشاركة",
        @"set_action_row_note": @"يضيف زرّ حفظ بجانب الإعجاب والمشاركة، يبنيه اليوتيوب نفسه من مُصيّرٍ إضافي — فيبدو كالأزرار المجاورة له وينطوي معها حين يضيق الصفّ.",
        @"diag_action_bar_title": @"شريط الأزرار نفسه",
        @"diag_action_bar": @"‏%lu خليّة شريط بُنيت · %lu زرّاً وُضع\n  %@",
        @"diag_action_bar_none": @"لا شيء بعد — لم يُبنَ شريط أزرار في هذه الجلسة",
        @"diag_action_bar_absent": @"‏YTSlimVideoScrollableActionBarCell غير موجود في هذا البناء",
        @"diag_action_bar_no_row": @"بُنيت الخليّة ولا شيء بداخلها يشبه الصفّ",
        @"diag_action_bar_no_room": @"لا فجوة واسعة بين المجموعتين — لم يُوضع شيء، عن قصد",
        @"diag_action_bar_placed": @"وُضع في الفجوة بين المجموعتين",
        @"diag_action_row_title": @"زر الحفظ في صفّ الأزرار",
        @"diag_action_row": @"‏%lu صفّاً بناه التطبيق · %lu سُلّم إلينا لملئه · %lu مُصيّراً أُضيف · %lu زرّاً وُجد · %lu ضغطة\n  %@",
        @"diag_action_row_none": @"لا شيء بعد — لم يُبنَ أيّ صفّ أزرار في هذه الجلسة",
        @"diag_action_row_nothing": @"لم يُسجَّل شيء بعد",
        @"diag_action_row_hooked": @"مربوط؛ بانتظار فتح فيديو",
        @"diag_action_row_absent": @"‏YTSlimVideoScrollableDetailsActionsView غير موجود في هذا البناء",
        @"diag_action_row_classes": @"أصناف المُصيّرات غير موجودة في هذا البناء",
        @"diag_action_row_added": @"أُضيف المُصيّر؛ بانتظار أن يبني اليوتيوب الزر",
        @"diag_action_row_placed": @"بُني الزر ووُسم",
        @"diag_action_row_refused": @"رُفض الحقل %@: %@",
        @"diag_action_row_threw": @"رُفض: %@",
        @"diag_action_row_no_host": @"ضُغط، لكن لم يوجد متحكّم يُعرض منه",
        @"set_pivot_bar": @"تعديل شريط تبويبات اليوتيوب",
        @"set_pivot_bar_note": @"يضيف تبويب مركز التحميلات وتبويب السجل، ويطبّق ترتيب التبويبات المحفوظ. يُطبَّق بعد فتح التطبيق بلحظة لا أثناء إقلاعه — وهذا ما كان يمنع اليوتيوب من الإقلاع في 1.29.x، وتأجيله يجعل أي خلل هنا يكلّف تبويباً لا التطبيق. أطفئه إن اضطرب الشريط.",
        @"set_shorts_button": @"زر الحفظ في الشورتس",
        @"set_shorts_button_note": @"يضيف زر حفظ بجانب الإعجاب والمشاركة. الشورتس لا يملك ضغطة مطوّلة فارغة، فبدونه لا سبيل لحفظه.",
        @"diag_feed": @"ترشيح الصفحة الرئيسية",
        @"diag_feed_none": @"لم تُرَ أقسام. افتح الرئيسية ومرّر مرّة، ثم عد.",
        @"diag_feed_counts": @"%lu قسمًا شوهد، و%lu أُسقط كإعلان.",
        @"diag_tab": @"تبويب التحميلات",
        @"diag_tab_none": @"لا شيء بعد. يتعلّق عند أوّل بناء لشريط التبويب.",
        @"diag_lock_screen": @"المشغّل ← شاشة القفل",
        @"diag_lock_screen_none": @"لا شيء بعد. يُسجَّل عند بدء تشغيل فيديو أو صوت محفوظ.",
        @"diag_ad_slots": @"فحص فتحات الإعلان",
        @"diag_ad_slots_none": @"لا شيء بعد. يُسجَّل كل مرة تُلتقط فيها استجابة مشغّل فيديو.",
        @"diag_feed_sample": @"صفحة الهوم ← الأقسام المُبقاة",
        @"diag_feed_sample_none": @"لا شيء بعد. يُسجَّل عند كل تمرير يحمّل المزيد من الهوم.",
        @"set_lock_skip": @"قفزة ١٥ ثانية في شاشة القفل",
        @"set_lock_skip_note": @"مطفأ: تظهر أزرار التالي والسابق. مشغّل: تظهر بدلها قفزة ١٥ ثانية للأمام والخلف. الآيفون يعرض زوجاً واحداً لا الاثنين.",
        @"player_speed": @"سرعة التشغيل",
        @"player_sleep": @"إيقاف التشغيل بعد",
        @"player_sleep_minutes": @"%ld دقيقة",
        @"player_sleep_end": @"عند انتهاء هذا",
        @"player_sleep_off": @"إلغاء المؤقّت",
        @"section_quality": @"الجودة",
        @"set_classic_quality": @"قائمة الجودة الكاملة",
        @"set_classic_quality_note": @"إظهار كل الدقّات عند الضغط على الجودة، بدل الاختصار ذي السطرين.",
        @"set_cap_wifi": @"الأعلى على الواي فاي",
        @"set_cap_cellular": @"الأعلى على بيانات الجوال",
        @"set_cap_note": @"سقف لا جودة ثابتة. يوتيوب ينزل أقلّ إن لم يتحمّل الاتصال.",
        @"quality_auto": @"بلا حدّ",
        @"quality_cap_format": @"حتى %ldp",
        @"dl_centre_title": @"التحميلات",
        @"dl_centre_empty": @"لا شيء محفوظ بعد",
        @"dl_centre_empty_hint": @"اضغط مطوّلًا على الفيديو لحفظه. ما تحفظه يبقى هنا — ولا يذهب إلى الصور إلا إذا أرسلته.",
        @"dl_started": @"جارٍ الحفظ. تابعه في التحميلات.",
        @"dl_untitled": @"فيديو",
        @"dl_in_photos": @"في الصور",
        @"dl_to_photos": @"إلى الصور",
        @"dl_share": @"مشاركة",
        @"delete": @"حذف",
        @"dl_audio_not_photos": @"الصور تحفظ الفيديو والصور لا الصوت. شاركه بدل ذلك.",
        @"dl_no_audio_track": @"لا صوت في هذا لحفظه.",

        // اختيار ما يُحفظ.
        @"dl_choose_title": @"حفظ",
        @"dl_kind_video": @"فيديو",
        @"dl_kind_shorts": @"شورتس",
        @"dl_kind_audio": @"صوت",
        @"dl_kind_thumb": @"الغلاف",
        @"dl_thumb_header": @"صورة الغلاف",
        @"dl_thumb_save": @"حفظ في الصور",
        @"dl_thumb_where": @"بالحجم الكامل",
        @"dl_thumb_saved": @"حُفظ الغلاف في الصور.",
        @"dl_thumb_failed": @"تعذّر حفظ هذا الغلاف.",
        @"dl_sound_only": @"الصوت فقط",
        @"dl_sound_small": @"جزء يسير من الحجم",
        @"dl_quality_header": @"الجودة",
        @"dl_sound_header": @"الصوت",
        @"overlay_save": @"حفظ هذا الفيديو",
        @"overlay_ends_at": @"ينتهي %@",
        @"overlay_header": @"داخل المشغّل",
        @"overlay_button_title": @"زر الحفظ",
        @"overlay_button_note": @"يضيف زر حفظ فوق الفيديو، فلا يعني التنزيل مغادرة المشغّل.",
        @"overlay_endtime_title": @"وقت الانتهاء",
        @"overlay_endtime_note": @"يعرض الساعة التي ينتهي عندها الفيديو، فوق شريط التقدّم.",

        // الإعدادات.
        @"set_auto_photos": @"احفظ في الصور أيضًا",
        @"set_auto_photos_note": @"مُطفأ: تبقى التحميلات في مركز التحميلات ولا تذهب إلى الصور إلا حين ترسلها.",
        @"set_downloads_title": @"التحميلات",
        @"set_open_centre": @"مركز التحميلات",
        @"dl_saved_silent": @"حُفظ لكن بلا صوت — تعذّر تنزيل مسار الصوت.",
        @"dl_failed": @"لم ينجح ذلك. التفصيل في صفحة التشخيص.",
        @"dl_no_permission": @"رُفض الوصول إلى الصور. امنحه من إعدادات iOS ← يوتيوب ← الصور، أو اسحب الصف واختر «مشاركة».",
        @"dl_no_photos_access": @"يوتيوب نفسه لا يعلن إذناً للإضافة إلى الصور، فلا شيء هنا يستطيعها. اسحب الصف واختر «مشاركة» لحفظ الملف.",
        @"dl_diag_none": @"لم يُعثر على صيغة قابلة للحفظ.",
        @"dl_diag_found": @"%ld صيغة فيديو و%ld صيغة صوت بروابط.",
        @"diag_downloadable": @"قابلية الحفظ",
        @"cancel": @"إلغاء",
        @"diag_truncated": @"— يُعرض إلى هنا. البقية في التقرير الكامل، وقد كُتب في %@ ويَنسخه الزر أدناه كاملًا.",
        @"diag_page_failed": @"تعذّر فتح هذه الصفحة، وكُتب التقرير في %@ بدلًا من ذلك.",

        @"diag_video": @"آخر فيديو شُغّل",
        @"diag_no_video": @"لا شيء بعد. شغّل فيديو ثم ارجع إلى هذه الصفحة.",
        @"diag_video_id": @"الفيديو",
        @"diag_streams": @"الصيغ المعروضة",
        @"diag_response": @"استجابة المشغّل كاملة",
        @"diag_response_note": @"كل ما قاله يوتيوب للتطبيق عن ذلك الفيديو. هذا هو الجزء الذي يستحق النسخ — فهو يحدّد كيف يمكن للتحميل أن يعمل أصلًا.",
        @"set_parallel": @"التنزيلات المتزامنة",
        @"set_parallel_note": @"كم قطعة من الفيديو تُجلب في وقتٍ واحد. الأكثر أسرع، والزائد قد يجعل الخادم يبطّئك.",
        @"set_parallel_tested": @" (المُجرَّب)",
    };
}

NSString *SCILocalized(NSString *key) {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        SCIBuildTables();
    });

    // The device's own preference, not the app's. Someone whose phone is Arabic is an
    // Arabic reader even if they left YouTube in English, and this tweak's strings are
    // its own rather than YouTube's.
    NSString *language = [[NSLocale preferredLanguages] firstObject] ?: @"en";
    BOOL arabic = [language hasPrefix:@"ar"];

    NSDictionary *table = arabic ? _arTable : _enTable;
    NSString *value = table[key];

    return value ?: (_enTable[key] ?: key);
}
