#import "SCILocalize.h"

///
/// Every user-facing string, in both languages.
///
/// The two tables must hold the same keys; tools/check.py fails the build if they
/// drift, if a key is used but never defined, or if a stray quote inside a value
/// leaves Objective-C reading prose as code.
///

static NSDictionary *_enTable = nil;
static NSDictionary *_arTable = nil;

static void SCIBuildTables(void) {
    _enTable = @{
        @"title": @"Albrhi for X",
        @"done": @"Done",
        @"cancel": @"Cancel",
        @"ok": @"OK",

        @"section_media": @"Save media",
        @"media_footer": @"Everything X has shown you since you opened it, newest first. Tap one to save it to Photos. Videos are saved at the best quality X offers.",
        @"media_video": @"Video",
        @"media_gif": @"GIF",
        @"media_image": @"Photo",
        @"save_working": @"Saving…",
        @"save_done": @"Saved to Photos",
        @"save_failed": @"Could not save this one.",
        @"save_no_permission": @"X needs permission to add to Photos. Settings › X › Photos.",
        @"menu_forget_media": @"Clear the media list",

        @"section_features": @"Features",
        @"features_footer": @"Each of these sets a group of X's own switches at once. Every switch it touches is one your phone reported, so they are all really there — but what each one does is read from its name, not from X's source code. If something looks wrong, turn it off and X goes straight back to normal.",
        @"detail_feature_on": @"On, from “%@”",
        @"detail_feature_off": @"Off, from “%@”",

        @"f_ads": @"Hide ads",
        @"f_ads_note": @"Turns off the promoted posts in the timeline, before videos, on profiles and in search — and turns on X's own rules that keep an ad out of the first slot.",
        @"f_promote": @"Hide the Promote button",
        @"f_promote_note": @"Removes “Promote this post” and the labels around it from your own posts.",
        @"f_grok": @"Hide Grok",
        @"f_grok_note": @"Removes the Grok button under posts, from the menus, from the tab bar and from the side menu. Grok itself is untouched if you open it yourself.",
        @"f_autotranslate": @"Stop translating by itself",
        @"f_autotranslate_note": @"X translates posts and bios without being asked — this is the busiest switch on your phone by far. Turning it off leaves the Translate button exactly where it is.",
        @"f_upsell": @"Hide Premium ads",
        @"f_upsell_note": @"The offers, the badges and the pages nudging you to subscribe. It does not touch a subscription you already have.",
        @"f_tracking": @"Send less about me",
        @"f_tracking_note": @"Turns off the usage reports X sends about your scrolling, your storage, your connection and your crashes, and two outside services it carries. It does not touch how X verifies your device — that one can get an account locked, so it is not offered.",
        @"f_clutter": @"Clean up the interface",
        @"f_clutter_note": @"Tips, nudges, reminders, like animations, the rings around avatars and branded decorations on posts.",
        @"f_viewcounts": @"Hide view counts",
        @"f_viewcounts_note": @"Removes the number of views under posts, and the rank badge beside it.",
        @"f_spaces": @"Hide Spaces",
        @"f_spaces_note": @"Hides the Spaces strip, the Spaces tab and the button to start one. A Space you open deliberately still works.",
        @"f_sensitive": @"Show sensitive posts directly",
        @"f_sensitive_note": @"Skips the “this may contain sensitive content” cover. It hides a warning, so it is off unless you turn it on.",
        @"f_safari": @"Open links in Safari",
        @"f_safari_note": @"Switches off X's in-app browser, so links open in Safari.",
        @"f_gif": @"Do not play GIFs by themselves",
        @"f_gif_note": @"Makes animated images follow your autoplay setting like videos do, instead of ignoring it.",
        @"f_zoom": @"Zoom without opening",
        @"f_zoom_note": @"Pinch an image in the timeline to zoom it in place.",
        @"f_gestures": @"More gestures",
        @"f_gestures_note": @"Swipes on posts, the reworked tab bar gestures, and tapping a name to open the profile.",
        @"f_tabs": @"More tabs",
        @"f_tabs_note": @"Puts Communities and your profile in the bottom bar, and allows extra pinned timelines.",
        @"f_privacy": @"Keep my likes private",
        @"f_privacy_note": @"Turns on hiding your likes and your subscriptions on your profile, and the settings for who may mention you. You still choose them in X's own settings.",
        @"f_launch": @"Open faster",
        @"f_launch_note": @"Skips the launch animation and stops X loading tabs you have not opened yet.",
        @"f_perf": @"Speed tweaks (experimental)",
        @"f_perf_note": @"Turns on X's own speed work that it ships switched off. It may be smoother, and it may be worse — this is the one here where that can happen. Easy to turn back off.",

        @"section_albrhi": @"Albrhi",
        @"section_links": @"Links and privacy",
        @"section_links_note": @"None of these tells X anything untrue. They change what a link carries and who can open the app.",
        @"section_timeline": @"Between the posts",
        @"section_timeline_note": @"Every switch here removes something that works, so all of them start off.",
        @"section_posts": @"On a post",
        @"section_posts_note": @"X lays this row out by hand, so a hidden button may leave its space behind. The report says how many were hidden.",
        @"section_extras": @"Extras",
        @"section_advanced": @"Advanced",
        @"page_albrhi_note": @"Saving, and the confirmations before a repost, a like or a follow.",
        @"page_extras_note": @"Undo, translation, upload quality, and text direction.",
        @"page_advanced_note": @"The raw switch list, the log, and what attached.",
        @"set_strip_tracking": @"Clean copied links",
        @"set_strip_tracking_note": @"Removes the two parameters that name the account a link was shared from.",
        @"set_expand_links": @"Show the real link",
        @"set_expand_links_note": @"Where a link goes, instead of the t.co wrapper.",
        @"set_no_search_history": @"No search history",
        @"set_no_search_history_note": @"Empties the recent row — searches and accounts — and stops new ones being written down. What is already stored is left alone, and X still keeps its own copy on its servers.",
        @"set_app_lock": @"Lock the app",
        @"set_app_lock_note": @"Face ID or your passcode before X shows anything. A device that can do neither is let through.",
        @"set_hide_who_to_follow": @"Hide who to follow",
        @"set_hide_who_to_follow_note": @"Account suggestions in the timeline and on profiles.",
        @"set_hide_topics": @"Hide topics",
        @"set_hide_topics_note": @"Topic banners and the prompts to follow one.",
        @"set_hide_trend_videos": @"Hide trend videos",
        @"set_hide_trend_videos_note": @"The video modules attached to trends.",
        @"set_hide_bookmark": @"Hide bookmark button",
        @"set_tweet_to_image": @"Post as a picture",
        @"set_tweet_to_image_note": @"A long press on share renders the post and offers it to share as an image.",
        @"set_full_frame": @"Show photos whole",
        @"set_full_frame_note": @"A single photo drawn in full instead of cropped. Videos and grids are left alone.",
        @"set_undo_post": @"Offer to undo a post",
        @"set_undo_post_note": @"Forces the toast X sometimes shows after posting.",
        @"set_copy_profile": @"Copy from a profile",
        @"set_copy_profile_note": @"A long press on the profile header offers its name, handle and bio as text.",
        @"set_bio_translate": @"Always offer to translate a bio",
        @"set_high_quality_upload": @"High quality uploads",
        @"set_high_quality_upload_note": @"Shows X's own setting for uploading photos at full resolution.",
        @"set_disable_rtl": @"Force left-to-right text",
        @"set_disable_rtl_note": @"Changes the direction of every piece of text X draws, not only the one you meant.",
        @"set_confirm_like": @"Confirm a like",
        @"set_confirm_like_note": @"Asks before liking. Taking a like back is never asked about.",
        @"set_confirm_follow": @"Confirm a follow",
        @"set_confirm_follow_note": @"Asks before following. Unfollowing is never asked about.",
        @"albrhi_save_button": @"Save button inside the video",
        @"albrhi_save_avatar": @"Offer to save profile photos",
        @"albrhi_save_avatar_note": @"Tap someone's profile photo to open it, and this asks whether to save it too. On by default -- it only ever asks, it never saves without you choosing to.",
        @"save_avatar_action": @"Save Photo",
        @"albrhi_confirm_repost": @"Confirm before reposting",
        @"albrhi_confirm_repost_note": @"Adds one more tap before Retweet goes out. Off by default -- X's own button already costs a tap, and a second one is worth adding only if you actually want it.",
        @"repost_confirm_action": @"Repost",
        @"like_confirm_action": @"Like",
        @"follow_confirm_action": @"Follow",
        @"profile_copy_title": @"Copy from this profile",
        @"profile_copy_all": @"Copy everything",
        @"lock_title": @"Locked",
        @"lock_reason": @"Unlock X",
        @"albrhi_save_button_note": @"Shown inside a video while it plays full-screen, and stays with it as you swipe to the next one. Turn it off and the list below still holds everything seen, so saving keeps working.",
        @"albrhi_hide_promoted": @"Hide Promoted Tweets (experimental)",
        @"albrhi_hide_promoted_note": @"“Hide ads” above does not touch these — a Promoted Tweet is an ordinary post the server marks, not a switch. This hides it where it is drawn instead, which can leave an empty gap in its place. Not yet confirmed on a device — try it and see.",
        @"albrhi_switch_layer": @"Feature switches",
        @"layer_row_note": @"Governs everything below it. Off, and the feature list is gone.",
        @"albrhi_switch_layer_note": @"Off makes this tweak do nothing at all — every feature below stops, and X behaves exactly as it would with nothing installed. For a build of X where hooking causes trouble.",
        @"albrhi_logging": @"Detailed log",
        @"albrhi_logging_note": @"Writes what the tweak is doing to the system log. Off unless something is being looked into.",

        @"section_status": @"Status",
        @"status_providers": @"Places hooked",
        @"status_providers_none": @"none found",
        @"status_keys": @"Switches seen",
        @"status_asked": @"Questions answered",
        @"status_gate": @"Albrhi in X",
        @"gate_on": @"On",
        @"gate_off": @"Off — turn it on in Settings › Albrhi",

        @"section_keys": @"Switches",
        @"licence_row": @"Licence",
        @"licence_row_note": @"Enter a key or a code, and see what this device is licensed for.",
        @"keys_link_title": @"View every switch",
        @"keys_footer": @"This is what X asked about while you were using it, not a list written in advance. Use the app for a while and more will appear. Tap one to answer it yourself.",
        @"keys_empty": @"Nothing yet. Scroll around X and come back.",
        @"search_placeholder": @"Search",

        @"pill_switches": @"Switches",
        @"pill_seen": @"Recording",
        @"pill_media": @"Media",
        @"filter_all": @"All",
        @"filter_changed": @"Changed",

        @"detail_app_on": @"X says on",
        @"detail_app_off": @"X says off",
        @"detail_you_on": @"You say on",
        @"detail_you_off": @"You say off",
        @"detail_asked": @"asked %lu×",

        @"choose_default": @"Let X decide",
        @"choose_on": @"On",
        @"choose_off": @"Off",

        @"menu_reset": @"Undo all my answers",
        @"menu_reset_body": @"Every switch goes back to whatever X decides. Nothing else changes.",
        @"menu_report": @"Save a report",
        @"report_saved": @"Saved to Files › On My iPhone › X › %@",
        @"report_failed": @"Could not save the report.",

        @"restart_note": @"Some changes only show after you close X and open it again.",
        @"credit": @"Albrhi — made by Ibrahim Ismail AL-Rahn. Open source under the GNU GPL v3. Where to hook this app was learned from the published work of BandarHL (BHTwitter) and TWIGalaxy; no code is taken from either.",
    };

    _arTable = @{
        @"title": @"البرهي لإكس",
        @"done": @"تم",
        @"cancel": @"إلغاء",
        @"ok": @"حسناً",

        @"section_media": @"حفظ الوسائط",
        @"media_footer": @"كل ما عرضه إكس عليك منذ فتحته، الأحدث أولاً. اضغط على أي عنصر ليُحفظ في الصور. والفيديو يُحفظ بأفضل جودة يوفّرها إكس.",
        @"media_video": @"فيديو",
        @"media_gif": @"صورة متحركة",
        @"media_image": @"صورة",
        @"save_working": @"جارٍ الحفظ…",
        @"save_done": @"حُفظ في الصور",
        @"save_failed": @"تعذّر حفظ هذا العنصر.",
        @"save_no_permission": @"يحتاج إكس إذناً بالإضافة إلى الصور. الإعدادات › X › الصور.",
        @"menu_forget_media": @"مسح قائمة الوسائط",

        @"section_features": @"الميزات",
        @"features_footer": @"كل ميزة هنا تضبط مجموعة من مفاتيح إكس نفسه دفعة واحدة. وكل مفتاح تلمسه هو مفتاح أبلغ عنه جهازك، فوجودها مؤكَّد — لكن معنى كل مفتاح مقروء من اسمه لا من كود إكس. إن بدا شيء غريباً، أطفئ الميزة ويعود إكس كما كان فوراً.",
        @"detail_feature_on": @"مُفعّل، من «%@»",
        @"detail_feature_off": @"مُطفأ، من «%@»",

        @"f_ads": @"إخفاء الإعلانات",
        @"f_ads_note": @"يُطفئ المنشورات المُروَّجة في المسار الزمني، وقبل الفيديو، وفي الملفات والبحث — ويُفعّل قواعد إكس نفسه التي تمنع إعلاناً في أول الصفحة.",
        @"f_promote": @"إخفاء زر الترويج",
        @"f_promote_note": @"يزيل «روّج هذا المنشور» والملصقات حوله من منشوراتك.",
        @"f_grok": @"إخفاء Grok",
        @"f_grok_note": @"يزيل زر Grok تحت المنشورات، ومن القوائم، ومن شريط التبويبات والقائمة الجانبية. ولا يمسّ Grok نفسه إن فتحته بنفسك.",
        @"f_autotranslate": @"إيقاف الترجمة التلقائية",
        @"f_autotranslate_note": @"إكس يترجم المنشورات والنبذات بلا أن تطلب، وهذا أكثر مفتاح انشغالاً في جهازك بفارق كبير. إيقافه يُبقي زر الترجمة في مكانه تماماً.",
        @"f_upsell": @"إخفاء دعايات الاشتراك",
        @"f_upsell_note": @"العروض والشارات والصفحات التي تدفعك للاشتراك. ولا يمسّ اشتراكاً لديك بالفعل.",
        @"f_tracking": @"أرسل عنّي أقل",
        @"f_tracking_note": @"يُطفئ تقارير الاستخدام التي يرسلها إكس عن تصفّحك ومساحتك واتصالك وأعطالك، وخدمتين خارجيتين يحملهما. ولا يمسّ طريقة تحقّق إكس من جهازك — تلك قد تُقفل الحساب، فلم تُعرض أصلاً.",
        @"f_clutter": @"تنظيف الواجهة",
        @"f_clutter_note": @"التلميحات والتنبيهات والتذكيرات وحركة الإعجاب والحلقات حول الصور الشخصية والزخارف الدعائية على المنشورات.",
        @"f_viewcounts": @"إخفاء عدّاد المشاهدات",
        @"f_viewcounts_note": @"يزيل عدد المشاهدات تحت المنشورات وشارة الترتيب بجانبه.",
        @"f_spaces": @"إخفاء المساحات",
        @"f_spaces_note": @"يخفي شريط المساحات وتبويبها وزرّ إنشاء واحدة. والمساحة التي تفتحها بنفسك تعمل كما هي.",
        @"f_sensitive": @"عرض المحتوى الحسّاس مباشرة",
        @"f_sensitive_note": @"يتخطّى غطاء «قد يحتوي محتوى حسّاساً». وهو يُخفي تحذيراً، لذلك يبقى مُطفأ حتى تُشغّله أنت.",
        @"f_safari": @"فتح الروابط في سفاري",
        @"f_safari_note": @"يوقف متصفّح إكس الداخلي، فتفتح الروابط في سفاري.",
        @"f_gif": @"لا تُشغّل الصور المتحركة وحدها",
        @"f_gif_note": @"يجعل الصور المتحركة تتبع إعداد التشغيل التلقائي مثل الفيديو، بدل تجاهله.",
        @"f_zoom": @"التكبير بلا فتح",
        @"f_zoom_note": @"قرّب الصورة بإصبعين داخل المسار الزمني لتكبيرها في مكانها.",
        @"f_gestures": @"إيماءات أكثر",
        @"f_gestures_note": @"سحب على المنشورات، وإيماءات شريط التبويبات المُحدَّثة، والضغط على الاسم لفتح الملف الشخصي.",
        @"f_tabs": @"تبويبات أكثر",
        @"f_tabs_note": @"يضع المجتمعات وملفك في الشريط السفلي، ويسمح بمسارات مثبَّتة إضافية.",
        @"f_privacy": @"أبقِ إعجاباتي خاصة",
        @"f_privacy_note": @"يُفعّل إخفاء إعجاباتك واشتراكاتك في ملفك، وإعدادات من يحق له ذكرك. والاختيار يبقى لك من إعدادات إكس نفسه.",
        @"f_launch": @"فتح أسرع",
        @"f_launch_note": @"يتخطّى حركة الفتح ويمنع إكس من تحميل تبويبات لم تفتحها بعد.",
        @"f_perf": @"تحسينات السرعة (تجريبي)",
        @"f_perf_note": @"يُفعّل تحسينات إكس نفسه التي يشحنها مُطفأة. قد يصير أسلس، وقد يصير أسوأ — وهذه الميزة الوحيدة هنا التي يحتمل فيها ذلك. وإيقافها سهل.",

        @"section_albrhi": @"البرهي",
        @"section_links": @"الروابط والخصوصية",
        @"section_links_note": @"لا شيء هنا يخبر إكس بشيء غير صحيح. تغيّر ما يحمله الرابط ومن يفتح التطبيق.",
        @"section_timeline": @"بين المنشورات",
        @"section_timeline_note": @"كل مفتاح هنا يزيل شيئاً يعمل، ولهذا تبدأ كلها موقوفة.",
        @"section_posts": @"على المنشور",
        @"section_posts_note": @"إكس يرتّب هذا الصف يدوياً، فقد يترك الزر المخفي مكانه فارغاً. التقرير يقول كم أُخفي.",
        @"section_extras": @"إضافات",
        @"section_advanced": @"متقدّم",
        @"page_albrhi_note": @"الحفظ، والتأكيد قبل إعادة النشر والإعجاب والمتابعة.",
        @"page_extras_note": @"التراجع والترجمة وجودة الرفع واتجاه النص.",
        @"page_advanced_note": @"قائمة المفاتيح الخام والسجل وما تم تركيبه.",
        @"set_strip_tracking": @"تنظيف الروابط المنسوخة",
        @"set_strip_tracking_note": @"يحذف المعاملين اللذين يدلّان على الحساب الذي شارك الرابط.",
        @"set_expand_links": @"إظهار الرابط الحقيقي",
        @"set_expand_links_note": @"وجهة الرابط بدل غلاف t.co.",
        @"set_no_search_history": @"بلا سجل بحث",
        @"set_no_search_history_note": @"يُفرغ صف الأخير — بحثاً وحسابات — ويمنع تسجيل الجديد. ما هو مخزَّن أصلاً يُترك كما هو، وإكس يحتفظ بنسخته على خوادمه.",
        @"set_app_lock": @"قفل التطبيق",
        @"set_app_lock_note": @"بصمة الوجه أو رمزك قبل أن يعرض إكس شيئاً. الجهاز الذي لا يملك أياً منهما يُمرَّر.",
        @"set_hide_who_to_follow": @"إخفاء «من تتابع»",
        @"set_hide_who_to_follow_note": @"اقتراحات الحسابات في الخط الزمني وفي الملفات.",
        @"set_hide_topics": @"إخفاء المواضيع",
        @"set_hide_topics_note": @"لافتات المواضيع ودعوات متابعتها.",
        @"set_hide_trend_videos": @"إخفاء مقاطع الترند",
        @"set_hide_trend_videos_note": @"وحدات الفيديو المرفقة بالأحداث الرائجة.",
        @"set_hide_bookmark": @"إخفاء زر الحفظ",
        @"set_tweet_to_image": @"المنشور كصورة",
        @"set_tweet_to_image_note": @"ضغطة مطوّلة على المشاركة ترسم المنشور وتعرضه للمشاركة كصورة.",
        @"set_full_frame": @"إظهار الصور كاملة",
        @"set_full_frame_note": @"الصورة المفردة تُرسم كاملة بدل اقتصاصها. الفيديو والشبكات لا تُمسّ.",
        @"set_undo_post": @"عرض التراجع عن النشر",
        @"set_undo_post_note": @"يفرض التنبيه الذي يعرضه إكس أحياناً بعد النشر.",
        @"set_copy_profile": @"النسخ من الملف الشخصي",
        @"set_copy_profile_note": @"ضغطة مطوّلة على رأس الملف تعرض الاسم والمعرّف والنبذة كنص.",
        @"set_bio_translate": @"عرض ترجمة النبذة دائماً",
        @"set_high_quality_upload": @"رفع بأعلى جودة",
        @"set_high_quality_upload_note": @"يُظهر إعداد إكس نفسه لرفع الصور بدقتها الكاملة.",
        @"set_disable_rtl": @"فرض الاتجاه من اليسار",
        @"set_disable_rtl_note": @"يغيّر اتجاه كل نص يرسمه إكس، لا النص الذي قصدته وحده.",
        @"set_confirm_like": @"تأكيد الإعجاب",
        @"set_confirm_like_note": @"يسأل قبل الإعجاب. وسحب الإعجاب لا يُسأل عنه.",
        @"set_confirm_follow": @"تأكيد المتابعة",
        @"set_confirm_follow_note": @"يسأل قبل متابعة حساب. وإلغاء المتابعة لا يُسأل عنه.",
        @"albrhi_save_button": @"زر الحفظ داخل الفيديو",
        @"albrhi_save_avatar": @"عرض حفظ الصور الشخصية",
        @"albrhi_save_avatar_note": @"اضغط على صورة أحد شخصياً لفتحها، وهذا يسألك هل تريد حفظها أيضاً. مُفعّل افتراضياً — يسأل فقط، ولا يحفظ إلا باختيارك.",
        @"save_avatar_action": @"حفظ الصورة",
        @"albrhi_confirm_repost": @"تأكيد قبل إعادة النشر",
        @"albrhi_confirm_repost_note": @"يضيف ضغطة واحدة قبل خروج إعادة النشر. مُطفأ افتراضياً — زرّ X نفسه يكلّف ضغطة أصلاً، وإضافة ثانية تستحق فقط إن كنت تريدها فعلاً.",
        @"repost_confirm_action": @"إعادة النشر",
        @"like_confirm_action": @"إعجاب",
        @"follow_confirm_action": @"متابعة",
        @"profile_copy_title": @"انسخ من هذا الملف",
        @"profile_copy_all": @"انسخ كل شيء",
        @"lock_title": @"مقفل",
        @"lock_reason": @"افتح إكس",
        @"albrhi_save_button_note": @"يظهر داخل الفيديو أثناء تشغيله بملء الشاشة، ويبقى معه أثناء التمرير للتالي. أطفئه وتبقى القائمة أدناه تحمل كل ما رأته الأداة، فالحفظ يظل يعمل.",
        @"albrhi_hide_promoted": @"إخفاء التغريدات المُروَّجة (تجريبي)",
        @"albrhi_hide_promoted_note": @"«إخفاء الإعلانات» أعلاه لا يمسّ هذه — التغريدة المُروَّجة منشور عادي يضع الخادم عليه علامة، لا مفتاحاً. هذا يُخفيها في مكان رسمها بدلاً من ذلك، وقد يترك فراغاً مكانها. لم يُؤكَّد بعد على جهاز حقيقي — جرّبها وانظر.",
        @"albrhi_switch_layer": @"مفاتيح المزايا",
        @"layer_row_note": @"يحكم كل ما يليه: أوقفه فتختفي قائمة المزايا كاملة.",
        @"albrhi_switch_layer_note": @"إطفاؤه يجعل الأداة لا تفعل شيئاً على الإطلاق — تتوقف كل المزايا أدناه، ويتصرف إكس كما لو لم يكن شيء مثبَّتاً. لبناءٍ من إكس يسبّب فيه الخطف مشكلة.",
        @"albrhi_logging": @"سجل مفصّل",
        @"albrhi_logging_note": @"يكتب ما تفعله الأداة في سجل النظام. مُطفأ إلا عند تتبّع مشكلة.",

        @"section_status": @"الحالة",
        @"status_providers": @"المواضع المربوطة",
        @"status_providers_none": @"لم يُعثر على شيء",
        @"status_keys": @"المفاتيح التي ظهرت",
        @"status_asked": @"الأسئلة المُجاب عنها",
        @"status_gate": @"البرهي داخل إكس",
        @"gate_on": @"مُفعّل",
        @"gate_off": @"مُطفأ — فعّله من الإعدادات › البرهي",

        @"section_keys": @"المفاتيح",
        @"licence_row": @"الترخيص",
        @"licence_row_note": @"أدخل مفتاحاً أو كوداً، واعرف ما يغطّيه ترخيص هذا الجهاز.",
        @"keys_link_title": @"عرض كل مفتاح",
        @"keys_footer": @"هذا ما سأل عنه إكس أثناء استخدامك، لا قائمة مكتوبة مسبقاً. استخدم التطبيق قليلاً وستظهر مفاتيح أكثر. اضغط على أي مفتاح لتجيب أنت عنه.",
        @"keys_empty": @"لا شيء بعد. تصفّح إكس قليلاً ثم ارجع.",
        @"search_placeholder": @"بحث",

        @"pill_switches": @"المفاتيح",
        @"pill_seen": @"التسجيل",
        @"pill_media": @"الوسائط",
        @"filter_all": @"الكل",
        @"filter_changed": @"المُعدَّلة",

        @"detail_app_on": @"إكس يقول: مُفعّل",
        @"detail_app_off": @"إكس يقول: مُطفأ",
        @"detail_you_on": @"أنت تقول: مُفعّل",
        @"detail_you_off": @"أنت تقول: مُطفأ",
        @"detail_asked": @"سُئل %lu مرة",

        @"choose_default": @"اترك القرار لإكس",
        @"choose_on": @"مُفعّل",
        @"choose_off": @"مُطفأ",

        @"menu_reset": @"تراجع عن كل إجاباتي",
        @"menu_reset_body": @"يعود كل مفتاح إلى ما يقرره إكس. لا يتغير شيء آخر.",
        @"menu_report": @"حفظ تقرير",
        @"report_saved": @"حُفظ في الملفات › على الآيفون › إكس › %@",
        @"report_failed": @"تعذّر حفظ التقرير.",

        @"restart_note": @"بعض التغييرات لا تظهر إلا بعد إغلاق إكس وفتحه من جديد.",
        @"credit": @"البرهي — تطوير إبراهيم إسماعيل الرهن. مفتوح المصدر تحت رخصة GNU GPL v3. موضع الربط في هذا التطبيق عُرف من عمل BandarHL‏ (BHTwitter) وTWIGalaxy المنشور، ولم يُنسخ منهما أي كود.",
    };
}

NSString *SCILocalized(NSString *key) {
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        SCIBuildTables();
    });

    // The device's own preference. Someone whose phone is Arabic is an Arabic reader, and
    // these strings are this tweak's own rather than X's.
    NSString *language = [[NSLocale preferredLanguages] firstObject] ?: @"en";
    BOOL arabic = [language hasPrefix:@"ar"];

    NSDictionary *table = arabic ? _arTable : _enTable;
    NSString *value = table[key];

    return value ?: (_enTable[key] ?: key);
}
