#import "SCILocalize.h"

@implementation SCILocalize

static NSDictionary *_enTable = nil;
static NSDictionary *_arTable = nil;

+ (void)load {
    [self buildTables];
}

+ (NSString *)languageOverride {
    NSString *v = [[NSUserDefaults standardUserDefaults] stringForKey:@"albrhi_language"];
    if (![v length]) return @"system";
    return v;
}

+ (void)setLanguageOverride:(NSString *)code {
    if ([code isEqualToString:@"system"]) {
        [[NSUserDefaults standardUserDefaults] removeObjectForKey:@"albrhi_language"];
    } else {
        [[NSUserDefaults standardUserDefaults] setObject:code forKey:@"albrhi_language"];
    }
}

+ (NSString *)activeLanguage {
    NSString *override = [self languageOverride];
    if ([override isEqualToString:@"ar"]) return @"ar";
    if ([override isEqualToString:@"en"]) return @"en";

    // System resolution
    NSString *pref = [[NSLocale preferredLanguages] firstObject] ?: @"en";
    if ([pref hasPrefix:@"ar"]) return @"ar";
    return @"en";
}

+ (BOOL)isRTL {
    return [[self activeLanguage] isEqualToString:@"ar"];
}

+ (NSString *)stringForKey:(NSString *)key {
    if (![key length]) return @"";
    NSDictionary *table = [[self activeLanguage] isEqualToString:@"ar"] ? _arTable : _enTable;
    NSString *value = table[key];
    if (value) return value;
    // Fallback to English, then to the raw key
    return _enTable[key] ?: key;
}

+ (void)buildTables {
    _enTable = @{
        @"wn_beta_badge": @"BETA",
        @"wn_w5_title": @"If something breaks",
        @"wn_w5_detail": @"Settings → Diagnostics → the speech bubble. It writes the bug report for you, with everything needed to fix it.",
        @"wn_beta_note": @"Beta · tested on Instagram 410.1.0, the newest build our ageing test phone will accept. Newer should work. Tell us if it doesn't.",

        // General section
        @"hide_ads_title": @"Hide ads",

        // Focus

        // Feed

        // Reels

        // Media / Downloads
        @"section_downloads": @"Downloads",
        @"save_profile_title": @"Save profile pictures",
        @"save_profile_sub": @"Long-press a profile picture to view/save it in HD",
        @"dw_save_to_camera_title": @"Save directly to Photos",
        @"dw_save_to_camera_sub": @"Save straight to your library instead of the share sheet",
        @"dw_reel_audio_title": @"Enable reel audio download",
        @"dw_reel_audio_sub": @"When downloading a reel, choose between the video or its audio",
        @"dw_choice_video": @"Download video",
        @"dw_choice_audio": @"Download audio only",
        @"copy_account_info_title": @"Copy account info",
        @"copy_account_info_sub": @"Long-press a profile picture to copy the account's username and name",
        @"custom_album_title": @"Save to \"Albrhi\" album",
        @"custom_album_sub": @"Organize saved media into a dedicated album in Photos",
        @"accent_color_title": @"Accent color",
        @"accent_color_sub": @"Customize Albrhi's highlight color",
        @"accent_reset_title": @"Reset accent color",
        @"info_download_pfp": @"Download profile picture",
        @"info_copy": @"Copy account info",
        @"info_copied": @"Account info copied",
        @"info_unavailable": @"Account info unavailable",
        @"info_verified": @"✓ Verified",
        @"quality_unknown": @"Unknown quality",
        @"dw_silent_video_title": @"Download videos without audio",
        @"dw_silent_video_sub": @"Strips the audio track from downloaded videos",

        // Privacy

        // Language
        @"section_language": @"Language",
        @"language_title": @"Language",
        @"language_sub": @"Choose Albrhi's interface language",
        @"language_system": @"System default",
        @"language_arabic": @"العربية (Arabic)",
        @"language_english": @"English",

        // Settings meta
        @"settings_title": @"Albrhi Settings",
        @"settings_header": @"Albrhi",
        @"quick_access_title": @"Settings quick-access",
        @"quick_access_sub": @"Hold the home tab to open Albrhi settings",
        @"open_on_launch_title": @"Open settings on launch",
        @"reset_first_run_title": @"Reset first-run flag",
        @"credits_title": @"Credits",
        @"credits_sub": @"Albrhi is based on SCInsta by SoCuul (GPLv3)",
        @"view_repo_title": @"View source",
        @"view_repo_sub": @"Albrhi is open-source under the GPLv3 license",
        @"developer_title": @"Developer",
        @"section_connect": @"Connect with the developer",
        @"social_instagram_title": @"Instagram",
        @"social_snapchat_title": @"Snapchat",
        @"social_telegram_title": @"Telegram",
        @"social_open_sub": @"Opens the profile directly",

        // Runtime messages
        @"download_saved": @"Saved to Photos",
        @"download_failed": @"Download failed",
        @"err_no_photo": @"Could not extract photo URL",
        @"err_no_video": @"Could not extract video URL",
        @"err_no_media": @"Could not find media to download",

        // Diagnostics
        @"diag_title": @"Diagnostics",
        @"diag_sub": @"What Albrhi actually sees at runtime",
        @"diag_beta_footer": @"Something not working? Open Diagnostics and tap the speech bubble — it files a report with everything needed to fix it.",
        @"diag_issue_what": @"**What happened**\n<describe what you expected and what you got>",
        @"diag_issue_steps": @"**Steps to reproduce**\n1. \n2. ",
        @"p_hdr_logging": @"Logging",
        @"p_verbose_t": @"Verbose logging",
        @"p_verbose_s": @"Writes detailed activity to the system log. Off by default — turn it on only while reproducing a bug.",
        @"diag_section_classes": @"Action row classes in this build",
        @"diag_section_attached": @"Download button attachments",
        @"diag_section_quality": @"Last video download",
        @"diag_section_stories": @"Stories",
        @"diag_section_env": @"Environment",
        @"diag_class_present": @"Exists in this Instagram build",
        @"diag_class_absent": @"Not present",
        @"diag_attached": @"Button attached here",
        @"diag_button_media": @"Media resolved on last press",
        @"diag_button_unpressed": @"Button not pressed yet",
        @"diag_button_nomedia": @"Nothing found — this is the download failure",
        @"diag_none_attached": @"No action row seen yet",
        @"diag_none_attached_hint": @"Scroll your feed once, then reopen this page",
        @"diag_quality_never": @"No video downloaded yet this session",
        @"diag_quality_single": @"Only %ld rendition found — no choice to offer",
        @"diag_quality_multi": @"%ld renditions found",
        @"diag_quality_last": @"Renditions",
        @"diag_quality_source": @"Video class",
        @"diag_download_kind": @"Last download treated as",
        @"diag_section_dash": @"DASH manifest",
        @"diag_dash_none": @"No manifest seen yet",
        @"diag_dash_hint": @"Download a video, then reopen this page",
        @"diag_dash_found": @"Manifest size",
        @"diag_dash_reps": @"Representations",
        @"diag_dash_excerpt": @"Raw excerpt",
        @"diag_dash_saveable": @"Saveable video reps (H.264/HEVC)",
        @"diag_dash_needs_transcode": @"  — needs transcode",
        @"diag_section_transcode": @"AV1 transcode",
        @"diag_transcode_none": @"No transcode attempted yet",
        @"diag_transcode_hint": @"Turn on AV1 transcoding, then download an AV1 video",
        @"dw_transcode_av1_title": @"Transcode AV1 to 1080p",
        @"dw_transcode_av1_sub": @"Re-encode the AV1 ladder to H.264 on device. Slower and heavier; off by default",
        @"transcode_progress": @"Processing %dp…",
        @"transcode_fell_back": @"Transcode failed — saved standard quality",
        @"transcode_saved": @"Saved",
        @"transcode_muxing": @"finishing…",
        @"transcode_frames": @"%ld frames",
        @"transcode_saving": @"saving…",
        @"page_appearance": @"Appearance",
        @"p_hdr_dates": @"Dates",
        @"p_hdr_theme": @"Theme",
        @"date_enable_t": @"Custom date format",
        @"date_preset_t": @"Style",
        @"date_preset_s": @"How an absolute date is written",
        @"date_preset_absolute": @"Jan 5, 2026",
        @"date_preset_compact": @"05/01/26",
        @"date_preset_datetime": @"05/01/2026 14:30",
        @"date_preset_time": @"14:30:05 (time only)",
        @"date_preset_custom": @"Custom pattern",
        @"date_24h_t": @"24-hour clock",
        @"date_24h_s": @"Off shows 2:30 PM instead of 14:30",
        @"date_compact_t": @"Compact relative times",
        @"date_compact_s": @"“2h” instead of “2 hours ago”",
        @"date_threshold_t": @"Keep relative under",
        @"date_combine_t": @"Show both",
        @"date_combine_s": @"Absolute and relative together",
        @"date_combine_off": @"Off",
        @"date_combine_absolute_first": @"Jan 5, 2026 (2h)",
        @"date_combine_relative_first": @"2h – Jan 5, 2026",
        @"date_pattern_t": @"Custom pattern",
        @"date_pattern_help": @"Placeholders: {DD} {MM} {MMM} {YYYY} {YY} {HH} {hh} {mm} {ss} {A} {EEE}",
        @"date_pattern_save": @"Save",
        @"date_preview_off": @"Off — Instagram's own wording",
        @"date_ago_format": @"%ld %@ ago",
        @"date_unit_second": @"second",
        @"date_unit_seconds": @"seconds",
        @"date_unit_minute": @"minute",
        @"date_unit_minutes": @"minutes",
        @"date_unit_hour": @"hour",
        @"date_unit_hours": @"hours",
        @"date_unit_day": @"day",
        @"date_unit_days": @"days",
        @"date_unit_week": @"week",
        @"date_unit_weeks": @"weeks",
        @"date_unit_month": @"month",
        @"date_unit_months": @"months",
        @"date_unit_year": @"year",
        @"date_unit_years": @"years",
        @"p_dm_keepdel_t": @"Keep deleted messages",
        @"p_dm_keepdel_s": @"Preserves messages others unsend. Pull-to-refresh in the inbox clears them",
        @"p_dm_lastactive_t": @"Full last-active time",
        @"p_dm_lastactive_s": @"A real date instead of “Active 2h ago”, in your chosen format",
        @"p_dm_voicecall_t": @"Hide voice call button",
        @"p_dm_voicecall_s": @"Removes it from the chat header",
        @"p_dm_videocall_t": @"Hide video call button",
        @"p_dm_videocall_s": @"Removes it from the chat header",
        @"oled_t": @"OLED black theme",
        @"oled_s": @"Replaces Instagram's dark grey with pure black",
        @"diag_section_timestamps": @"Timestamp labels on screen",
        @"diag_ts_prompt": @"Not scanned yet",
        @"diag_ts_empty": @"No timestamp labels found",
        @"diag_ts_hint": @"Open the feed behind this page, then scan again",
        @"diag_ts_sample_header": @"No match — here is what the labels say:",
        @"diag_section_dateformat": @"Date formatters in use",
        @"diag_df_none": @"No date formatter seen yet",
        @"diag_df_hint": @"Scroll the feed, open a story and a chat, then reopen this page",
        @"diag_section_daterewrite": @"Timestamps rewritten",
        @"diag_dr_none": @"None rewritten yet",
        @"diag_dr_hint": @"Turn on custom dates, scroll the feed, then reopen this page",
        @"diag_dr_count": @"Rewrites",
        @"diag_dr_hooks": @"NSDate selectors hooked",
        @"err_save_failed": @"Could not save to Photos",
        @"diag_dash_empty": @"Probe ran, found no manifest",
        @"diag_dash_empty_hint": @"Neither the video nor the media object carried one",
        @"diag_dash_candidates": @"Selectors mentioning dash/manifest",
        @"diag_dash_no_candidates": @"None — field not exposed on these classes",
        @"diag_on": @"On",
        @"diag_off": @"Off",
        @"diag_story_intercepts": @"Seen receipts blocked",
        @"diag_seen_replay": @"DM mark-as-seen replay",
        @"diag_copied": @"Report copied",
        @"diag_section_scan": @"Live screen scan",
        @"diag_scan_prompt": @"Not scanned yet",
        @"diag_scan_hint": @"Open a feed post behind this sheet, then tap the magnifier above",
        @"diag_scan_empty": @"Nothing button-row shaped on screen",

        // Story seen button
        @"story_seen_button_title": @"Mark-as-seen button",
        @"story_seen_button_sub": @"Adds an eye toggle in the story viewer to register a story as seen",

        // Welcome / What's New
        @"wn_welcome_title": @"Welcome to Albrhi",
        @"wn_welcome_sub": @"Instagram, minus the parts nobody asked for.",
        @"wn_update_title": @"Albrhi %@",
        @"wn_update_sub": @"Here's what changed while you were scrolling.",
        @"wn_continue": @"Let's go",

        @"wn_w1_title": @"Download anything",
        @"wn_w1_detail": @"A download button sits right in the action row of posts and reels. One tap, highest quality, straight to Photos.",
        @"wn_w2_title": @"Watch without a trace",
        @"wn_w2_detail": @"Stories and view-once messages leave no seen receipt — until you decide otherwise with the eye button.",
        @"wn_w3_title": @"A quieter feed",
        @"wn_w3_detail": @"Ads, suggested posts, suggested accounts and Meta AI, all politely shown the door.",
        @"wn_w4_title": @"Where the settings live",
        @"wn_w4_detail": @"Hold the ☰ button on your profile. That is the entire trick — no hidden gestures to memorise.",

        @"wn_u1_title": @"1080p downloads",
        @"wn_u1_detail": @"Instagram’s best quality, converted right on your phone.",
        @"wn_u2_title": @"Dates your way",
        @"wn_u2_detail": @"A real time instead of “2h”. Presets, your own format, 12 or 24 hour.",
        @"wn_u3_title": @"True black",
        @"wn_u3_detail": @"An OLED theme — easier on the eyes and the battery.",
        @"wn_u4_title": @"Download centre",
        @"wn_u4_detail": @"Queue, pause, resume and keep a history of everything you save.",

        @"wn_show_again": @"Show the welcome screen again",
        @"wn_footnote_welcome": @"Free, open source, and not affiliated with Instagram — they have no idea we are here.",
        @"wn_footnote_update": @"No new ads were added in the making of this update.",

        // Download Center
        @"dl_center_title": @"Download Center",
        @"dl_center_sub": @"Queue, progress and history for every download",
        @"dl_section_active": @"Active",
        @"dl_section_history": @"History",
        @"dl_total_footer": @"%@ downloaded in total",
        @"dl_search_placeholder": @"Search downloads",
        @"dl_scope_all": @"All",
        @"dl_kind_photo": @"Photo",
        @"dl_kind_video": @"Video",
        @"dl_kind_audio": @"Audio",
        @"dl_kind_file": @"File",
        @"dl_state_queued": @"Waiting…",
        @"dl_state_paused": @"Paused",
        @"dl_state_failed": @"Failed",
        @"dl_state_cancelled": @"Cancelled",
        @"dl_size_of": @"%@ of %@",
        @"dl_pause": @"Pause",
        @"dl_resume": @"Resume",
        @"dl_retry": @"Retry",
        @"dl_cancel": @"Cancel",
        @"dl_pause_all": @"Pause all",
        @"dl_resume_all": @"Resume all",
        @"dl_clear_history": @"Clear history",
        @"dl_clear_history_message": @"Removes every finished download from the list. The saved files are not deleted.",
        @"dl_share": @"Share",
        @"dl_copy_link": @"Copy link",
        @"dl_remove": @"Remove",
        @"dl_sort_title": @"Sort by",
        @"dl_sort_newest": @"Newest first",
        @"dl_sort_oldest": @"Oldest first",
        @"dl_sort_name": @"Name",
        @"dl_sort_size": @"Size",
        @"dl_empty_title": @"No downloads yet",
        @"dl_empty_sub": @"Media you save will appear here, with progress and history.",
        @"dl_use_queue_title": @"Use the download queue",
        @"dl_use_queue_sub": @"Downloads run in the background and continue if you leave the app",
        @"dl_max_concurrent_title": @"Simultaneous downloads",
        @"dl_clear_title": @"Clear after saving",
        @"dl_clear_sub": @"Removes the download from this list once it is in Photos, so nothing is stored twice",
        @"dl_added_to_queue": @"Added to queue",
        @"dl_already_downloaded": @"Already downloaded",

        // Feature page titles
        @"page_general": @"General",
        @"page_feed": @"Feed",
        @"page_reels": @"Reels",
        @"page_stories_messages": @"Stories and messages",
        @"page_navigation": @"Navigation",
        @"page_confirmations": @"Confirm actions",

        @"inline_download_title": @"Inline download button",
        @"inline_download_sub": @"Adds a download icon to the post action row, next to save",
        @"loading": @"Loading",
        @"cancel": @"Cancel",

        // ---- Settings pages (fully localized) ----
        // General
        @"p_general_ads_t": @"Hide ads", @"p_general_ads_s": @"Removes all ads from the Instagram app",
        @"p_general_metaai_t": @"Hide Meta AI", @"p_general_metaai_s": @"Hides the Meta AI buttons and functionality in the app",
        @"p_general_copydesc_t": @"Copy description", @"p_general_copydesc_s": @"Copy caption text by long-pressing on it",
        @"p_general_norecent_t": @"Don't save recent searches", @"p_general_norecent_s": @"Search bars will no longer store your recent searches",
        @"p_general_colorpicker_t": @"Detailed color picker", @"p_general_colorpicker_s": @"Long-press the eyedropper in stories for precise text colors",
        @"p_hdr_notes": @"Notes",
        @"p_general_hidenotes_t": @"Hide notes tray", @"p_general_hidenotes_s": @"Hides the notes tray in the DM inbox",
        @"p_general_friendsmap_t": @"Hide friends map", @"p_general_friendsmap_s": @"Hides the friends map icon in the notes tray",
        @"p_general_notetheming_t": @"Note theming", @"p_general_notetheming_s": @"Enables the notes theme picker",
        @"p_general_customnote_t": @"Custom note themes", @"p_general_customnote_s": @"Set custom emojis and background/text colors",
        @"p_hdr_focus": @"Focus & distractions",
        @"p_general_nosuggusers_t": @"No suggested users", @"p_general_nosuggusers_s": @"Hides suggested users to follow outside your feed",
        @"p_general_nosuggchats_t": @"No suggested chats", @"p_general_nosuggchats_s": @"Hides suggested broadcast channels in direct messages",
        @"p_general_exploregrid_t": @"Hide explore grid", @"p_general_exploregrid_s": @"Hides the grid of suggested posts on the explore tab",
        @"p_general_trending_t": @"Hide trending searches", @"p_general_trending_s": @"Hides trending searches under the explore search bar",
        // Feed
        @"p_feed_storytray_t": @"Hide stories tray", @"p_feed_storytray_s": @"Hides the story tray at the top and within your feed",
        @"p_feed_entirefeed_t": @"Hide entire feed", @"p_feed_entirefeed_s": @"Removes all content from your home feed, including posts",
        @"p_feed_nosuggposts_t": @"No suggested posts", @"p_feed_nosuggposts_s": @"Removes suggested posts from your feed",
        @"p_feed_nosuggacct_t": @"No suggested accounts", @"p_feed_nosuggacct_s": @"Hides suggested accounts for you to follow",
        @"p_feed_nosuggreels_t": @"No suggested reels", @"p_feed_nosuggreels_s": @"Hides suggested reels to watch",
        @"p_feed_nosuggthreads_t": @"No suggested Threads posts", @"p_feed_nosuggthreads_s": @"Hides suggested Threads posts in your feed",
        @"p_feed_autoplay_t": @"Disable video autoplay", @"p_feed_autoplay_s": @"Prevents feed videos from playing automatically",
        // Reels
        @"p_reels_tap_t": @"Tap controls", @"p_reels_tap_s": @"Change what happens when you tap on a reel",
        @"p_reels_scrubber_t": @"Always show progress scrubber", @"p_reels_scrubber_s": @"Forces the progress bar to appear on every reel",
        @"p_reels_unmute_t": @"Disable auto-unmuting reels", @"p_reels_unmute_s": @"Prevents reels from unmuting when the volume button is pressed",
        @"p_reels_refresh_t": @"Confirm reel refresh", @"p_reels_refresh_s": @"Shows an alert when you trigger a reels refresh",
        @"p_hdr_hiding": @"Hiding",
        @"p_reels_header_t": @"Hide reels header", @"p_reels_header_s": @"Hides the top navigation bar while watching reels",
        @"p_reels_blend_t": @"Hide reels blend button", @"p_reels_blend_s": @"Hides the button in DMs that opens a reels blend",
        @"p_hdr_limits": @"Limits",
        // Stories & messages
        @"p_hdr_messages": @"Messages",
        @"p_sm_markseen_t": @"Manual mark-as-seen", @"p_sm_markseen_s": @"Adds a button to DM threads to mark messages as seen",
        @"p_sm_typing_t": @"Disable typing status", @"p_sm_typing_s": @"Stops the typing indicator from showing to others in DMs",
        @"p_hdr_visual": @"Visual messages & stories",
        @"p_sm_replay_t": @"Unlimited replay of visual messages", @"p_sm_replay_s": @"Replay view-once/normal visual messages unlimited times (toggle with the image-check icon in the chat)",
        @"p_sm_viewonce_t": @"Disable view-once limitations", @"p_sm_viewonce_s": @"Makes view-once messages behave like normal ones (loopable/pausable)",
        @"p_sm_screenshot_t": @"Disable screenshot detection", @"p_sm_screenshot_s": @"Removes screenshot alerts for visual messages in DMs",
        @"p_sm_seen_t": @"Disable story seen receipt", @"p_sm_seen_s": @"Others won't be notified when you view their story",
        @"p_sm_instants_t": @"Disable instants creation", @"p_sm_instants_s": @"Hides the ability to create/send instants",
        // Navigation
        @"p_nav_order_t": @"Icon order", @"p_nav_order_s": @"The order of the icons on the bottom navigation bar",
        @"p_nav_swipe_t": @"Swipe between tabs", @"p_nav_swipe_s": @"Swipe to switch between navigation bar tabs",
        @"p_hdr_hidetabs": @"Hiding tabs",
        @"p_nav_feedtab_t": @"Hide feed tab", @"p_nav_feedtab_s": @"Hides the home tab on the navigation bar",
        @"p_nav_exploretab_t": @"Hide explore tab", @"p_nav_exploretab_s": @"Hides the explore/search tab on the navigation bar",
        @"p_nav_reelstab_t": @"Hide reels tab", @"p_nav_reelstab_s": @"Hides the reels tab on the navigation bar",
        @"p_nav_createtab_t": @"Hide create tab", @"p_nav_createtab_s": @"Hides the create tab on the navigation bar",
        // Confirmations
        @"p_cf_like_t": @"Confirm like: posts & stories", @"p_cf_like_s": @"Asks before liking a post or story",
        @"p_cf_likereels_t": @"Confirm like: reels", @"p_cf_likereels_s": @"Asks before liking a reel",
        @"p_cf_follow_t": @"Confirm follow", @"p_cf_follow_s": @"Asks before following an account",
        @"p_cf_repost_t": @"Confirm repost", @"p_cf_repost_s": @"Asks before reposting",
        @"p_cf_call_t": @"Confirm call", @"p_cf_call_s": @"Asks before starting an audio/video call",
        @"p_cf_voice_t": @"Confirm voice messages", @"p_cf_voice_s": @"Asks before sending a voice message",
        @"p_cf_followreq_t": @"Confirm follow requests", @"p_cf_followreq_s": @"Asks before accepting/declining a follow request",
        @"p_cf_shh_t": @"Confirm Shh mode", @"p_cf_shh_s": @"Asks before toggling disappearing messages",
        @"p_cf_comment_t": @"Confirm posting comment", @"p_cf_comment_s": @"Asks before posting a comment",
        @"p_cf_theme_t": @"Confirm theme change", @"p_cf_theme_s": @"Asks before changing a chat theme",
        @"p_cf_sticker_t": @"Confirm sticker interaction", @"p_cf_sticker_s": @"Asks before tapping a sticker on someone's story",
        // Debug / root
        @"p_hdr_debug": @"Debug",
        @"p_dbg_flexgesture_t": @"Enable FLEX gesture", @"p_dbg_flexgesture_s": @"Hold 5 fingers on the screen to open the FLEX explorer",
        @"p_dbg_flexlaunch_t": @"Open FLEX on launch", @"p_dbg_flexlaunch_s": @"Automatically opens FLEX when the app launches",
        @"p_dbg_flexfocus_t": @"Open FLEX on focus", @"p_dbg_flexfocus_s": @"Automatically opens FLEX when the app is focused",
        @"p_dbg_safemode_t": @"Disable safe mode", @"p_dbg_safemode_s": @"Stops Instagram from resetting settings after repeated crashes (at your own risk)",
        // Stepper labels
        @"p_lbl_downloads": @"downloads", @"p_lbl_download": @"download",
        // Menus
        @"p_menu_default": @"Default", @"p_menu_pauseplay": @"Pause / Play", @"p_menu_muteunmute": @"Mute / Unmute",
        @"p_menu_classic": @"Classic", @"p_menu_standard": @"Standard", @"p_menu_alternate": @"Alternate",
        @"p_menu_enabled": @"Enabled", @"p_menu_disabled": @"Disabled",
        // DM seen/replay toasts
        @"p_toast_marked_seen": @"Marked messages as seen",
        // Follow status
        @"p_follows_you": @"✓ Follows you",
        @"p_not_follows_you": @"✗ Doesn't follow you",
        @"p_followstatus_t": @"Show follow-back status",
        @"p_followstatus_s": @"Long-press a profile picture to see whether that account follows you",
        // Story download button
        @"p_story_dl_title": @"Story download button",
        @"p_story_dl_sub": @"Shows a download button in the story viewer to save the current story",
        // DM media save button
        @"p_dm_save_t": @"Save DM photos & videos",
        @"p_dm_save_s": @"Adds a save button when you open a photo or video in DMs, and always allows saving",
        // View-once seen toasts
        @"p_dm_seen_already": @"Already marked as seen",
        // Long-press action
        @"p_press_zoom": @"Zoom (peek)",
        @"p_press_off": @"Off",
        // Auto-advance reels
    };

    _arTable = @{
        @"wn_beta_badge": @"نسخة تجريبية",
        @"wn_w5_title": @"لو تعطّل شيء",
        @"wn_w5_detail": @"الإعدادات ← التشخيص ← أيقونة الفقاعة. تكتب لك البلاغ كاملًا بكل ما يلزم لإصلاحه.",
        @"wn_beta_note": @"نسخة تجريبية · جُرّبت على انستقرام 410.1.0، وهو أحدث إصدار يقبله هاتف التجارب المتقاعد لدينا. الأحدث يُفترض أن يعمل. أخبرنا إن لم يفعل.",

        // عام
        @"hide_ads_title": @"إخفاء الإعلانات",

        // التركيز

        // الصفحة الرئيسية

        // الريلز

        // التنزيلات
        @"section_downloads": @"التنزيلات",
        @"save_profile_title": @"حفظ صور الملف الشخصي",
        @"save_profile_sub": @"اضغط مطوّلًا على صورة الملف الشخصي لعرضها/حفظها بجودة عالية",
        @"dw_save_to_camera_title": @"الحفظ مباشرة في الصور",
        @"dw_save_to_camera_sub": @"احفظ مباشرة في مكتبة الصور بدل قائمة المشاركة",
        @"dw_reel_audio_title": @"تفعيل تنزيل صوت الريلز",
        @"dw_reel_audio_sub": @"عند تنزيل ريل، اختر بين الفيديو أو الصوت فقط",
        @"dw_choice_video": @"تنزيل الفيديو",
        @"dw_choice_audio": @"تنزيل الصوت فقط",
        @"copy_account_info_title": @"نسخ معلومات الحساب",
        @"copy_account_info_sub": @"اضغط مطوّلًا على صورة الملف الشخصي لنسخ اسم المستخدم والاسم",
        @"custom_album_title": @"الحفظ في ألبوم \"Albrhi\"",
        @"custom_album_sub": @"تنظيم الوسائط المحفوظة في ألبوم مخصّص داخل الصور",
        @"accent_color_title": @"لون التمييز",
        @"accent_color_sub": @"خصّص لون Albrhi المميّز",
        @"accent_reset_title": @"إعادة تعيين اللون",
        @"info_download_pfp": @"تنزيل صورة الملف الشخصي",
        @"info_copy": @"نسخ معلومات الحساب",
        @"info_copied": @"تم نسخ معلومات الحساب",
        @"info_unavailable": @"معلومات الحساب غير متاحة",
        @"info_verified": @"✓ موثّق",
        @"quality_unknown": @"جودة غير معروفة",
        @"dw_silent_video_title": @"تنزيل الفيديو بدون صوت",
        @"dw_silent_video_sub": @"إزالة مسار الصوت من الفيديوهات المنزّلة",

        // الخصوصية

        // اللغة
        @"section_language": @"اللغة",
        @"language_title": @"اللغة",
        @"language_sub": @"اختر لغة واجهة Albrhi",
        @"language_system": @"لغة النظام",
        @"language_arabic": @"العربية",
        @"language_english": @"English (الإنجليزية)",

        // إعدادات
        @"settings_title": @"إعدادات Albrhi",
        @"settings_header": @"Albrhi",
        @"quick_access_title": @"وصول سريع للإعدادات",
        @"quick_access_sub": @"اضغط مطوّلًا على تبويب الرئيسية لفتح إعدادات Albrhi",
        @"open_on_launch_title": @"فتح الإعدادات عند التشغيل",
        @"reset_first_run_title": @"إعادة تعيين شاشة الترحيب",
        @"credits_title": @"شكر وتقدير",
        @"credits_sub": @"Albrhi مبني على SCInsta من SoCuul (رخصة GPLv3)",
        @"view_repo_title": @"عرض الشيفرة المصدرية",
        @"view_repo_sub": @"Albrhi مفتوح المصدر تحت رخصة GPLv3",
        @"developer_title": @"المطوّر",
        @"section_connect": @"تواصل مع المطوّر",
        @"social_instagram_title": @"انستقرام",
        @"social_snapchat_title": @"سناب شات",
        @"social_telegram_title": @"تليقرام",
        @"social_open_sub": @"يفتح الحساب مباشرة",

        // رسائل التشغيل
        @"download_saved": @"تم الحفظ في الصور",
        @"download_failed": @"فشل التنزيل",
        @"err_no_photo": @"تعذّر استخراج رابط الصورة",
        @"err_no_video": @"تعذّر استخراج رابط الفيديو",
        @"err_no_media": @"تعذّر العثور على الوسائط المطلوب تنزيلها",

        // التشخيص
        @"diag_title": @"التشخيص",
        @"diag_sub": @"ما تراه Albrhi فعليًا أثناء التشغيل",
        @"diag_beta_footer": @"شيء لا يعمل؟ افتح التشخيص واضغط أيقونة الفقاعة — تُنشئ بلاغًا يحمل كل ما يلزم لإصلاحه.",
        @"diag_issue_what": @"**ماذا حدث**\n<صف ما توقّعته وما حصل>",
        @"diag_issue_steps": @"**خطوات إعادة الإنتاج**\n1. \n2. ",
        @"p_hdr_logging": @"السجل",
        @"p_verbose_t": @"سجل مفصّل",
        @"p_verbose_s": @"يكتب نشاطًا تفصيليًا في سجل النظام. مطفأ افتراضيًا — فعّله فقط أثناء إعادة إنتاج مشكلة.",
        @"diag_section_classes": @"أصناف شريط الأزرار في هذا الإصدار",
        @"diag_section_attached": @"ارتباطات زر التنزيل",
        @"diag_section_quality": @"آخر تنزيل فيديو",
        @"diag_section_stories": @"القصص",
        @"diag_section_env": @"البيئة",
        @"diag_class_present": @"موجود في نسخة انستقرام هذه",
        @"diag_class_absent": @"غير موجود",
        @"diag_attached": @"الزر مرتبط هنا",
        @"diag_button_media": @"الوسائط المُستخرجة عند آخر ضغطة",
        @"diag_button_unpressed": @"لم يُضغط الزر بعد",
        @"diag_button_nomedia": @"لم يُعثر على شيء — هذا سبب فشل التنزيل",
        @"diag_none_attached": @"لم يُرصد أي شريط أزرار بعد",
        @"diag_none_attached_hint": @"مرّر في الصفحة الرئيسية مرة، ثم أعد فتح هذه الصفحة",
        @"diag_quality_never": @"لم يُنزَّل أي فيديو في هذه الجلسة",
        @"diag_quality_single": @"وُجدت %ld نسخة فقط — لا يوجد خيار لعرضه",
        @"diag_quality_multi": @"وُجدت %ld نسخ",
        @"diag_quality_last": @"النسخ المتاحة",
        @"diag_quality_source": @"صنف الفيديو",
        @"diag_download_kind": @"آخر تنزيل عومل كـ",
        @"diag_section_dash": @"بيان DASH",
        @"diag_dash_none": @"لم يُلتقط بيان بعد",
        @"diag_dash_hint": @"نزّل فيديو ثم أعد فتح هذه الصفحة",
        @"diag_dash_found": @"حجم البيان",
        @"diag_dash_reps": @"عدد التمثيلات",
        @"diag_dash_excerpt": @"مقتطف خام",
        @"diag_dash_saveable": @"تمثيلات قابلة للحفظ (H.264/HEVC)",
        @"diag_dash_needs_transcode": @"  — يحتاج ترميزًا",
        @"diag_section_transcode": @"ترميز AV1",
        @"diag_transcode_none": @"لم تُجرَّب أي عملية ترميز بعد",
        @"diag_transcode_hint": @"فعّل ترميز AV1 ثم نزّل فيديو AV1",
        @"dw_transcode_av1_title": @"تحويل AV1 إلى 1080p",
        @"dw_transcode_av1_sub": @"إعادة ترميز سلّم AV1 إلى H.264 على الجهاز. أبطأ وأثقل؛ مطفأ افتراضيًا",
        @"transcode_progress": @"جارٍ المعالجة %dp…",
        @"transcode_fell_back": @"فشل الترميز — حُفظت الجودة العادية",
        @"transcode_saved": @"حُفظ",
        @"transcode_muxing": @"جارٍ الإنهاء…",
        @"transcode_frames": @"%ld إطار",
        @"transcode_saving": @"جارٍ الحفظ…",
        @"page_appearance": @"المظهر",
        @"p_hdr_dates": @"التواريخ",
        @"p_hdr_theme": @"السمة",
        @"date_enable_t": @"تنسيق تاريخ مخصّص",
        @"date_preset_t": @"النمط",
        @"date_preset_s": @"كيف يُكتب التاريخ الكامل",
        @"date_preset_absolute": @"Jan 5, 2026",
        @"date_preset_compact": @"05/01/26",
        @"date_preset_datetime": @"05/01/2026 14:30",
        @"date_preset_time": @"14:30:05 (الوقت فقط)",
        @"date_preset_custom": @"نمط مخصّص",
        @"date_24h_t": @"نظام 24 ساعة",
        @"date_24h_s": @"إطفاؤه يعرض 2:30 م بدل 14:30",
        @"date_compact_t": @"وقت نسبي مضغوط",
        @"date_compact_s": @"“2h” بدل “قبل ساعتين”",
        @"date_threshold_t": @"أبقِ النسبي تحت",
        @"date_combine_t": @"اعرض الاثنين",
        @"date_combine_s": @"التاريخ والوقت النسبي معًا",
        @"date_combine_off": @"مطفأ",
        @"date_combine_absolute_first": @"Jan 5, 2026 (2h)",
        @"date_combine_relative_first": @"2h – Jan 5, 2026",
        @"date_pattern_t": @"نمط مخصّص",
        @"date_pattern_help": @"الرموز: {DD} {MM} {MMM} {YYYY} {YY} {HH} {hh} {mm} {ss} {A} {EEE}",
        @"date_pattern_save": @"حفظ",
        @"date_preview_off": @"مطفأ — صياغة إنستقرام نفسها",
        @"date_ago_format": @"قبل %ld %@",
        @"date_unit_second": @"ثانية",
        @"date_unit_seconds": @"ثوانٍ",
        @"date_unit_minute": @"دقيقة",
        @"date_unit_minutes": @"دقائق",
        @"date_unit_hour": @"ساعة",
        @"date_unit_hours": @"ساعات",
        @"date_unit_day": @"يوم",
        @"date_unit_days": @"أيام",
        @"date_unit_week": @"أسبوع",
        @"date_unit_weeks": @"أسابيع",
        @"date_unit_month": @"شهر",
        @"date_unit_months": @"أشهر",
        @"date_unit_year": @"سنة",
        @"date_unit_years": @"سنوات",
        @"p_dm_keepdel_t": @"حفظ الرسائل المحذوفة",
        @"p_dm_keepdel_s": @"يبقي ما يتراجع الآخرون عن إرساله. السحب للتحديث في الوارد يمسحها",
        @"p_dm_lastactive_t": @"وقت آخر ظهور كاملًا",
        @"p_dm_lastactive_s": @"تاريخ حقيقي بدل “نشط قبل ساعتين”، بالتنسيق الذي اخترته",
        @"p_dm_voicecall_t": @"إخفاء زر المكالمة الصوتية",
        @"p_dm_voicecall_s": @"يزيله من ترويسة المحادثة",
        @"p_dm_videocall_t": @"إخفاء زر مكالمة الفيديو",
        @"p_dm_videocall_s": @"يزيله من ترويسة المحادثة",
        @"oled_t": @"سمة OLED سوداء",
        @"oled_s": @"يستبدل رمادي إنستقرام الداكن بأسود نقي",
        @"diag_section_timestamps": @"عناصر الوقت على الشاشة",
        @"diag_ts_prompt": @"لم يُمسح بعد",
        @"diag_ts_empty": @"لم يُعثر على عناصر وقت",
        @"diag_ts_hint": @"افتح التغذية خلف هذه الصفحة ثم امسح ثانية",
        @"diag_ts_sample_header": @"لا تطابق — هذا ما تقوله العناصر:",
        @"diag_section_dateformat": @"مُنسّقات التاريخ المستعملة",
        @"diag_df_none": @"لم يُرصد أي مُنسّق بعد",
        @"diag_df_hint": @"مرّر التغذية، وافتح قصة ومحادثة، ثم أعد فتح هذه الصفحة",
        @"diag_section_daterewrite": @"الأوقات المُبدَّلة",
        @"diag_dr_none": @"لم يُبدَّل شيء بعد",
        @"diag_dr_hint": @"فعّل التاريخ المخصّص، مرّر التغذية، ثم أعد فتح الصفحة",
        @"diag_dr_count": @"عدد التبديلات",
        @"diag_dr_hooks": @"سيليكتورات NSDate المربوطة",
        @"err_save_failed": @"تعذّر الحفظ في الصور",
        @"diag_dash_empty": @"عمل المسبار ولم يجد بيانًا",
        @"diag_dash_empty_hint": @"لا كائن الفيديو ولا الوسائط يحمل بيانًا",
        @"diag_dash_candidates": @"أسماء تذكر dash أو manifest",
        @"diag_dash_no_candidates": @"لا شيء — الحقل غير مكشوف في هذه الأصناف",
        @"diag_on": @"مفعّل",
        @"diag_off": @"مطفأ",
        @"diag_story_intercepts": @"إشعارات مشاهدة مُوقَفة",
        @"diag_seen_replay": @"إعادة تشغيل تعليم المشاهدة",
        @"diag_copied": @"تم نسخ التقرير",
        @"diag_section_scan": @"مسح الشاشة الحيّة",
        @"diag_scan_prompt": @"لم يُجرَ المسح بعد",
        @"diag_scan_hint": @"افتح منشورًا خلف هذه الصفحة، ثم اضغط زر العدسة أعلاه",
        @"diag_scan_empty": @"لا يوجد ما يشبه شريط أزرار على الشاشة",

        // زر مشاهدة القصة
        @"story_seen_button_title": @"زر تعليم كمشاهَد",
        @"story_seen_button_sub": @"يضيف زر عين في عارض القصص لتسجيل القصة كمشاهَدة",

        // الترحيب وما الجديد
        @"wn_welcome_title": @"أهلًا بك في Albrhi",
        @"wn_welcome_sub": @"انستقرام، ناقصًا الأشياء التي لم يطلبها أحد.",
        @"wn_update_title": @"Albrhi %@",
        @"wn_update_sub": @"إليك ما تغيّر بينما كنت تتصفّح.",
        @"wn_continue": @"يلا نبدأ",

        @"wn_w1_title": @"نزّل أي شيء",
        @"wn_w1_detail": @"زر التنزيل موجود في شريط أزرار المنشورات والريلز. ضغطة واحدة، أعلى جودة، مباشرة إلى الاستوديو.",
        @"wn_w2_title": @"شاهد بلا أثر",
        @"wn_w2_detail": @"القصص والرسائل التي تُفتح مرة واحدة لا تُسجّل مشاهدتك — حتى تقرّر أنت غير ذلك من زر العين.",
        @"wn_w3_title": @"صفحة رئيسية أهدأ",
        @"wn_w3_detail": @"الإعلانات والمنشورات المقترحة والحسابات المقترحة وMeta AI… ودّعناهم جميعًا بأدب.",
        @"wn_w4_title": @"وين الإعدادات؟",
        @"wn_w4_detail": @"اضغط مطوّلًا على ☰ في ملفك الشخصي. هذه كل الحيلة — لا إيماءات خفية تحفظها.",

        @"wn_u1_title": @"تنزيل بجودة 1080p",
        @"wn_u1_detail": @"أعلى جودة في إنستقرام، تُحوَّل على جهازك.",
        @"wn_u2_title": @"التواريخ كما تريدها",
        @"wn_u2_detail": @"وقت حقيقي بدل «2h». أنماط جاهزة، أو نمطك، و12 أو 24 ساعة.",
        @"wn_u3_title": @"أسود حقيقي",
        @"wn_u3_detail": @"سمة OLED — أرحم للعين وللبطارية.",
        @"wn_u4_title": @"مركز التنزيلات",
        @"wn_u4_detail": @"طابور وإيقاف واستئناف وسجل لكل ما حفظته.",

        @"wn_show_again": @"عرض صفحة الترحيب مرة أخرى",
        @"wn_footnote_welcome": @"مجاني ومفتوح المصدر، وغير تابع لانستقرام — هم أصلًا لا يعلمون بوجودنا.",
        @"wn_footnote_update": @"لم تُضَف أي إعلانات أثناء إعداد هذا التحديث.",

        // مركز التنزيلات
        @"dl_center_title": @"مركز التنزيلات",
        @"dl_center_sub": @"الطابور والتقدّم وسجل كل التنزيلات",
        @"dl_section_active": @"جارية",
        @"dl_section_history": @"السجل",
        @"dl_total_footer": @"إجمالي ما تم تنزيله: %@",
        @"dl_search_placeholder": @"ابحث في التنزيلات",
        @"dl_scope_all": @"الكل",
        @"dl_kind_photo": @"صورة",
        @"dl_kind_video": @"فيديو",
        @"dl_kind_audio": @"صوت",
        @"dl_kind_file": @"ملف",
        @"dl_state_queued": @"في الانتظار…",
        @"dl_state_paused": @"متوقّف مؤقتًا",
        @"dl_state_failed": @"فشل",
        @"dl_state_cancelled": @"أُلغي",
        @"dl_size_of": @"%@ من %@",
        @"dl_pause": @"إيقاف مؤقت",
        @"dl_resume": @"استئناف",
        @"dl_retry": @"إعادة المحاولة",
        @"dl_cancel": @"إلغاء",
        @"dl_pause_all": @"إيقاف الكل",
        @"dl_resume_all": @"استئناف الكل",
        @"dl_clear_history": @"مسح السجل",
        @"dl_clear_history_message": @"يزيل كل التنزيلات المنتهية من القائمة. لن تُحذف الملفات المحفوظة.",
        @"dl_share": @"مشاركة",
        @"dl_copy_link": @"نسخ الرابط",
        @"dl_remove": @"إزالة",
        @"dl_sort_title": @"الترتيب حسب",
        @"dl_sort_newest": @"الأحدث أولًا",
        @"dl_sort_oldest": @"الأقدم أولًا",
        @"dl_sort_name": @"الاسم",
        @"dl_sort_size": @"الحجم",
        @"dl_empty_title": @"لا توجد تنزيلات بعد",
        @"dl_empty_sub": @"ستظهر هنا الوسائط التي تحفظها، مع التقدّم والسجل.",
        @"dl_use_queue_title": @"استخدام طابور التنزيل",
        @"dl_use_queue_sub": @"تعمل التنزيلات في الخلفية وتستمر عند مغادرة التطبيق",
        @"dl_max_concurrent_title": @"عدد التنزيلات المتزامنة",
        @"dl_clear_title": @"الحذف بعد الحفظ",
        @"dl_clear_sub": @"يزيل التنزيل من هذه القائمة بعد حفظه في الصور، فلا يُخزَّن مرتين",
        @"dl_added_to_queue": @"أُضيف إلى الطابور",
        @"dl_already_downloaded": @"تم تنزيله مسبقًا",

        // عناوين صفحات المزايا
        @"page_general": @"عام",
        @"page_feed": @"الصفحة الرئيسية",
        @"page_reels": @"الريلز",
        @"page_stories_messages": @"القصص والرسائل",
        @"page_navigation": @"شريط التنقل",
        @"page_confirmations": @"تأكيد الإجراءات",

        @"inline_download_title": @"زر تحميل مدمج",
        @"inline_download_sub": @"يضيف أيقونة تنزيل في شريط أزرار المنشور بجانب زر الحفظ",
        @"loading": @"جارٍ التحميل",
        @"cancel": @"إلغاء",

        // ---- صفحات الإعدادات (مترجمة بالكامل) ----
        // عام
        @"p_general_ads_t": @"إخفاء الإعلانات", @"p_general_ads_s": @"يزيل جميع الإعلانات من تطبيق انستقرام",
        @"p_general_metaai_t": @"إخفاء Meta AI", @"p_general_metaai_s": @"يخفي أزرار ووظائف Meta AI داخل التطبيق",
        @"p_general_copydesc_t": @"نسخ الوصف", @"p_general_copydesc_s": @"انسخ نص الوصف بالضغط المطوّل عليه",
        @"p_general_norecent_t": @"عدم حفظ عمليات البحث الأخيرة", @"p_general_norecent_s": @"لن تحفظ أشرطة البحث عمليات بحثك الأخيرة",
        @"p_general_colorpicker_t": @"منتقي ألوان مفصّل", @"p_general_colorpicker_s": @"اضغط مطوّلًا على أداة القطارة في القصص لاختيار لون النص بدقة",
        @"p_hdr_notes": @"الملاحظات",
        @"p_general_hidenotes_t": @"إخفاء شريط الملاحظات", @"p_general_hidenotes_s": @"يخفي شريط الملاحظات في صندوق الرسائل",
        @"p_general_friendsmap_t": @"إخفاء خريطة الأصدقاء", @"p_general_friendsmap_s": @"يخفي أيقونة خريطة الأصدقاء في شريط الملاحظات",
        @"p_general_notetheming_t": @"تنسيق الملاحظات", @"p_general_notetheming_s": @"يفعّل منتقي سمات الملاحظات",
        @"p_general_customnote_t": @"سمات ملاحظات مخصّصة", @"p_general_customnote_s": @"عيّن رموزًا تعبيرية وألوان خلفية ونص مخصّصة",
        @"p_hdr_focus": @"التركيز وتقليل التشتّت",
        @"p_general_nosuggusers_t": @"إخفاء الحسابات المقترحة", @"p_general_nosuggusers_s": @"يخفي الحسابات المقترحة للمتابعة خارج صفحتك الرئيسية",
        @"p_general_nosuggchats_t": @"إخفاء المحادثات المقترحة", @"p_general_nosuggchats_s": @"يخفي قنوات البث المقترحة في الرسائل",
        @"p_general_exploregrid_t": @"إخفاء شبكة الاستكشاف", @"p_general_exploregrid_s": @"يخفي شبكة المنشورات المقترحة في تبويب الاستكشاف",
        @"p_general_trending_t": @"إخفاء عمليات البحث الرائجة", @"p_general_trending_s": @"يخفي عمليات البحث الرائجة أسفل شريط بحث الاستكشاف",
        // الصفحة الرئيسية
        @"p_feed_storytray_t": @"إخفاء شريط القصص", @"p_feed_storytray_s": @"يخفي شريط القصص في الأعلى وداخل صفحتك الرئيسية",
        @"p_feed_entirefeed_t": @"إخفاء الصفحة الرئيسية بالكامل", @"p_feed_entirefeed_s": @"يزيل كل المحتوى من صفحتك الرئيسية بما في ذلك المنشورات",
        @"p_feed_nosuggposts_t": @"إخفاء المنشورات المقترحة", @"p_feed_nosuggposts_s": @"يزيل المنشورات المقترحة من صفحتك الرئيسية",
        @"p_feed_nosuggacct_t": @"إخفاء الحسابات المقترحة", @"p_feed_nosuggacct_s": @"يخفي الحسابات المقترحة للمتابعة",
        @"p_feed_nosuggreels_t": @"إخفاء الريلز المقترحة", @"p_feed_nosuggreels_s": @"يخفي الريلز المقترحة للمشاهدة",
        @"p_feed_nosuggthreads_t": @"إخفاء منشورات ثريدز المقترحة", @"p_feed_nosuggthreads_s": @"يخفي منشورات ثريدز المقترحة في صفحتك الرئيسية",
        @"p_feed_autoplay_t": @"تعطيل التشغيل التلقائي للفيديو", @"p_feed_autoplay_s": @"يمنع فيديوهات الصفحة الرئيسية من التشغيل تلقائيًا",
        // الريلز
        @"p_reels_tap_t": @"التحكم باللمس", @"p_reels_tap_s": @"غيّر ما يحدث عند النقر على الريل",
        @"p_reels_scrubber_t": @"إظهار شريط التقدّم دائمًا", @"p_reels_scrubber_s": @"يفرض ظهور شريط التقدّم على كل ريل",
        @"p_reels_unmute_t": @"تعطيل إلغاء الكتم التلقائي", @"p_reels_unmute_s": @"يمنع الريلز من إلغاء الكتم عند الضغط على زر الصوت",
        @"p_reels_refresh_t": @"تأكيد تحديث الريلز", @"p_reels_refresh_s": @"يعرض تنبيهًا عند تحديث الريلز",
        @"p_hdr_hiding": @"الإخفاء",
        @"p_reels_header_t": @"إخفاء رأس الريلز", @"p_reels_header_s": @"يخفي شريط التنقل العلوي أثناء مشاهدة الريلز",
        @"p_reels_blend_t": @"إخفاء زر المزج", @"p_reels_blend_s": @"يخفي زر فتح مزج الريلز في الرسائل",
        @"p_hdr_limits": @"الحدود",
        // القصص والرسائل
        @"p_hdr_messages": @"الرسائل",
        @"p_sm_markseen_t": @"تعليم الرسائل كمقروءة يدويًا", @"p_sm_markseen_s": @"يضيف زرًا في المحادثات لتعليم الرسائل كمقروءة",
        @"p_sm_typing_t": @"تعطيل حالة الكتابة", @"p_sm_typing_s": @"يمنع ظهور مؤشّر الكتابة للآخرين في الرسائل",
        @"p_hdr_visual": @"الرسائل المرئية والقصص",
        @"p_sm_replay_t": @"إعادة تشغيل غير محدودة للرسائل المرئية", @"p_sm_replay_s": @"أعد تشغيل الرسائل المرئية (لمرة واحدة/عادية) بلا حدود (بدّلها من أيقونة الصورة ذات علامة الصح في المحادثة)",
        @"p_sm_viewonce_t": @"تعطيل قيود العرض لمرة واحدة", @"p_sm_viewonce_s": @"يجعل رسائل العرض لمرة واحدة تتصرّف كالعادية (قابلة للتكرار والإيقاف)",
        @"p_sm_screenshot_t": @"تعطيل كشف لقطة الشاشة", @"p_sm_screenshot_s": @"يزيل تنبيهات لقطة الشاشة للرسائل المرئية في الرسائل",
        @"p_sm_seen_t": @"تعطيل إشعار مشاهدة القصة", @"p_sm_seen_s": @"لن يُشعَر الآخرون عند مشاهدتك لقصصهم",
        @"p_sm_instants_t": @"تعطيل إنشاء الإنستانت", @"p_sm_instants_s": @"يخفي إمكانية إنشاء/إرسال الإنستانت",
        // شريط التنقل
        @"p_nav_order_t": @"ترتيب الأيقونات", @"p_nav_order_s": @"ترتيب الأيقونات في شريط التنقل السفلي",
        @"p_nav_swipe_t": @"التمرير بين التبويبات", @"p_nav_swipe_s": @"مرّر للتبديل بين تبويبات شريط التنقل",
        @"p_hdr_hidetabs": @"إخفاء التبويبات",
        @"p_nav_feedtab_t": @"إخفاء تبويب الرئيسية", @"p_nav_feedtab_s": @"يخفي تبويب الرئيسية في شريط التنقل",
        @"p_nav_exploretab_t": @"إخفاء تبويب الاستكشاف", @"p_nav_exploretab_s": @"يخفي تبويب الاستكشاف/البحث في شريط التنقل",
        @"p_nav_reelstab_t": @"إخفاء تبويب الريلز", @"p_nav_reelstab_s": @"يخفي تبويب الريلز في شريط التنقل",
        @"p_nav_createtab_t": @"إخفاء تبويب الإنشاء", @"p_nav_createtab_s": @"يخفي تبويب الإنشاء في شريط التنقل",
        // تأكيد الإجراءات
        @"p_cf_like_t": @"تأكيد الإعجاب: المنشورات والقصص", @"p_cf_like_s": @"يسأل قبل الإعجاب بمنشور أو قصة",
        @"p_cf_likereels_t": @"تأكيد الإعجاب: الريلز", @"p_cf_likereels_s": @"يسأل قبل الإعجاب بريل",
        @"p_cf_follow_t": @"تأكيد المتابعة", @"p_cf_follow_s": @"يسأل قبل متابعة حساب",
        @"p_cf_repost_t": @"تأكيد إعادة النشر", @"p_cf_repost_s": @"يسأل قبل إعادة النشر",
        @"p_cf_call_t": @"تأكيد الاتصال", @"p_cf_call_s": @"يسأل قبل بدء مكالمة صوتية/مرئية",
        @"p_cf_voice_t": @"تأكيد الرسائل الصوتية", @"p_cf_voice_s": @"يسأل قبل إرسال رسالة صوتية",
        @"p_cf_followreq_t": @"تأكيد طلبات المتابعة", @"p_cf_followreq_s": @"يسأل قبل قبول/رفض طلب متابعة",
        @"p_cf_shh_t": @"تأكيد وضع الهمس", @"p_cf_shh_s": @"يسأل قبل تفعيل الرسائل المختفية",
        @"p_cf_comment_t": @"تأكيد نشر التعليق", @"p_cf_comment_s": @"يسأل قبل نشر تعليق",
        @"p_cf_theme_t": @"تأكيد تغيير السمة", @"p_cf_theme_s": @"يسأل قبل تغيير سمة المحادثة",
        @"p_cf_sticker_t": @"تأكيد التفاعل مع الملصق", @"p_cf_sticker_s": @"يسأل قبل النقر على ملصق في قصة أحدهم",
        // التصحيح
        @"p_hdr_debug": @"التصحيح",
        @"p_dbg_flexgesture_t": @"تفعيل إيماءة FLEX", @"p_dbg_flexgesture_s": @"اضغط بخمسة أصابع على الشاشة لفتح مستكشف FLEX",
        @"p_dbg_flexlaunch_t": @"فتح FLEX عند التشغيل", @"p_dbg_flexlaunch_s": @"يفتح FLEX تلقائيًا عند تشغيل التطبيق",
        @"p_dbg_flexfocus_t": @"فتح FLEX عند التنشيط", @"p_dbg_flexfocus_s": @"يفتح FLEX تلقائيًا عند تنشيط التطبيق",
        @"p_dbg_safemode_t": @"تعطيل الوضع الآمن", @"p_dbg_safemode_s": @"يمنع انستقرام من إعادة تعيين الإعدادات بعد الأعطال المتكررة (على مسؤوليتك)",
        // تسميات العدّادات
        @"p_lbl_downloads": @"تنزيلات", @"p_lbl_download": @"تنزيل",
        // القوائم
        @"p_menu_default": @"افتراضي", @"p_menu_pauseplay": @"إيقاف / تشغيل", @"p_menu_muteunmute": @"كتم / إلغاء الكتم",
        @"p_menu_classic": @"كلاسيكي", @"p_menu_standard": @"قياسي", @"p_menu_alternate": @"بديل",
        @"p_menu_enabled": @"مفعّل", @"p_menu_disabled": @"معطّل",
        // تنبيهات مشاهدة/إعادة تشغيل الرسائل المرئية
        @"p_toast_marked_seen": @"تم تعليم الرسائل كمقروءة",
        // حالة المتابعة
        @"p_follows_you": @"✓ يتابعك",
        @"p_not_follows_you": @"✗ لا يتابعك",
        @"p_followstatus_t": @"إظهار حالة المتابعة المتبادلة",
        @"p_followstatus_s": @"اضغط مطوّلًا على صورة الملف الشخصي لمعرفة إن كان الحساب يتابعك",
        // زر تحميل القصة
        @"p_story_dl_title": @"زر تحميل القصة",
        @"p_story_dl_sub": @"يظهر زر تحميل في عارض القصص لحفظ القصة الحالية",
        // زر حفظ وسائط الخاص
        @"p_dm_save_t": @"حفظ صور وفيديوهات الخاص",
        @"p_dm_save_s": @"يضيف زر حفظ عند فتح صورة أو فيديو في الرسائل، ويسمح بالحفظ دائمًا",
        // تنبيهات مشاهدة العرض لمرة واحدة
        @"p_dm_seen_already": @"معلَّم كمشاهَد مسبقًا",
        // إجراء الضغط المطوّل
        @"p_press_zoom": @"تكبير (معاينة)",
        @"p_press_off": @"إيقاف",
        // التنقل التلقائي للريل
    };
}

@end
