#import "SCILicense.h"
#import "SCIPanelGate.h"

#import <CommonCrypto/CommonDigest.h>
#import <Security/Security.h>
#import <dlfcn.h>
#import <sys/sysctl.h>

const NSTimeInterval SCILicenseGraceSeconds = 24 * 60 * 60;   // one day, the owner's choice

/// How often the revocation call is allowed to run. Six hours: often enough that a revoked key
/// stops working the same day, rare enough that it is not a request per launch.
static const NSTimeInterval kSCILicenseCheckInterval = 6 * 60 * 60;

static NSString *const kSCILicenseKeyPref     = @"licence_key";
static NSString *const kSCILicenseEnforcePref = @"licence_enforced";
static NSString *const kSCILicenseEndpoint    = @"https://ibrahim2100.github.io/albrhi-repo/licence/revoked.json";
static NSString *const kSCICodesEndpoint     = @"https://ibrahim2100.github.io/albrhi-repo/licence/codes.json";

static NSString *const kSCICodePref          = @"licence_code";
static NSString *const kSCICodeHashPref      = @"licence_code_hash";
static NSString *const kSCICodeDaysPref      = @"licence_code_days";
static NSString *const kSCICodeAtPref        = @"licence_code_at";
static NSString *const kSCICodeTierPref      = @"licence_code_tier";

/// The alphabet a code is written in.
///
/// Crockford's, and the reason is that these get read down a phone line and typed by hand: I, L,
/// O and U are gone, so there is no 1/I, no 0/O, and nothing that can be misheard into an
/// unfortunate word. Anything a person types that *looks* like one of those is folded back in
/// before the hash is taken, which is the half that actually saves the support message.
static NSString *const kSCICodeAlphabet = @"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// The fixed salt. Not a secret — it exists so a fingerprint cannot be recomputed from a serial
/// number by someone who has only seen the fingerprint and guessed the scheme.
static NSString *const kSCILicenseSalt = @"albrhi.licence.v1";

// The public half of the Albrhi licence key, as an uncompressed P-256 point.
// Generated by tools/licence.py keygen. Safe to publish — it only verifies.
static const uint8_t kSCILicensePublicKey[65] = {
    0x04, 0xA4, 0x5B, 0x34, 0x61, 0x51, 0xA7, 0x8E, 0xC0, 0x2F, 0x43, 0x8D,
    0x8A, 0x09, 0xC4, 0x1C, 0xF1, 0x66, 0x2E, 0xE4, 0x5F, 0xEF, 0xA8, 0xFD,
    0xFC, 0xD6, 0xD3, 0x54, 0x7A, 0x7E, 0x40, 0x23, 0x09, 0x05, 0x24, 0xC6,
    0xDB, 0xBD, 0x38, 0x06, 0x9A, 0x2C, 0x79, 0x8A, 0xDC, 0xD8, 0xA1, 0x89,
    0xA6, 0xD0, 0xDE, 0x15, 0x4C, 0x22, 0xC7, 0xD0, 0x4B, 0x64, 0xC9, 0xB8,
    0x4C, 0x07, 0xFC, 0xDB, 0xAE,
};

static BOOL sciFingerprintWeak = YES;

/// Declared here because the overall state consults it and is written above it: the file reads
/// top-down as key, then code, then the two combined, and reordering it to satisfy the compiler
/// would put the combination before either half it combines.
static SCILicenseState SCICodeState(void);


#pragma mark - The device

/// A value from libMobileGestalt, or nil.
///
/// `dlopen`/`dlsym` rather than a link: MobileGestalt is private, its presence is not something
/// to assume, and a missing symbol has to be an answer rather than a launch failure. Every
/// caller below treats nil as "use something else", which is why a device that refuses to
/// answer still gets a fingerprint.
static NSString *SCIGestaltString(NSString *question) {
    static void *handle = NULL;
    static CFStringRef (*copyAnswer)(CFStringRef) = NULL;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        handle = dlopen("/usr/lib/libMobileGestalt.dylib", RTLD_LAZY);
        if (handle) copyAnswer = (CFStringRef (*)(CFStringRef))dlsym(handle, "MGCopyAnswer");
    });

    if (!copyAnswer) return nil;

    CFStringRef answer = copyAnswer((__bridge CFStringRef)question);
    if (!answer) return nil;

    NSString *value = (__bridge_transfer NSString *)answer;
    return [value isKindOfClass:[NSString class]] && value.length ? value : nil;
}

/// The hardware model, from the kernel. Present on every device and unique to none.
static NSString *SCIHardwareModel(void) {
    char buffer[64] = {0};
    size_t size = sizeof(buffer) - 1;
    if (sysctlbyname("hw.machine", buffer, &size, NULL, 0) != 0) return @"?";
    return [NSString stringWithUTF8String:buffer] ?: @"?";
}

static NSString *const kSCIDevicePref = @"licence_device";
static NSString *const kSCIServerPref = @"licence_server";

/// Eight random bytes as sixteen hex characters.
///
/// Random rather than derived, which is the whole correction. A derived id has to be derivable in
/// every process that needs it, and the value this used to derive from -- MobileGestalt's serial
/// number -- is readable in Settings and not in a sandboxed app. A random id has no such problem
/// and identifies nothing about the phone or its owner.
static NSString *SCIFreshDeviceIdentity(void) {
    uint8_t bytes[8];
    if (SecRandomCopyBytes(kSecRandomDefault, sizeof(bytes), bytes) != errSecSuccess) {
        // Never a silent weaker fallback. An identity that might be predictable is worse than no
        // identity, because a key would be issued against it and trusted.
        return nil;
    }

    NSMutableString *hex = [NSMutableString string];
    for (int i = 0; i < 8; i++) [hex appendFormat:@"%02x", bytes[i]];
    return hex;
}

/// The legacy shape, kept only so a process with no provisioned identity still answers something.
///
/// Marked weak wherever it surfaces. It is deliberately *not* used for anything but saying "the
/// panel has not been opened yet": issuing a key against it is what caused the fault this whole
/// function was rewritten for.
static NSString *SCIProvisionalIdentity(void) {
    NSString *material = [NSString stringWithFormat:@"%@|%@|provisional",
                          kSCILicenseSalt, SCIHardwareModel()];

    NSData *bytes = [material dataUsingEncoding:NSUTF8StringEncoding];
    unsigned char digest[CC_SHA256_DIGEST_LENGTH];
    CC_SHA256(bytes.bytes, (CC_LONG)bytes.length, digest);

    NSMutableString *hex = [NSMutableString string];
    for (int i = 0; i < 8; i++) [hex appendFormat:@"%02x", digest[i]];
    return hex;
}

void SCILicenseProvisionDevice(void) {
    NSString *stored = SCIPanelReadString(kSCIDevicePref, nil);
    if (stored.length == 16) return;

    NSString *fresh = SCIFreshDeviceIdentity();
    if (!fresh) return;

    CFStringRef domain = (__bridge CFStringRef)@"com.albrhi.panel";
    CFPreferencesSetAppValue((__bridge CFStringRef)kSCIDevicePref,
                             (__bridge CFStringRef)fresh, domain);
    CFPreferencesAppSynchronize(domain);
}

NSString *SCILicenseFingerprint(void) {
    // Not memoised across the process's life, unlike everything else here.
    //
    // The panel provisions the identity while this same process is running, so a cached "there
    // isn't one" would outlive the moment one appeared -- and the page would go on showing a
    // provisional id right after writing a real one. The read is a preference lookup; it is
    // cheap enough to do honestly.
    NSString *stored = SCIPanelReadString(kSCIDevicePref, nil);
    if (stored.length == 16) {
        sciFingerprintWeak = NO;
        return stored.lowercaseString;
    }

    sciFingerprintWeak = YES;
    return SCIProvisionalIdentity();
}

BOOL SCILicenseFingerprintIsWeak(void) {
    SCILicenseFingerprint();       // sets the flag as a side effect of answering
    return sciFingerprintWeak;
}


#pragma mark - The key

static NSData *SCIBase64URLDecode(NSString *text) {
    if (!text.length) return nil;

    NSMutableString *padded = [text mutableCopy];
    [padded replaceOccurrencesOfString:@"-" withString:@"+"
                               options:0 range:NSMakeRange(0, padded.length)];
    [padded replaceOccurrencesOfString:@"_" withString:@"/"
                               options:0 range:NSMakeRange(0, padded.length)];
    while (padded.length % 4) [padded appendString:@"="];

    return [[NSData alloc] initWithBase64EncodedString:padded options:0];
}

/// The signature check itself.
///
/// `kSecKeyAlgorithmECDSASignatureMessageX962SHA256` hashes the message and verifies a DER
/// signature, which is exactly what `openssl dgst -sha256 -sign` produces — the two sides were
/// chosen together rather than made to meet afterwards.
static BOOL SCIVerifySignature(NSData *signedBytes, NSData *signature) {
    if (!signedBytes.length || !signature.length) return NO;

    NSData *point = [NSData dataWithBytes:kSCILicensePublicKey length:sizeof(kSCILicensePublicKey)];
    NSDictionary *attributes = @{
        (__bridge id)kSecAttrKeyType:  (__bridge id)kSecAttrKeyTypeECSECPrimeRandom,
        (__bridge id)kSecAttrKeyClass: (__bridge id)kSecAttrKeyClassPublic,
        (__bridge id)kSecAttrKeySizeInBits: @256,
    };

    CFErrorRef error = NULL;
    SecKeyRef key = SecKeyCreateWithData((__bridge CFDataRef)point,
                                         (__bridge CFDictionaryRef)attributes, &error);
    if (!key) {
        if (error) CFRelease(error);
        return NO;
    }

    BOOL ok = SecKeyVerifySignature(key,
                                    kSecKeyAlgorithmECDSASignatureMessageX962SHA256,
                                    (__bridge CFDataRef)signedBytes,
                                    (__bridge CFDataRef)signature,
                                    &error);
    CFRelease(key);
    if (error) CFRelease(error);
    return ok;
}

/// Parses and checks a key, without touching storage.
///
/// Order matters and is deliberate: **signature first, contents afterwards.** Reading a device
/// id or an expiry date out of a payload nobody has authenticated is reading whatever the person
/// holding the file decided to put there.
static SCILicenseState SCIEvaluateKey(NSString *key, NSDictionary **outPayload) {
    if (outPayload) *outPayload = nil;
    if (!key.length) return SCILicenseStateNone;

    NSArray<NSString *> *parts = [[key stringByTrimmingCharactersInSet:
        [NSCharacterSet whitespaceAndNewlineCharacterSet]] componentsSeparatedByString:@"."];

    if (parts.count != 3 || ![parts[0] isEqualToString:@"ALB1"]) return SCILicenseStateMalformed;

    NSString *signingInput = [NSString stringWithFormat:@"%@.%@", parts[0], parts[1]];
    NSData *signature = SCIBase64URLDecode(parts[2]);

    if (!SCIVerifySignature([signingInput dataUsingEncoding:NSUTF8StringEncoding], signature)) {
        return SCILicenseStateMalformed;
    }

    NSData *body = SCIBase64URLDecode(parts[1]);
    NSDictionary *payload = body ? [NSJSONSerialization JSONObjectWithData:body options:0 error:NULL] : nil;
    if (![payload isKindOfClass:[NSDictionary class]]) return SCILicenseStateMalformed;

    if (outPayload) *outPayload = payload;

    NSString *device = payload[@"dev"];
    if (![device isKindOfClass:[NSString class]] ||
        ![device.lowercaseString isEqualToString:SCILicenseFingerprint()]) {
        return SCILicenseStateWrongDevice;
    }

    NSNumber *expiry = payload[@"exp"];
    if (![expiry isKindOfClass:[NSNumber class]]) return SCILicenseStateMalformed;
    if (expiry.doubleValue <= [NSDate date].timeIntervalSince1970) return SCILicenseStateExpired;

    return SCILicenseStateValid;
}


#pragma mark - Storage and state

NSString *SCILicenseStoredKey(void) {
    NSString *key = SCIPanelReadString(kSCILicenseKeyPref, nil);
    return key.length ? key : nil;
}

BOOL SCILicenseIsEnforced(void) {
    //
    // **On unless switched off, as of Panel 0.9.27.**
    //
    // It shipped off for two releases on purpose, and that was the right order: the layer was
    // introduced, proved end to end on a real device — issued, entered, accepted, refused — and
    // only then turned on. Introducing a gate and enforcing it in the same release would have
    // stopped every existing install on the next update, before a single key had been issued to
    // fix them with.
    //
    // The absent-reads-as-on default is deliberate and is the opposite of the per-app switch
    // three functions up. That one reads absence as *off* because installing the suite must not
    // silently modify four apps nobody asked about. This one reads absence as *on* because the
    // question is whether the software may be used at all, and silence is not a licence.
    //
    // Switching it off is always possible: the panel is a Settings bundle and never asks this,
    // so nobody can be locked out of the screen that would let them back in.
    //
    return SCIPanelReadBool(kSCILicenseEnforcePref, YES);
}

/// The last time the server confirmed the key, and the ids it has revoked.
///
/// In NSUserDefaults for this process rather than in the panel's plist: a sandboxed app cannot
/// write the panel's domain -- that is a lesson this repository already paid for with the Watch
/// tweak -- and this is a cache, not a setting. Each app keeping its own copy costs one request
/// per app per six hours and needs no cross-sandbox write at all.
static NSString *const kSCILastCheckDefault = @"albrhi_licence_last_check";
static NSString *const kSCIRevokedDefault   = @"albrhi_licence_revoked";

static BOOL SCIKeyIsRevoked(NSDictionary *payload) {
    NSString *identifier = payload[@"id"];
    if (![identifier isKindOfClass:[NSString class]] || !identifier.length) return NO;

    NSArray *revoked = [[NSUserDefaults standardUserDefaults] arrayForKey:kSCIRevokedDefault];
    return [revoked isKindOfClass:[NSArray class]] && [revoked containsObject:identifier];
}

SCILicenseState SCILicenseCurrentState(void) {
    NSDictionary *payload = nil;
    SCILicenseState state = SCIEvaluateKey(SCILicenseStoredKey(), &payload);

    // Two ways to be licensed, and the better answer wins.
    //
    // A device can hold a key *and* have redeemed a code -- somebody who bought a code and later
    // got a key issued directly, most obviously. Refusing on the strength of whichever happens to
    // be worse would take a working licence away from a paying user over a leftover.
    if (state != SCILicenseStateValid) {
        SCILicenseState fromCode = SCICodeState();
        if (fromCode == SCILicenseStateValid) return SCILicenseStateValid;
        if (state == SCILicenseStateNone && fromCode != SCILicenseStateNone) return fromCode;
        return state;
    }

    if (SCIKeyIsRevoked(payload)) return SCILicenseStateRevoked;

    // Grace. The key is signed and in date; the only open question is whether it has been
    // withdrawn, and that needs the server. One day, then the answer stops being assumed.
    NSTimeInterval last = [[NSUserDefaults standardUserDefaults] doubleForKey:kSCILastCheckDefault];
    if (last > 0 && [NSDate date].timeIntervalSince1970 - last > SCILicenseGraceSeconds) {
        return SCILicenseStateGrace;
    }

    return SCILicenseStateValid;
}

BOOL SCILicenseAllows(void) {
    if (!SCILicenseIsEnforced()) return YES;

    switch (SCILicenseCurrentState()) {
        case SCILicenseStateValid:
            return YES;

        // Grace is *allowed*, and that is the point of having it: the key is genuine and in
        // date, and the only thing missing is a network this code has no right to demand. It is
        // reported, not punished.
        case SCILicenseStateGrace:
            return YES;

        default:
            return NO;
    }
}

BOOL SCILicenseStoreKey(NSString *key, SCILicenseState *outState) {
    NSDictionary *payload = nil;
    SCILicenseState state = SCIEvaluateKey(key, &payload);
    if (outState) *outState = state;

    if (state != SCILicenseStateValid) return NO;

    CFPreferencesSetAppValue((__bridge CFStringRef)kSCILicenseKeyPref,
                             (__bridge CFStringRef)key,
                             (__bridge CFStringRef)@"com.albrhi.panel");
    CFPreferencesAppSynchronize((__bridge CFStringRef)@"com.albrhi.panel");

    // A key accepted now is a key confirmed now: without this the very first launch after
    // entering one would already be a day into its grace period.
    [[NSUserDefaults standardUserDefaults] setDouble:[NSDate date].timeIntervalSince1970
                                              forKey:kSCILastCheckDefault];
    return YES;
}

void SCILicenseForgetKey(void) {
    CFPreferencesSetAppValue((__bridge CFStringRef)kSCILicenseKeyPref, NULL,
                             (__bridge CFStringRef)@"com.albrhi.panel");
    CFPreferencesAppSynchronize((__bridge CFStringRef)@"com.albrhi.panel");
}


#pragma mark - Check-in

void SCILicenseCheckInIfDue(void) {
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSTimeInterval last = [defaults doubleForKey:kSCILastCheckDefault];

    //
    // **With a server configured, the check-in is a renewal and it runs whether or not there is a
    // key already.** A device that has just been approved has nothing stored, so a `return` on an
    // empty key would mean the licence never arrives without somebody opening the panel — which
    // is exactly the sort of "works if you know the trick" behaviour this project keeps ending up
    // with when a gate is placed before the thing it gates.
    //
    if (SCILicenseServerBase()) {
        NSTimeInterval interval = kSCILicenseCheckInterval;

        // Renew sooner when the token is close to running out. Six hours is right for a healthy
        // token and far too slow for one with a day left: at that point the sync is not a
        // formality, it is the only thing standing between a paying user and a closed gate.
        NSDictionary *payload = nil;
        if (SCIEvaluateKey(SCILicenseStoredKey(), &payload) == SCILicenseStateValid) {
            NSNumber *expiry = payload[@"exp"];
            double left = [expiry isKindOfClass:[NSNumber class]]
                ? expiry.doubleValue - [NSDate date].timeIntervalSince1970 : 0;
            if (left < 2 * 86400) interval = 30 * 60;
        }

        if (last > 0 && [NSDate date].timeIntervalSince1970 - last < interval) return;

        // Not waited on, and its result is deliberately dropped: whatever it decides lands in the
        // stored token for the *next* question, and a launch must never sit behind a network call.
        SCILicenseSyncWithServer(nil);
        return;
    }

    if (!SCILicenseStoredKey()) return;
    if (last > 0 && [NSDate date].timeIntervalSince1970 - last < kSCILicenseCheckInterval) return;

    NSURL *url = [NSURL URLWithString:kSCILicenseEndpoint];
    if (!url) return;

    NSURLSessionConfiguration *configuration =
        [NSURLSessionConfiguration ephemeralSessionConfiguration];

    // Short, and never waited on. A licence check that can hold up a launch is a licence check
    // that will one day hold up every launch, and this project has a standing rule against a
    // fallback that hides a fault -- a hung request is that fault with a spinner over it.
    configuration.timeoutIntervalForRequest = 8;
    configuration.timeoutIntervalForResource = 12;

    NSURLSession *session = [NSURLSession sessionWithConfiguration:configuration];
    NSURLSessionDataTask *task = [session dataTaskWithURL:url
        completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
            NSInteger status = [response isKindOfClass:[NSHTTPURLResponse class]]
                ? ((NSHTTPURLResponse *)response).statusCode : 0;

            // Only a real answer counts. A timeout, a captive portal's login page or a 500 must
            // never be read as "revoked" -- that would take a paying user's features away
            // because a coffee shop's wifi asked them to sign in.
            if (error || status != 200 || !data.length) return;

            id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:NULL];
            NSArray *ids = [parsed isKindOfClass:[NSDictionary class]] ? parsed[@"revoked"] : nil;

            if ([ids isKindOfClass:[NSArray class]]) {
                [defaults setObject:ids forKey:kSCIRevokedDefault];
            }
            [defaults setDouble:[NSDate date].timeIntervalSince1970 forKey:kSCILastCheckDefault];
        }];

    [task resume];
}


#pragma mark - The server

NSString *SCILicenseServerBase(void) {
    NSString *base = SCIPanelReadString(kSCIServerPref, nil);
    if (!base.length) return nil;

    // Trailing slashes trimmed here rather than at four call sites, and https demanded rather
    // than assumed: a licence arriving over plain http could be swapped in flight by anyone on
    // the same wifi, and the signature would still check out because they could simply replay an
    // older, longer-lived one.
    while ([base hasSuffix:@"/"]) base = [base substringToIndex:base.length - 1];
    if (![base hasPrefix:@"https://"]) return nil;

    return base;
}

void SCILicenseSetServerBase(NSString *base) {
    CFStringRef domain = (__bridge CFStringRef)@"com.albrhi.panel";
    NSString *trimmed = [base stringByTrimmingCharactersInSet:
        [NSCharacterSet whitespaceAndNewlineCharacterSet]];

    CFPreferencesSetAppValue((__bridge CFStringRef)kSCIServerPref,
                             trimmed.length ? (__bridge CFStringRef)trimmed : NULL, domain);
    CFPreferencesAppSynchronize(domain);
}

/// One JSON POST, with every failure folded into "nothing was decided".
///
/// **A network problem is never reported as a licence problem.** That distinction is the single
/// most important thing in this file: a timeout, a 500 or a captive portal's login page must not
/// cost a paying user their features, and the seven-day token is what makes it safe to simply
/// shrug and try again later.
static void SCIPostJSON(NSString *path, NSDictionary *body,
                        void (^completion)(NSDictionary *_Nullable answer, NSInteger status)) {
    NSString *base = SCILicenseServerBase();
    if (!base) { completion(nil, 0); return; }

    NSURL *url = [NSURL URLWithString:[base stringByAppendingString:path]];
    if (!url) { completion(nil, 0); return; }

    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];
    request.HTTPMethod = @"POST";
    [request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];
    request.HTTPBody = [NSJSONSerialization dataWithJSONObject:body options:0 error:NULL];
    request.timeoutInterval = 12;

    NSURLSessionConfiguration *configuration =
        [NSURLSessionConfiguration ephemeralSessionConfiguration];
    configuration.timeoutIntervalForRequest = 12;
    configuration.timeoutIntervalForResource = 20;

    NSURLSession *session = [NSURLSession sessionWithConfiguration:configuration];
    [[session dataTaskWithRequest:request
                completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
        NSInteger status = [response isKindOfClass:[NSHTTPURLResponse class]]
            ? ((NSHTTPURLResponse *)response).statusCode : 0;

        id parsed = data.length ? [NSJSONSerialization JSONObjectWithData:data options:0 error:NULL]
                                : nil;

        dispatch_async(dispatch_get_main_queue(), ^{
            completion([parsed isKindOfClass:[NSDictionary class]] ? parsed : nil,
                       error ? 0 : status);
        });
    }] resume];
}

/// Stores a token the server signed, but only after checking it here.
///
/// The server is trusted to *decide*; it is not trusted to be reachable, correct, or even the
/// right server. A token that does not verify against the compiled public key, or is not for this
/// device, is dropped -- so pointing the address at something hostile gains nothing but a
/// refusal.
static BOOL SCIAcceptServerToken(NSString *token) {
    NSDictionary *payload = nil;
    if (SCIEvaluateKey(token, &payload) != SCILicenseStateValid) return NO;

    CFStringRef domain = (__bridge CFStringRef)@"com.albrhi.panel";
    CFPreferencesSetAppValue((__bridge CFStringRef)kSCILicenseKeyPref,
                             (__bridge CFStringRef)token, domain);
    CFPreferencesAppSynchronize(domain);

    [[NSUserDefaults standardUserDefaults] setDouble:[NSDate date].timeIntervalSince1970
                                              forKey:kSCILastCheckDefault];
    return YES;
}

static SCILicenseServerResult SCIResultForState(NSString *state) {
    if ([state isEqualToString:@"revoked"]) return SCILicenseServerRevoked;
    if ([state isEqualToString:@"expired"]) return SCILicenseServerExpired;
    return SCILicenseServerNoLicence;
}

void SCILicenseSyncWithServer(void (^completion)(SCILicenseServerResult)) {
    void (^finish)(SCILicenseServerResult) = ^(SCILicenseServerResult result) {
        if (completion) completion(result);
    };

    if (!SCILicenseServerBase()) { finish(SCILicenseServerNotConfigured); return; }

    SCIPostJSON(@"/v1/hello", @{@"dev": SCILicenseFingerprint()},
                ^(NSDictionary *answer, NSInteger status) {
        if (status != 200 || !answer) { finish(SCILicenseServerUnreachable); return; }

        NSString *token = answer[@"token"];
        if ([token isKindOfClass:[NSString class]] && SCIAcceptServerToken(token)) {
            finish(SCILicenseServerOK);
            return;
        }

        // A pending request is its own answer, not "no licence": the panel says "asked, waiting"
        // rather than offering to ask again, which is what stops one person filling the inbox.
        if ([answer[@"pending"] boolValue]) { finish(SCILicenseServerPending); return; }

        finish(SCIResultForState(answer[@"state"]));
    });
}

void SCILicenseRequestFromServer(NSInteger days, NSString *note,
                                 void (^completion)(SCILicenseServerResult)) {
    if (!SCILicenseServerBase()) { completion(SCILicenseServerNotConfigured); return; }

    NSMutableDictionary *body = [@{
        @"dev": SCILicenseFingerprint(),
        @"days": @(days < 1 ? 365 : days),
    } mutableCopy];

    NSString *trimmed = [note stringByTrimmingCharactersInSet:
        [NSCharacterSet whitespaceAndNewlineCharacterSet]];
    if (trimmed.length) body[@"note"] = trimmed;

    SCIPostJSON(@"/v1/request", body, ^(NSDictionary *answer, NSInteger status) {
        completion(status == 200 && answer ? SCILicenseServerPending
                                          : SCILicenseServerUnreachable);
    });
}

void SCILicenseRedeemWithServer(NSString *code, void (^completion)(SCILicenseRedeemResult)) {
    if (!SCILicenseServerBase()) {
        // Falls back to the published list, which is the scheme that shipped before the server
        // existed. A device pointed at no server can still redeem.
        SCILicenseRedeemCode(code, completion);
        return;
    }

    SCIPostJSON(@"/v1/redeem", @{@"dev": SCILicenseFingerprint(), @"code": code ?: @""},
                ^(NSDictionary *answer, NSInteger status) {
        if (status == 0 || !answer) { completion(SCILicenseRedeemOffline); return; }

        NSString *token = answer[@"token"];
        if (status == 200 && [token isKindOfClass:[NSString class]] &&
            SCIAcceptServerToken(token)) {
            completion(SCILicenseRedeemedOK);
            return;
        }

        NSString *state = answer[@"state"];
        if ([state isEqualToString:@"malformed"])     { completion(SCILicenseRedeemMalformed); return; }
        if ([state isEqualToString:@"window_closed"]) { completion(SCILicenseRedeemWindowClosed); return; }

        // "Already bound to another device" is its own sentence in the panel: it is the one
        // refusal here that means the code was real and somebody else got there first.
        if ([state isEqualToString:@"already_used"])  { completion(SCILicenseRedeemTaken); return; }

        completion(SCILicenseRedeemUnknown);
    });
}

NSTimeInterval SCILicenseTermEnds(void) {
    NSDictionary *payload = nil;
    if (SCIEvaluateKey(SCILicenseStoredKey(), &payload) != SCILicenseStateValid) return 0;

    // `until` when the server set one, `exp` otherwise. A manually issued offline key has no
    // renewal cycle, so its expiry *is* its term -- and showing a seven-day renewal date to
    // somebody who bought a year is the kind of screen that generates a support message.
    NSNumber *until = payload[@"until"];
    if ([until isKindOfClass:[NSNumber class]] && until.doubleValue > 0) return until.doubleValue;

    NSNumber *expiry = payload[@"exp"];
    return [expiry isKindOfClass:[NSNumber class]] ? expiry.doubleValue : 0;
}


#pragma mark - Saying so

#pragma mark - Asking for a licence

/// A short check over the payload. Typos, not tampering.
///
/// Named `check` rather than `sig` everywhere it surfaces, because a four-character digest that
/// looks like a signature is worse than none: somebody would eventually trust it as one.
static NSString *SCIRequestCheck(NSString *body) {
    NSData *bytes = [body dataUsingEncoding:NSUTF8StringEncoding];
    unsigned char digest[CC_SHA256_DIGEST_LENGTH];
    CC_SHA256(bytes.bytes, (CC_LONG)bytes.length, digest);
    return [NSString stringWithFormat:@"%02x%02x", digest[0], digest[1]];
}

NSString *SCILicenseMakeRequest(NSInteger days, NSString *note) {
    if (days < 1) days = 365;

    NSMutableDictionary *payload = [@{
        @"v": @1,
        @"dev": SCILicenseFingerprint(),
        @"days": @(days),
        @"ts": @((long long)[NSDate date].timeIntervalSince1970),
    } mutableCopy];

    NSString *trimmed = [note stringByTrimmingCharactersInSet:
        [NSCharacterSet whitespaceAndNewlineCharacterSet]];
    if (trimmed.length) payload[@"note"] = trimmed;

    // Sorted keys, so the same request made twice is the same string -- which is what lets the
    // panel recognise a duplicate paste instead of listing it twice.
    NSData *json = [NSJSONSerialization dataWithJSONObject:payload
                                                   options:NSJSONWritingSortedKeys
                                                     error:NULL];
    if (!json) return nil;

    NSString *body = [[[json base64EncodedStringWithOptions:0]
        stringByReplacingOccurrencesOfString:@"+" withString:@"-"]
        stringByReplacingOccurrencesOfString:@"/" withString:@"_"];
    body = [body stringByReplacingOccurrencesOfString:@"=" withString:@""];

    return [NSString stringWithFormat:@"ALBREQ1.%@.%@", body, SCIRequestCheck(body)];
}


#pragma mark - Redeeming a short code

/// Everything a person might type, folded into the alphabet the code was minted in.
static NSString *SCINormaliseCode(NSString *typed) {
    NSMutableString *out = [NSMutableString string];

    for (NSUInteger i = 0; i < typed.length; i++) {
        unichar c = [typed.uppercaseString characterAtIndex:i];

        // The confusable pairs, folded rather than rejected: somebody reading a code aloud says
        // "oh" for zero and "eye" for one, and refusing that is refusing the way people actually
        // pass a code to each other.
        if (c == 'O') c = '0';
        if (c == 'I' || c == 'L') c = '1';
        if (c == 'U') c = 'V';

        if ([kSCICodeAlphabet rangeOfString:[NSString stringWithCharacters:&c length:1]].location
                != NSNotFound) {
            [out appendFormat:@"%C", c];
        }
    }

    // The ALB prefix is written for the reader, not for the machine, and it is made of alphabet
    // characters -- so it survives the filter above and has to come off deliberately.
    if (out.length > 12 && [out hasPrefix:@"A1B"]) [out deleteCharactersInRange:NSMakeRange(0, 3)];

    return out;
}

/// The lookup key: sixteen hex characters of SHA-256 over the normalised code.
///
/// The published list holds these and never the codes themselves, so anybody may read it and
/// nobody gains a working code by doing so.
static NSString *SCICodeHash(NSString *normalised) {
    NSData *bytes = [normalised dataUsingEncoding:NSUTF8StringEncoding];
    unsigned char digest[CC_SHA256_DIGEST_LENGTH];
    CC_SHA256(bytes.bytes, (CC_LONG)bytes.length, digest);

    NSMutableString *hex = [NSMutableString string];
    for (int i = 0; i < 8; i++) [hex appendFormat:@"%02x", digest[i]];
    return hex;
}

NSString *SCILicenseRedeemedCode(void) {
    NSString *code = SCIPanelReadString(kSCICodePref, nil);
    return code.length ? code : nil;
}

void SCILicenseForgetCode(void) {
    for (NSString *key in @[kSCICodePref, kSCICodeHashPref, kSCICodeDaysPref,
                            kSCICodeAtPref, kSCICodeTierPref]) {
        CFPreferencesSetAppValue((__bridge CFStringRef)key, NULL,
                                 (__bridge CFStringRef)@"com.albrhi.panel");
    }
    CFPreferencesAppSynchronize((__bridge CFStringRef)@"com.albrhi.panel");
}

void SCILicenseRedeemCode(NSString *code, void (^completion)(SCILicenseRedeemResult)) {
    NSString *normalised = SCINormaliseCode(code ?: @"");

    void (^finish)(SCILicenseRedeemResult) = ^(SCILicenseRedeemResult result) {
        dispatch_async(dispatch_get_main_queue(), ^{ if (completion) completion(result); });
    };

    if (normalised.length != 12) { finish(SCILicenseRedeemMalformed); return; }

    NSURL *url = [NSURL URLWithString:kSCICodesEndpoint];
    if (!url) { finish(SCILicenseRedeemOffline); return; }

    NSURLSessionConfiguration *configuration =
        [NSURLSessionConfiguration ephemeralSessionConfiguration];
    configuration.timeoutIntervalForRequest = 12;
    configuration.timeoutIntervalForResource = 20;

    NSURLSession *session = [NSURLSession sessionWithConfiguration:configuration];
    [[session dataTaskWithURL:url completionHandler:^(NSData *data, NSURLResponse *response,
                                                      NSError *error) {
        NSInteger status = [response isKindOfClass:[NSHTTPURLResponse class]]
            ? ((NSHTTPURLResponse *)response).statusCode : 0;

        // "Could not read the list" is its own answer, never "no such code". Telling somebody
        // their code is wrong because a coffee shop's wifi asked them to sign in is the shape of
        // support message this whole file is written to avoid.
        if (error || status != 200 || !data.length) { finish(SCILicenseRedeemOffline); return; }

        id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:NULL];
        NSDictionary *codes = [parsed isKindOfClass:[NSDictionary class]] ? parsed[@"codes"] : nil;
        if (![codes isKindOfClass:[NSDictionary class]]) { finish(SCILicenseRedeemOffline); return; }

        NSDictionary *terms = codes[SCICodeHash(normalised)];
        if (![terms isKindOfClass:[NSDictionary class]]) { finish(SCILicenseRedeemUnknown); return; }

        NSNumber *redeemBy = terms[@"rb"];
        if ([redeemBy isKindOfClass:[NSNumber class]] &&
            redeemBy.doubleValue > 0 &&
            redeemBy.doubleValue <= [NSDate date].timeIntervalSince1970) {
            finish(SCILicenseRedeemWindowClosed);
            return;
        }

        NSNumber *days = terms[@"days"];
        NSInteger duration = [days isKindOfClass:[NSNumber class]] ? days.integerValue : 0;
        if (duration < 1) duration = 365;

        NSString *tier = [terms[@"tier"] isKindOfClass:[NSString class]] ? terms[@"tier"] : @"suite";

        // **The clock starts now, not when the code was minted.** A code sold in January and
        // redeemed in March is a year from March -- anything else quietly sells somebody two
        // months less than they paid for.
        CFStringRef domain = (__bridge CFStringRef)@"com.albrhi.panel";
        CFPreferencesSetAppValue((__bridge CFStringRef)kSCICodePref,
                                 (__bridge CFStringRef)normalised, domain);
        CFPreferencesSetAppValue((__bridge CFStringRef)kSCICodeHashPref,
                                 (__bridge CFStringRef)SCICodeHash(normalised), domain);
        CFPreferencesSetAppValue((__bridge CFStringRef)kSCICodeDaysPref,
                                 (__bridge CFNumberRef)@(duration), domain);
        CFPreferencesSetAppValue((__bridge CFStringRef)kSCICodeAtPref,
                                 (__bridge CFNumberRef)@((long long)[NSDate date].timeIntervalSince1970),
                                 domain);
        CFPreferencesSetAppValue((__bridge CFStringRef)kSCICodeTierPref,
                                 (__bridge CFStringRef)tier, domain);
        CFPreferencesAppSynchronize(domain);

        [[NSUserDefaults standardUserDefaults] setDouble:[NSDate date].timeIntervalSince1970
                                                  forKey:kSCILastCheckDefault];
        finish(SCILicenseRedeemedOK);
    }] resume];
}

/// The state of a redeemed code, if there is one.
static SCILicenseState SCICodeState(void) {
    NSString *code = SCILicenseRedeemedCode();
    if (!code.length) return SCILicenseStateNone;

    NSString *hash = SCIPanelReadString(kSCICodeHashPref, nil);

    // Recomputed rather than trusted. The stored hash is a convenience for the report; the code
    // itself is what was redeemed, and if the two disagree the stored pair has been edited.
    if (hash.length && ![hash isEqualToString:SCICodeHash(code)]) return SCILicenseStateMalformed;

    NSArray *revoked = [[NSUserDefaults standardUserDefaults] arrayForKey:kSCIRevokedDefault];
    if ([revoked isKindOfClass:[NSArray class]] && [revoked containsObject:SCICodeHash(code)]) {
        return SCILicenseStateRevoked;
    }

    double activated = SCIPanelReadNumber(kSCICodeAtPref, 0);
    double days = SCIPanelReadNumber(kSCICodeDaysPref, 0);
    if (activated <= 0 || days <= 0) return SCILicenseStateMalformed;

    if ([NSDate date].timeIntervalSince1970 > activated + days * 86400) {
        return SCILicenseStateExpired;
    }

    return SCILicenseStateValid;
}


NSString *SCILicenseDescribeState(SCILicenseState state) {
    NSString *device = SCILicenseFingerprint();
    switch (state) {
        case SCILicenseStateValid:
            return [NSString stringWithFormat:@"licensed · device %@", device];
        case SCILicenseStateGrace:
            return [NSString stringWithFormat:@"licensed, not confirmed for over a day · device %@", device];
        case SCILicenseStateNone:
            return [NSString stringWithFormat:@"no key · device %@", device];
        case SCILicenseStateExpired:
            return [NSString stringWithFormat:@"key expired · device %@", device];
        case SCILicenseStateWrongDevice:
            return [NSString stringWithFormat:@"key was issued to another device · this one is %@", device];
        case SCILicenseStateRevoked:
            return [NSString stringWithFormat:@"key withdrawn · device %@", device];
        case SCILicenseStateMalformed:
            return @"that is not a valid key";
    }
    return @"?";
}

NSString *SCILicenseStatusLine(void) {
    if (!SCILicenseIsEnforced()) {
        return [NSString stringWithFormat:@"not enforced · device %@%@",
                SCILicenseFingerprint(),
                SCILicenseFingerprintIsWeak() ? @" (weak — no device-unique value readable)" : @""];
    }
    return SCILicenseDescribeState(SCILicenseCurrentState());
}
