#import "SCILicense.h"
#import "SCIPanelGate.h"

#import <CommonCrypto/CommonDigest.h>
#import <Security/Security.h>
#import <dlfcn.h>
#import <sys/sysctl.h>

const NSTimeInterval SCILicenseGraceSeconds = 24 * 60 * 60;   // one day, the owner's choice

/// How often the revocation call is allowed to run. Six hours: often enough that a revoked key
/// stops working the same day, rare enough that it is not a request per launch.
static const NSTimeInterval kSCILicenseCheckInterval = 6 * 60 * 60;

static NSString *const kSCILicenseKeyPref     = @"licence_key";
static NSString *const kSCILicenseEnforcePref = @"licence_enforced";
static NSString *const kSCILicenseEndpoint    = @"https://ibrahim2100.github.io/albrhi-repo/licence/revoked.json";

/// The fixed salt. Not a secret — it exists so a fingerprint cannot be recomputed from a serial
/// number by someone who has only seen the fingerprint and guessed the scheme.
static NSString *const kSCILicenseSalt = @"albrhi.licence.v1";

// The public half of the Albrhi licence key, as an uncompressed P-256 point.
// Generated by tools/licence.py keygen. Safe to publish — it only verifies.
static const uint8_t kSCILicensePublicKey[65] = {
    0x04, 0xA4, 0x5B, 0x34, 0x61, 0x51, 0xA7, 0x8E, 0xC0, 0x2F, 0x43, 0x8D,
    0x8A, 0x09, 0xC4, 0x1C, 0xF1, 0x66, 0x2E, 0xE4, 0x5F, 0xEF, 0xA8, 0xFD,
    0xFC, 0xD6, 0xD3, 0x54, 0x7A, 0x7E, 0x40, 0x23, 0x09, 0x05, 0x24, 0xC6,
    0xDB, 0xBD, 0x38, 0x06, 0x9A, 0x2C, 0x79, 0x8A, 0xDC, 0xD8, 0xA1, 0x89,
    0xA6, 0xD0, 0xDE, 0x15, 0x4C, 0x22, 0xC7, 0xD0, 0x4B, 0x64, 0xC9, 0xB8,
    0x4C, 0x07, 0xFC, 0xDB, 0xAE,
};

static BOOL sciFingerprintWeak = YES;


#pragma mark - The device

/// A value from libMobileGestalt, or nil.
///
/// `dlopen`/`dlsym` rather than a link: MobileGestalt is private, its presence is not something
/// to assume, and a missing symbol has to be an answer rather than a launch failure. Every
/// caller below treats nil as "use something else", which is why a device that refuses to
/// answer still gets a fingerprint.
static NSString *SCIGestaltString(NSString *question) {
    static void *handle = NULL;
    static CFStringRef (*copyAnswer)(CFStringRef) = NULL;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        handle = dlopen("/usr/lib/libMobileGestalt.dylib", RTLD_LAZY);
        if (handle) copyAnswer = (CFStringRef (*)(CFStringRef))dlsym(handle, "MGCopyAnswer");
    });

    if (!copyAnswer) return nil;

    CFStringRef answer = copyAnswer((__bridge CFStringRef)question);
    if (!answer) return nil;

    NSString *value = (__bridge_transfer NSString *)answer;
    return [value isKindOfClass:[NSString class]] && value.length ? value : nil;
}

/// The hardware model, from the kernel. Present on every device and unique to none.
static NSString *SCIHardwareModel(void) {
    char buffer[64] = {0};
    size_t size = sizeof(buffer) - 1;
    if (sysctlbyname("hw.machine", buffer, &size, NULL, 0) != 0) return @"?";
    return [NSString stringWithUTF8String:buffer] ?: @"?";
}

NSString *SCILicenseFingerprint(void) {
    static NSString *fingerprint = nil;
    static dispatch_once_t once;
    dispatch_once(&once, ^{
        // Serial first, then UDID. Either is device-unique; neither leaves this function.
        NSString *unique = SCIGestaltString(@"SerialNumber");
        if (!unique.length) unique = SCIGestaltString(@"UniqueDeviceID");

        sciFingerprintWeak = (unique.length == 0);

        NSString *material = [NSString stringWithFormat:@"%@|%@|%@",
                              kSCILicenseSalt, SCIHardwareModel(), unique ?: @"-"];

        NSData *bytes = [material dataUsingEncoding:NSUTF8StringEncoding];
        unsigned char digest[CC_SHA256_DIGEST_LENGTH];
        CC_SHA256(bytes.bytes, (CC_LONG)bytes.length, digest);

        // Eight bytes of a SHA-256 is sixty-four bits: far too wide to collide across the
        // number of phones this will ever run on, and short enough to be read aloud down a
        // phone line, which is how a licence actually gets issued.
        NSMutableString *hex = [NSMutableString string];
        for (int i = 0; i < 8; i++) [hex appendFormat:@"%02x", digest[i]];
        fingerprint = [hex copy];
    });
    return fingerprint;
}

BOOL SCILicenseFingerprintIsWeak(void) {
    SCILicenseFingerprint();       // computes the flag as a side effect of the once-block
    return sciFingerprintWeak;
}


#pragma mark - The key

static NSData *SCIBase64URLDecode(NSString *text) {
    if (!text.length) return nil;

    NSMutableString *padded = [text mutableCopy];
    [padded replaceOccurrencesOfString:@"-" withString:@"+"
                               options:0 range:NSMakeRange(0, padded.length)];
    [padded replaceOccurrencesOfString:@"_" withString:@"/"
                               options:0 range:NSMakeRange(0, padded.length)];
    while (padded.length % 4) [padded appendString:@"="];

    return [[NSData alloc] initWithBase64EncodedString:padded options:0];
}

/// The signature check itself.
///
/// `kSecKeyAlgorithmECDSASignatureMessageX962SHA256` hashes the message and verifies a DER
/// signature, which is exactly what `openssl dgst -sha256 -sign` produces — the two sides were
/// chosen together rather than made to meet afterwards.
static BOOL SCIVerifySignature(NSData *signedBytes, NSData *signature) {
    if (!signedBytes.length || !signature.length) return NO;

    NSData *point = [NSData dataWithBytes:kSCILicensePublicKey length:sizeof(kSCILicensePublicKey)];
    NSDictionary *attributes = @{
        (__bridge id)kSecAttrKeyType:  (__bridge id)kSecAttrKeyTypeECSECPrimeRandom,
        (__bridge id)kSecAttrKeyClass: (__bridge id)kSecAttrKeyClassPublic,
        (__bridge id)kSecAttrKeySizeInBits: @256,
    };

    CFErrorRef error = NULL;
    SecKeyRef key = SecKeyCreateWithData((__bridge CFDataRef)point,
                                         (__bridge CFDictionaryRef)attributes, &error);
    if (!key) {
        if (error) CFRelease(error);
        return NO;
    }

    BOOL ok = SecKeyVerifySignature(key,
                                    kSecKeyAlgorithmECDSASignatureMessageX962SHA256,
                                    (__bridge CFDataRef)signedBytes,
                                    (__bridge CFDataRef)signature,
                                    &error);
    CFRelease(key);
    if (error) CFRelease(error);
    return ok;
}

/// Parses and checks a key, without touching storage.
///
/// Order matters and is deliberate: **signature first, contents afterwards.** Reading a device
/// id or an expiry date out of a payload nobody has authenticated is reading whatever the person
/// holding the file decided to put there.
static SCILicenseState SCIEvaluateKey(NSString *key, NSDictionary **outPayload) {
    if (outPayload) *outPayload = nil;
    if (!key.length) return SCILicenseStateNone;

    NSArray<NSString *> *parts = [[key stringByTrimmingCharactersInSet:
        [NSCharacterSet whitespaceAndNewlineCharacterSet]] componentsSeparatedByString:@"."];

    if (parts.count != 3 || ![parts[0] isEqualToString:@"ALB1"]) return SCILicenseStateMalformed;

    NSString *signingInput = [NSString stringWithFormat:@"%@.%@", parts[0], parts[1]];
    NSData *signature = SCIBase64URLDecode(parts[2]);

    if (!SCIVerifySignature([signingInput dataUsingEncoding:NSUTF8StringEncoding], signature)) {
        return SCILicenseStateMalformed;
    }

    NSData *body = SCIBase64URLDecode(parts[1]);
    NSDictionary *payload = body ? [NSJSONSerialization JSONObjectWithData:body options:0 error:NULL] : nil;
    if (![payload isKindOfClass:[NSDictionary class]]) return SCILicenseStateMalformed;

    if (outPayload) *outPayload = payload;

    NSString *device = payload[@"dev"];
    if (![device isKindOfClass:[NSString class]] ||
        ![device.lowercaseString isEqualToString:SCILicenseFingerprint()]) {
        return SCILicenseStateWrongDevice;
    }

    NSNumber *expiry = payload[@"exp"];
    if (![expiry isKindOfClass:[NSNumber class]]) return SCILicenseStateMalformed;
    if (expiry.doubleValue <= [NSDate date].timeIntervalSince1970) return SCILicenseStateExpired;

    return SCILicenseStateValid;
}


#pragma mark - Storage and state

NSString *SCILicenseStoredKey(void) {
    NSString *key = SCIPanelReadString(kSCILicenseKeyPref, nil);
    return key.length ? key : nil;
}

BOOL SCILicenseIsEnforced(void) {
    // Off unless switched on. The whole reasoning is in the header: a gate introduced in the
    // same release that enforces it breaks every existing install before a key exists to fix
    // them with.
    return SCIPanelReadBool(kSCILicenseEnforcePref, NO);
}

/// The last time the server confirmed the key, and the ids it has revoked.
///
/// In NSUserDefaults for this process rather than in the panel's plist: a sandboxed app cannot
/// write the panel's domain -- that is a lesson this repository already paid for with the Watch
/// tweak -- and this is a cache, not a setting. Each app keeping its own copy costs one request
/// per app per six hours and needs no cross-sandbox write at all.
static NSString *const kSCILastCheckDefault = @"albrhi_licence_last_check";
static NSString *const kSCIRevokedDefault   = @"albrhi_licence_revoked";

static BOOL SCIKeyIsRevoked(NSDictionary *payload) {
    NSString *identifier = payload[@"id"];
    if (![identifier isKindOfClass:[NSString class]] || !identifier.length) return NO;

    NSArray *revoked = [[NSUserDefaults standardUserDefaults] arrayForKey:kSCIRevokedDefault];
    return [revoked isKindOfClass:[NSArray class]] && [revoked containsObject:identifier];
}

SCILicenseState SCILicenseCurrentState(void) {
    NSDictionary *payload = nil;
    SCILicenseState state = SCIEvaluateKey(SCILicenseStoredKey(), &payload);
    if (state != SCILicenseStateValid) return state;

    if (SCIKeyIsRevoked(payload)) return SCILicenseStateRevoked;

    // Grace. The key is signed and in date; the only open question is whether it has been
    // withdrawn, and that needs the server. One day, then the answer stops being assumed.
    NSTimeInterval last = [[NSUserDefaults standardUserDefaults] doubleForKey:kSCILastCheckDefault];
    if (last > 0 && [NSDate date].timeIntervalSince1970 - last > SCILicenseGraceSeconds) {
        return SCILicenseStateGrace;
    }

    return SCILicenseStateValid;
}

BOOL SCILicenseAllows(void) {
    if (!SCILicenseIsEnforced()) return YES;

    switch (SCILicenseCurrentState()) {
        case SCILicenseStateValid:
            return YES;

        // Grace is *allowed*, and that is the point of having it: the key is genuine and in
        // date, and the only thing missing is a network this code has no right to demand. It is
        // reported, not punished.
        case SCILicenseStateGrace:
            return YES;

        default:
            return NO;
    }
}

BOOL SCILicenseStoreKey(NSString *key, SCILicenseState *outState) {
    NSDictionary *payload = nil;
    SCILicenseState state = SCIEvaluateKey(key, &payload);
    if (outState) *outState = state;

    if (state != SCILicenseStateValid) return NO;

    CFPreferencesSetAppValue((__bridge CFStringRef)kSCILicenseKeyPref,
                             (__bridge CFStringRef)key,
                             (__bridge CFStringRef)@"com.albrhi.panel");
    CFPreferencesAppSynchronize((__bridge CFStringRef)@"com.albrhi.panel");

    // A key accepted now is a key confirmed now: without this the very first launch after
    // entering one would already be a day into its grace period.
    [[NSUserDefaults standardUserDefaults] setDouble:[NSDate date].timeIntervalSince1970
                                              forKey:kSCILastCheckDefault];
    return YES;
}

void SCILicenseForgetKey(void) {
    CFPreferencesSetAppValue((__bridge CFStringRef)kSCILicenseKeyPref, NULL,
                             (__bridge CFStringRef)@"com.albrhi.panel");
    CFPreferencesAppSynchronize((__bridge CFStringRef)@"com.albrhi.panel");
}


#pragma mark - Check-in

void SCILicenseCheckInIfDue(void) {
    if (!SCILicenseStoredKey()) return;

    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSTimeInterval last = [defaults doubleForKey:kSCILastCheckDefault];
    if (last > 0 && [NSDate date].timeIntervalSince1970 - last < kSCILicenseCheckInterval) return;

    NSURL *url = [NSURL URLWithString:kSCILicenseEndpoint];
    if (!url) return;

    NSURLSessionConfiguration *configuration =
        [NSURLSessionConfiguration ephemeralSessionConfiguration];

    // Short, and never waited on. A licence check that can hold up a launch is a licence check
    // that will one day hold up every launch, and this project has a standing rule against a
    // fallback that hides a fault -- a hung request is that fault with a spinner over it.
    configuration.timeoutIntervalForRequest = 8;
    configuration.timeoutIntervalForResource = 12;

    NSURLSession *session = [NSURLSession sessionWithConfiguration:configuration];
    NSURLSessionDataTask *task = [session dataTaskWithURL:url
        completionHandler:^(NSData *data, NSURLResponse *response, NSError *error) {
            NSInteger status = [response isKindOfClass:[NSHTTPURLResponse class]]
                ? ((NSHTTPURLResponse *)response).statusCode : 0;

            // Only a real answer counts. A timeout, a captive portal's login page or a 500 must
            // never be read as "revoked" -- that would take a paying user's features away
            // because a coffee shop's wifi asked them to sign in.
            if (error || status != 200 || !data.length) return;

            id parsed = [NSJSONSerialization JSONObjectWithData:data options:0 error:NULL];
            NSArray *ids = [parsed isKindOfClass:[NSDictionary class]] ? parsed[@"revoked"] : nil;

            if ([ids isKindOfClass:[NSArray class]]) {
                [defaults setObject:ids forKey:kSCIRevokedDefault];
            }
            [defaults setDouble:[NSDate date].timeIntervalSince1970 forKey:kSCILastCheckDefault];
        }];

    [task resume];
}


#pragma mark - Saying so

NSString *SCILicenseDescribeState(SCILicenseState state) {
    NSString *device = SCILicenseFingerprint();
    switch (state) {
        case SCILicenseStateValid:
            return [NSString stringWithFormat:@"licensed · device %@", device];
        case SCILicenseStateGrace:
            return [NSString stringWithFormat:@"licensed, not confirmed for over a day · device %@", device];
        case SCILicenseStateNone:
            return [NSString stringWithFormat:@"no key · device %@", device];
        case SCILicenseStateExpired:
            return [NSString stringWithFormat:@"key expired · device %@", device];
        case SCILicenseStateWrongDevice:
            return [NSString stringWithFormat:@"key was issued to another device · this one is %@", device];
        case SCILicenseStateRevoked:
            return [NSString stringWithFormat:@"key withdrawn · device %@", device];
        case SCILicenseStateMalformed:
            return @"that is not a valid key";
    }
    return @"?";
}

NSString *SCILicenseStatusLine(void) {
    if (!SCILicenseIsEnforced()) {
        return [NSString stringWithFormat:@"not enforced · device %@%@",
                SCILicenseFingerprint(),
                SCILicenseFingerprintIsWeak() ? @" (weak — no device-unique value readable)" : @""];
    }
    return SCILicenseDescribeState(SCILicenseCurrentState());
}
