#!/usr/bin/env python3
"""Issue and inspect Albrhi licence keys.

    python3 tools/licence.py keygen                       # once, ever
    python3 tools/licence.py issue <fingerprint> [--days 365] [--name "..."]
    python3 tools/licence.py verify <key>
    python3 tools/licence.py pubkey                       # the C array to embed
    python3 tools/licence.py export-web                   # the key the browser panel imports

**Why ECDSA P-256 and not Ed25519.** Ed25519 on iOS means CryptoKit, which is Swift-only, or a
vendored crypto library -- and this repository ships one Swift tweak precisely because Swift and
Orion cost it three separate things that Logos does not (see CLAUDE.md). `Security.framework`
verifies ECDSA P-256 from plain Objective-C with `SecKeyVerifySignature`, on every iOS this
project targets, with no dependency at all. The security margin is the same order; the surface
area is much smaller.

**Why `openssl` and not a Python library.** `cryptography` is not installed on the developer's
machine and adding a pip dependency to a repository whose whole toolchain is "python3 and the
system" is a cost with no return. `openssl` is already there.

**The private key never enters this repository.** `keygen` writes it to ~/.albrhi/ and prints
where. Anyone holding it can mint licences for every device forever, so it does not go in git, in
a build, in CI, or in a message. The public half is what gets embedded in the tweak.

Token format, deliberately boring:

    ALB1.<base64url(payload json)>.<base64url(ECDSA DER signature)>

The signature covers the ASCII bytes of everything before the last dot, so a payload edited by a
byte fails. The payload is readable on purpose -- there is nothing secret in it, and a licence
whose contents can be read by the person it was issued to is one they can check themselves.
"""

import base64, json, os, subprocess, sys, time

HOME = os.path.expanduser('~/.albrhi')
PRIV = os.path.join(HOME, 'licence-ec-private.pem')

MAGIC = 'ALB1'


def b64u(raw):
    return base64.urlsafe_b64encode(raw).decode().rstrip('=')


def unb64u(text):
    return base64.urlsafe_b64decode(text + '=' * (-len(text) % 4))


def run(args, **kw):
    return subprocess.run(args, check=True, capture_output=True, **kw)


def keygen():
    if os.path.exists(PRIV):
        sys.exit('refusing to overwrite %s\n'
                 'A new key invalidates every licence already issued. Move the old one aside '
                 'by hand if that is really what you want.' % PRIV)

    os.makedirs(HOME, mode=0o700, exist_ok=True)
    run(['openssl', 'ecparam', '-name', 'prime256v1', '-genkey', '-noout', '-out', PRIV])
    os.chmod(PRIV, 0o600)

    print('private key: %s  (never commit, never send)' % PRIV)
    print()
    pubkey()


def public_point():
    """The raw X9.62 point, which is what SecKeyCreateWithData wants.

    `openssl ec -pubout -outform DER` gives a SubjectPublicKeyInfo wrapper; for P-256 the last
    65 bytes of it are the uncompressed point (0x04 || X || Y). Sliced from the end rather than
    parsed, because the prefix is a fixed 26-byte header for this one curve and a DER parser here
    would be more code than the thing it parses.
    """
    der = run(['openssl', 'ec', '-in', PRIV, '-pubout', '-outform', 'DER']).stdout
    point = der[-65:]
    if len(point) != 65 or point[0] != 0x04:
        sys.exit('unexpected public key encoding — expected an uncompressed P-256 point')
    return point


def pubkey():
    point = public_point()
    print('// The public half of the Albrhi licence key, as an uncompressed P-256 point.')
    print('// Generated by tools/licence.py keygen. Safe to publish — it only verifies.')
    print('static const uint8_t kSCILicensePublicKey[65] = {')
    for i in range(0, 65, 12):
        chunk = point[i:i + 12]
        print('    ' + ' '.join('0x%02X,' % b for b in chunk))
    print('};')


def issue(fingerprint, days, name, tier):
    if not os.path.exists(PRIV):
        sys.exit('no private key at %s — run: python3 tools/licence.py keygen' % PRIV)

    fingerprint = fingerprint.strip().lower()
    if len(fingerprint) != 16 or any(c not in '0123456789abcdef' for c in fingerprint):
        sys.exit('a device fingerprint is 16 hex characters; the panel shows it under Licence')

    now = int(time.time())
    payload = {
        'v': 1,
        'id': b64u(os.urandom(9)),          # what a revocation names
        'dev': fingerprint,
        'tier': tier,
        'iat': now,
        'exp': now + days * 86400,
    }
    if name:
        payload['for'] = name

    # Separators without spaces and sorted keys: the bytes signed have to be reproducible, and
    # json.dumps' defaults are not stable across versions in either respect.
    body = b64u(json.dumps(payload, separators=(',', ':'), sort_keys=True).encode())
    signing_input = ('%s.%s' % (MAGIC, body)).encode()

    signature = run(['openssl', 'dgst', '-sha256', '-sign', PRIV], input=signing_input).stdout
    token = '%s.%s.%s' % (MAGIC, body, b64u(signature))

    print(token)
    print(file=sys.stderr)
    print('device  %s' % fingerprint, file=sys.stderr)
    print('tier    %s' % tier, file=sys.stderr)
    print('expires %s (%d days)' % (time.strftime('%Y-%m-%d', time.localtime(payload['exp'])), days),
          file=sys.stderr)
    print('id      %s   <- the string to revoke' % payload['id'], file=sys.stderr)


def export_web():
    """The private key in the one format WebCrypto can import.

    `crypto.subtle.importKey('pkcs8', ...)` is the only EC private-key import the Web Crypto API
    offers, and `openssl ecparam -genkey` writes SEC1 -- so the browser panel cannot read the key
    file as it sits on disk. This converts it without altering the key.

    Printed to stdout so it can be piped, with every warning on stderr so a pipe stays clean.
    """
    if not os.path.exists(PRIV):
        sys.exit('no private key at %s — run: python3 tools/licence.py keygen' % PRIV)

    print('This is the signing key itself.', file=sys.stderr)
    print('Anyone holding it can mint a licence for every device, forever.', file=sys.stderr)
    print('Paste it only into your own licence panel, on a device you control.', file=sys.stderr)
    print(file=sys.stderr)

    sys.stdout.write(run(['openssl', 'pkcs8', '-topk8', '-nocrypt', '-in', PRIV]).stdout.decode())


def verify(token):
    """Verify with the public key alone, which is what the device does.

    Deliberately not "does the private key match": this is the check the tweak performs, so
    running it here means the format is exercised by the same rules on both sides.
    """
    parts = token.strip().split('.')
    if len(parts) != 3 or parts[0] != MAGIC:
        sys.exit('not an Albrhi licence key')

    point = public_point()
    tmp = os.path.join(HOME, '.verify-pub.der')
    os.makedirs(HOME, mode=0o700, exist_ok=True)
    run(['openssl', 'ec', '-in', PRIV, '-pubout', '-out', tmp + '.pem'])

    signing_input = ('%s.%s' % (parts[0], parts[1])).encode()
    sig = os.path.join(HOME, '.verify-sig.bin')
    with open(sig, 'wb') as f:
        f.write(unb64u(parts[2]))

    try:
        run(['openssl', 'dgst', '-sha256', '-verify', tmp + '.pem', '-signature', sig],
            input=signing_input)
        ok = True
    except subprocess.CalledProcessError:
        ok = False
    finally:
        for f in (tmp + '.pem', sig):
            if os.path.exists(f):
                os.remove(f)

    payload = json.loads(unb64u(parts[1]))
    print(json.dumps(payload, indent=2, sort_keys=True))
    print()
    print('signature : %s' % ('valid' if ok else 'INVALID'))

    left = payload.get('exp', 0) - int(time.time())
    print('expiry    : %s' % ('expired' if left <= 0 else '%d day(s) left' % (left // 86400)))
    if not ok:
        sys.exit(1)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)

    command = sys.argv[1]
    if command == 'keygen':
        keygen()
    elif command == 'pubkey':
        pubkey()
    elif command == 'issue':
        if len(sys.argv) < 3:
            sys.exit('usage: licence.py issue <fingerprint> [--days N] [--name "..."] [--tier suite]')
        args = sys.argv[3:]
        days = int(args[args.index('--days') + 1]) if '--days' in args else 365
        name = args[args.index('--name') + 1] if '--name' in args else None
        tier = args[args.index('--tier') + 1] if '--tier' in args else 'suite'
        issue(sys.argv[2], days, name, tier)
    elif command == 'export-web':
        export_web()
    elif command == 'verify':
        if len(sys.argv) < 3:
            sys.exit('usage: licence.py verify <key>')
        verify(sys.argv[2])
    else:
        sys.exit(__doc__)


if __name__ == '__main__':
    main()
